### ISSUE TITLE
Restructure Redis connection management.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#2693]
Replace `SENTRY_REDIS_OPTIONS` with `redis.clusters` in `sentry.options`. The value of this option is is similar to the `DATABASES` setting, except values are a map that will be passed to the [`Cluster` constructor](https://github.com/getsentry/rb/blob/50ede887d9980d46fbe52aaa32d884c425f29c18/rb/cluster.py#L89).

For example, the current setting:

```
SENTRY_REDIS_OPTIONS = {
    'hosts': {
        0: {
            'host': '127.0.0.1',
            'port': 6379,
        }
    }
}
```

would instead have a value that is structured as:

```
{
    'default':
        'hosts': {
            0: {
                'host': '127.0.0.1',
                'port': 6379,
            }
        }
    },
}
```

In backends, the target cluster(s) should be provided by name to the backend constructor. For backwards compatibility, if no cluster is provided, either use the default cluster, or fall back to the old method of configuration (providing options directly to the backend constructor) and throw a deprecation warning. Don't allow passing both the cluster and old parameters.

For third-party plugin compatibility, create a derived value for the `SENTRY_REDIS_OPTIONS` setting from the default cluster options. This will be removed in the future, since it allows circumventing [our factory method that uses a shared connection pool](https://github.com/getsentry/sentry/blob/6a4227f32543d459e859c3fd8eb64b0ccb697be7/src/sentry/utils/redis.py#L18-L50). We'll need to decide on when formally remove this.

# Tasks

- [x] Add `redis.clusters` to [`sentry.options`](https://github.com/getsentry/sentry/blob/65332fc9ead7dafdb75eedeb672dbe1eabf4543d/src/sentry/options/defaults.py).
- [x] If the `redis.clusters` options is set but `SENTRY_REDIS_OPTIONS` setting isn't, provide a compatibility layer to allow access to `SENTRY_REDIS_OPTIONS` from the derived value from `redis.clusters`. If the `SENTRY_REDIS_OPTIONS` setting is set but the `redis.clusters` option isn't,  provide a compatibility layer to allow access via `redis.clusters`. If both are set, error and suggest only using the `redis.clusters` option.
- [x] Add Redis cluster manager that allows retrieving clusters by name, and uses our shared connection pool.
- [x] Update backends to prefer named clusters rather than connection parameters. (These will also need to be instantiated via the cluster manager, or at least continue to use the same shared pool.)
  - [x] Buffers
  - [x] Cache
  - [x] Digests
  - [x] Quotas
  - [x] Rate Limiter
  - [x] TSDB
- [x] Update supported plugins.
  - getsentry/sentry-hipchat-ac#24
- [x] Update documentation to reference configuration file option instead of `SENTRY_REDIS_OPTIONS`. 
- [x] Figure out a formal (public) deprecation strategy for `SENTRY_REDIS_OPTIONS`.

**Comment by tkaemming** [comment]
> It'd also be nice to create BROKER_URL from the default cluster connection options if none is provided.

@mitsuhiko pointed out this won't work for clustered configurations, so we can only derive the `BROKER_URL` when there is a single host.

**Comment by dcramer** [comment]
I think it's ok to just have BROKER_URL be a separate thing.

**Comment by tkaemming** [comment]
@mattrobenolt: This will result in deprecating/replacing the [`redis.options` option](https://github.com/getsentry/sentry/blob/master/src/sentry/options/defaults.py#L22) — would it make sense to add a `FLAG_DEPRECATED` flag that warns if this is either loaded from the configuration file or options store?

**Comment by tkaemming** [comment]
Also, does it make sense to remove the Redis configurations from the settings file (other than `BROKER_URL` or anything necessary for temporary backwards compatibility) and allow "new style" named cluster configuration to only happen via the configuration file?

**Comment by mattrobenolt** [comment]
> This will result in deprecating/replacing the redis.options option — would it make sense to add a FLAG_DEPRECATED flag that warns if this is either loaded from the configuration file or options store?

Literally nothing and nobody used this. It was never documented, and was just a test to make sure things worked. This option didn't even work since nothing read from it. It was moreorless a placeholder. So just repurpose however you want.

> Also, does it make sense to remove the Redis configurations from the settings file (other than BROKER_URL or anything necessary for temporary backwards compatibility) and allow "new style" named cluster configuration to only happen via the configuration file?

If we push them into `config.yml`, yes, we should. I'd keep a shim in `runner.initializer` to pick up old `REDIS_*` settings, and transform them into `options`, then when these stores are initialized, only do `options.get`, etc. If that makes sense.

**Comment by tkaemming** [comment]
> It was never documented, and was just a test to make sure things worked. This option didn't even work since nothing read from it.

Okay, that makes it easy. :smile:

**Comment by mattrobenolt** [comment]
> I think it's ok to just have BROKER_URL be a separate thing.

Couldn't we just have a cluster named 'broker' ? And assert that it can only contain one host?

```python
broker_config = clusters.get('broker', clusters['default'])
assert len(broker_config) == 1
```

My concern with `BROKER_URL` is because it's in a completely different format from any other redis configuration, but typically overlaps. It's common that one redis instance is used for all of Sentry, and only in extreme cases, people would need to shard across many.

BUT, this is a little weird since `BROKER_URL` isn't _just_ redis. It may also be RabbitMQ.

So I'm ok leaving `BROKER_URL` as is. We can maybe introduce a sane default, and say, if `BROKER_URL` isn't defined, assume they want the 'default' redis cluster? But probably not much value.

Just food for thought.

**Comment by tkaemming** [comment]
We need to figure out a deprecation strategy for this, and how to safely integrate with plugins. The only plugin that I am aware of (from grepping the hosted Sentry dependencies) that uses Redis directly is [`sentry-hipchat-ac`](https://github.com/getsentry/sentry-hipchat-ac/blob/master/sentry_hipchat_ac/mentions.py#L16).

It might make sense to deprecate `SENTRY_REDIS_OPTIONS` at the same time that we move all backend component configurations (cache, TSDB, etc.) to the configuration file?

**Comment by dcramer** [comment]
Still -1 on BROKER_URL using clusters. It will just mean more people opening support tickets.

**Comment by dcramer** [comment]
@tkaemming i think its fine that sentry-hipchat-ac will still read the old settings but we can immediately add support for clusters in it

**Comment by kzw** [comment]
Getting a deprecation warning on upgrading from 7.x to 8.9.0.  Above dictionary replacement in the original post does not compile is valid python.  The only other reference related to this problem I can see is in `config.yml` and that fails to run with `unhashable type 'dict'` error.

The warning I get is 

```The SENTRY_REDIS_OPTIONS setting is deprecated. Please use SENTRY_OPTIONS["redis.clusters"] instead. This setting will be removed in Sentry 8.5.```

Literal replacement in this warning message does not work.


--------
I am referring to this python dict suggested as replacement above.

{
    'default':
        'hosts': {
            0: {
                'host': '127.0.0.1',
                'port': 6379,
            }
        }
    },
}

**Comment by mattrobenolt** [comment]
You need:

```yaml
redis.clusters:
  default:
    hosts:
      0:
        host: '127.0.0.1'
        port: 6379
```

in config.yaml

**Comment by kzw** [comment]
Ok.  That is acceptable and I believe the `unhashable type 'dict'` was this warning

`The 'hosts' parameter of SENTRY_TSDB_OPTIONS setting is deprecated. Please use SENTRY_TSDB_OPTIONS["cluster"] instead. This setting will be removed in Sentry 8.5.`

I did the replacement but did not work; so I am now sticking to the old configuration.  Any reference on how to make this change.  Currently I have

```
SENTRY_TSDB_OPTIONS = {
    'hosts': {
        0: {
            'host': 'xyz',
            'port': 6379
        }
    }
}

```

**Comment by dcramer** [comment]
@kzw take a look at our docs, as we don't provide support here.
