### ISSUE TITLE
DSym Checklist

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#2900]
- [x] make stacktrace rendering pretty
- [ ] move READMEs into real documentation
- [x] in-app support
- [x] correct instruction offset display
- [x] pad out addresses in user interface
- [ ] integrate user reported stacktraces for unity

Nice to have:
- [ ] swift demangling

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
