### ISSUE TITLE
Profiling Issue launch

### ISSUE THREAD

**Issue by logicalbomb** [getsentry/sentry#42044]
Final items to do before we launch Profiling Issues.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/42048
- [x] https://github.com/getsentry/sentry/issues/42049
- [x] https://github.com/getsentry/sentry/issues/42050
- [x] https://github.com/getsentry/sentry/issues/42055
- [ ] https://github.com/getsentry/sentry/issues/42178
- [x] https://github.com/getsentry/sentry/issues/42529
- [x] https://github.com/getsentry/sentry/issues/42530
- [ ] https://github.com/getsentry/sentry/issues/42531
- [ ] https://github.com/getsentry/sentry/issues/43948
- [ ] https://github.com/getsentry/sentry/issues/42278
- [ ] https://github.com/getsentry/sentry/issues/43413
- [ ] https://github.com/getsentry/sentry/issues/44085
- [ ] https://github.com/getsentry/sentry/issues/44129
- [ ] https://github.com/getsentry/sentry/issues/44117
- [ ] https://github.com/getsentry/sentry/issues/44121
- [ ] https://github.com/getsentry/sentry/issues/44122
- [ ] https://github.com/getsentry/sentry/issues/44429
```

---------

### [epic in Jira](https://getsentry.atlassian.net/browse/ISP-95)

**Comment by chadwhitacre** [comment]
What's the right `Team: *` [label](https://github.com/getsentry/sentry/labels?q=team) to apply to this issue?

**Comment by chadwhitacre** [comment]
Okay this is painful, I'm sorry. Details on https://github.com/getsentry/team-ospo/issues/105, likely to be some additional noise before the automation is set up correctly. Sorry.
