### ISSUE TITLE
Sidebar follow-up issues

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#4281]
- [x] **Critical** clicking within the project header activates the star/unstar action (not just on the button itself) (see #4287)
- [x] Audit log is not full-width
- [x] Sidebar needs poofed on share page (or needs left-aligned)
- [x] footer should hide on mobile
- [x] /api/ needs modal
- [x] strange selector arrow for organization pullout on mobile  
  https://www.dropbox.com/s/r6rzgobbxwchcma/Screenshot%202016-10-05%2018.49.16.png?dl=0
- [x] Entire broadcast item appears clickable, but only "Read more" goes anywhere
- [x] Move broadcast list item up
- [x] add member shows sidebar
- [x] bad padding in broadcasts
- [x] billing page, and likely every single other modal, has same issues with sidebar/frame showing
- [x] contexts need more padding (e.g. a long email address will brush up against the browser icon)
- [x] Sidebar items need hover text
- [x] settings do not wrap correctly https://www.dropbox.com/s/mfs2c50u6n1rl71/Screenshot%202016-10-07%2001.04.01.png?dl=0
- [x] margin issues on message https://www.dropbox.com/s/6ri2g8r8k0r7fq0/Screenshot%202016-10-07%2013.12.11.png?dl=0
- [x] context should _not_ look the same as the title https://www.dropbox.com/s/xm3elgidkaxfor9/Screenshot%202016-10-07%2013.43.12.png?dl=0
- [x] Sticky stream actions toolbar tooltips are clipped by top of browser
- [x] new broadcasts arent highlighted in popup (they used to be bold or something)
- [x] muted box display issues https://www.dropbox.com/s/2ltl1scll8oggpe/Screenshot%202016-10-06%2000.49.22.png?dl=0 (fixed in #4344)
- [x] downcase request urls https://twitter.com/dave1010/status/784418194354237444 (fixed in #4344)
- [ ] Team settings should have organization chrome / sidebar
- [ ] Pin active org to top of org sidebar panel
- [ ] Chained exceptions don't look chained

**Comment by dcramer** [comment]
FYI there's a high priority issue which clicking the project header toggles the star action, not just clicking on the button

**Comment by dcramer** [comment]
a second, even more critical issue is the way flex is behaving when certain things arent wrapping:

https://twitter.com/YorickH/status/783967548576374784

**Comment by dcramer** [comment]
attached commit fixes the critical wrapping issue
