### ISSUE TITLE
Crons: SDK for Node.JS

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#43661]
This issue tracks adding Crons to our Node JS package.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-javascript/issues/8006
- [ ] https://github.com/getsentry/sentry-docs/pull/6842
- [ ] https://github.com/getsentry/sentry-javascript/issues/8067
```

**Is this issue important to you?**
Please feel free to upvote or provide your feedback, we'd love to hear more about your use cases.

**Comment by AbhiPrasad** [comment]
See https://github.com/getsentry/sentry-javascript/pull/7996 at an early attempt as this we twitch streamed building: https://www.twitch.tv/videos/1805791207
