### ISSUE TITLE
Perf Migration: Remove old perf issue creation code

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#44084]
Once we're finished with the migration and are happy that everything is working well, we can remove all the old code associated with creating performance issues in the transaction table. We might break this up into several task as well.

Tasks I can think of here, please add more that are missed
```[tasklist]
### Tasks
- [ ] Remove `group_ids` column from transactions dataset in snuba and logic related to it
- [ ] Remove `group_ids` from eventstream
- [ ] Remove `group_ids` from `Event`
- [x] In `save_transaction_events`, https://github.com/getsentry/sentry/blob/6f0b68a2782204a2bd2453333b43c6d5a76135e8/src/sentry/event_manager.py#L2449 move `_detect_performance_problems` to after we save to nodestore, remove all calls that are related to creating issues
- [ ] Find all places where we query performance issues via the transaction dataset and remove those branches. Work from https://github.com/getsentry/sentry/issues/43982 will probably be helpful in tracking these places down.
```

**Comment by ceorourke** [comment]
Not related to perf issue creation, but we can do a lot of cleanup of integration/email code that specifically checks for performance issues and use the generic paths assuming they're passing the evidence along.

**Comment by mikejihbe** [comment]
Probably not going to be prioritized given the backing stores and schemas for these data are changing. Closing, but LMK if you feel differently @wedamija

**Comment by wedamija** [comment]
> Probably not going to be prioritized given the backing stores and schemas for these data are changing. Closing, but LMK if you feel differently [@wedamija](https://github.com/wedamija)

I think this still needs to be done - Not the dataset itself, but passing group ids to eventstream and post process group should be cleaned up.
