### ISSUE TITLE
Add dynamic sdk options to JavaScript loader backend

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry#44225]
Playground PR: https://github.com/getsentry/sentry/pull/44237

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/44228
- [ ] https://github.com/getsentry/sentry/pull/44346
- [ ] https://github.com/getsentry/sentry/pull/44492
- [ ] https://github.com/getsentry/sentry/pull/44496
- [ ] https://github.com/getsentry/sentry/pull/44876
```

**Comment by AbhiPrasad** [comment]
Once https://github.com/getsentry/sentry/pull/44876 has been merged in, the backend changes to get the loader working are all done.

All that is left is for the frontend to update the project key settings to enable the different bundles (replay, performance etc.)

The project key settings are detailed in https://github.com/getsentry/sentry/pull/44496
