### ISSUE TITLE
Sentry SDK Crash Detection for Cocoa

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry#44342]
### Problem Statement

As an APM company, the reliability of our SDKs is one of our most essential quality goals. If our SDK breaks the customer, we fail. Our SDK philosophy refers to this as [degrade gracefully](https://develop.sentry.dev/sdk/philosophy/#degrade-gracefully).

For some SDKs, like mobile SDKs, we primarily rely on users to report SDK crashes because we don't operate them in production. If users don't report them, we are unaware. Instead, we should detect crashes caused by our SDKs when they happen so we can proactively fix them.

This solution doesn't seek to detect severe bugs, such as the transport layer breaking or the SDK continuously crashing. CI or other quality mechanisms should find such severe bugs. Furthermore, the solution only targets SDKs maintained by us, Sentry.

The goal is to only start with Cocoa SDK crashes. If that works properly, we can extend the algorithm to find SDK crashes of other Sentry SDKs.

### Solution

We want to detect SDK crashes during event processing as decided in the [RFC](https://github.com/getsentry/rfcs/pull/63).

```[tasklist]
### Tasks for Alpha Phase
- [x] Algorithm to detect Cocoa SDK crashes by looking at the stacktrace
- [x] Duplicate the event with only the essential field so the event doesn’t contain any customer data.
- [x] https://github.com/getsentry/sentry/issues/46173
- [x] https://github.com/getsentry/sentry/issues/46174
- [ ] https://github.com/getsentry/sentry/issues/46175
- [ ] https://github.com/getsentry/sentry/issues/46177
- [ ] https://github.com/getsentry/sentry/pull/49528
- [ ] https://github.com/getsentry/sentry/issues/49749
- [ ] https://github.com/getsentry/sentry/issues/51023
- [ ] https://github.com/getsentry/sentry/issues/50916
- [ ] https://github.com/getsentry/sentry/issues/51024
- [ ] https://github.com/getsentry/sentry/issues/51025
- [ ] https://github.com/getsentry/sentry/issues/52081
- [ ] https://github.com/getsentry/sentry/issues/52094
- [ ] https://github.com/getsentry/sentry/issues/50401
- [ ] https://github.com/getsentry/sentry/pull/52109
- [ ] https://github.com/getsentry/sentry/pull/52119
- [ ] https://github.com/getsentry/sentry/pull/52247
```

```[tasklist]
### Other open tasks
- [ ] https://github.com/getsentry/sentry/pull/52331
- [ ] https://github.com/getsentry/sentry/pull/52501
- [x] Validate grouping
```
```[tasklist]
### Rollout PRs
- [ ] https://github.com/getsentry/getsentry/pull/11035
- [ ] https://github.com/getsentry/getsentry/pull/11046
- [ ] https://github.com/getsentry/getsentry/pull/11065
```

**Comment by philipphofmann** [comment]
Current state is here https://github.com/getsentry/sentry/tree/feat/sdk-crash-monitoring

**Comment by philipphofmann** [comment]
### Collected Data

_The current state as of June 14th, 2023._

I have a POC tested locally in this PR https://github.com/getsentry/sentry/pull/49928. Nothing is merged to master yet. We decided to split the PR into multiple smaller PRs so it's easier to review. You can have a look at a clean diff [here](https://github.com/getsentry/sentry/compare/master...feat/sdk-crash-monitoring).

The feature will be called in post_process https://github.com/getsentry/sentry/blob/ea6b6dc281a0a833cd58f4ff2e8274e26ee9e654/src/sentry/tasks/post_process.py#L1078-L1080

Then it takes the event data and only keeps properties of the event based on an allow list. We must still remove debug images and define an allow list for exceptions (https://github.com/getsentry/sentry/issues/50710):

https://github.com/getsentry/sentry/blob/ea6b6dc281a0a833cd58f4ff2e8274e26ee9e654/src/sentry/utils/sdk_crashes/sdk_crash_detection.py#L56

https://github.com/getsentry/sentry/blob/ea6b6dc281a0a833cd58f4ff2e8274e26ee9e654/src/sentry/utils/sdk_crashes/event_stripper.py#L30-L54

Currently, the code only keeps non-in-app frames and SDK frames. We still have to refine this to use an allow list (https://github.com/getsentry/sentry/issues/50916) cause if users change the in app logic, we might collect customer frames. 

https://github.com/getsentry/sentry/blob/ea6b6dc281a0a833cd58f4ff2e8274e26ee9e654/src/sentry/utils/sdk_crashes/event_stripper.py#L122-L132

Finally, it saves the stripped event data to a dedicated project
https://github.com/getsentry/sentry/blob/ea6b6dc281a0a833cd58f4ff2e8274e26ee9e654/src/sentry/utils/sdk_crashes/sdk_crash_detection.py#L17-L19

**Comment by philipphofmann** [comment]
@HazAT, just the SDK frames won't be enough sometimes to know what's happening. System frames would be helpful as well. So therefore, my plan is to add an allow list with items such as CoreFoundation, UIKit, UIKitCore, GraphicsServices, etc.

**Comment by philipphofmann** [comment]
We decided to move away from the in-app logic and only keep SDK frames and system library frames instead. For more detail see https://github.com/getsentry/sentry/issues/50916.

**Comment by philipphofmann** [comment]
The SDK Crash detection is up and running for the Cocoa SDK. We will open more issues in the future to roll it out to more SDKs.
