### ISSUE TITLE
View Hierarchies in Event Details

### ISSUE THREAD

**Issue by brentc** [getsentry/sentry#44426]
Project plan for View Hierarchies Project

## Milestones
```[tasklist]
### Milestone 1
- [ ] #43355
- [ ] #44023
- [ ] #44300
- [ ] #43872
```

```[tasklist]
### Milestone 2
- [ ] #43731
```

```[tasklist]
### Milestone 3
- [ ] #43320
- [ ] #43875
- [ ] #43873
```

```[tasklist]
### Milestone 4
- [ ] https://github.com/getsentry/sentry/issues/44590
- [ ] https://github.com/getsentry/sentry/issues/44592
- [ ] #42997
- [ ] https://github.com/getsentry/sentry/issues/44656
- [ ] https://github.com/getsentry/sentry/issues/44754
- [ ] https://github.com/getsentry/sentry/issues/44747
- [ ] https://github.com/getsentry/sentry/issues/44743
- [ ] #44588
```

```[tasklist]
### Post GA
- [ ] https://github.com/getsentry/sentry/issues/45239
- [ ] https://github.com/getsentry/sentry/issues/46036
```

## Release Plan
```[tasklist]
- [x] Release to EA
- [x] Release to GA
- [x] Release to Single Tenant/Self-Hosted
```

┆Issue is synchronized with this [Jira Epic](https://getsentry.atlassian.net/browse/MDX-6) by [Unito](https://www.unito.io)

**Comment by narsaynorath** [comment]
SDKs that have deobfuscation working/don't need it:

| SDK | iOS | Android |
| ---- | ----- | ------- | 
| iOS | ✅  | N/A |
| Android | N/A | ✅  |
| React Native | ✅  | ❌  |
| Flutter | ❓ | ❌ |

**Comment by narsaynorath** [comment]
Removed the :X: from Flutter on Android because it doesn't use proguard. So I'll be responsible for fixing the Flutter symbolication in the ingestion pipeline, and the work the SDK team is doing in Android should resolve the React Native functionality because we'll be able to ingest the event with its attachment.
