### ISSUE TITLE
Mobile Device Classification

### ISSUE THREAD

**Issue by brentc** [getsentry/sentry#44449]
Project details to be determined.

```[tasklist]
### Planning
- [x] [GitHub discussion](https://github.com/getsentry/sentry/discussions/44422)
- [x] Product requirements
- [x] Proposed design
- [x] Implementation proposal reviewed
- [x] Milestones defined
- [x] Release schedule drafted
```

## Proposal
Users have a hard time understanding impact and performance of their mobile apps across thousands of available device models today. We will introduce a `device.class` queryable tag that categorizes devices into classes of `high`, `medium`, `low` to simplify understanding device performance levels.

The quick technical details of how this will be done are:

- In relay, we will synthesize a new value in the `device` context, which we call `device.class`. The criteria we will be using is as follows:
```
apple:
    < 2000mhz => low (class 1)
    < 3000mhz => med (class 2)
    otherwise high (class 3)
android:
    < 8 cores or < 2000mhz or < 4gb memory => low (class 1)
    < 2500 mhz or < 6gb memory => med (class 2)
    otherwise high (class 3)
```
- **note**: the `device.class` context will be stored as a number value instead of literal `high`, `medium`, `low`. This is to ensure we have future runway for higher performance devices, at which point we can adjust our mapping of `high`, `medium`, `low` to number value.
- promote `device.class` to a tag. This enables `device.class` to be used in all areas tags are normally used (ie discover, issue details page, tags summary, etc).
- update all areas that display `device.class` to map from number value to `high`, `medium`, `low`. For most cases, this means updating apis with this mapping.
- any final frontend design changes, ie hoist `device.class` in tag summary

## Assumptions
Mobile SDKs aren't sending core frequency and core count yet, but we can still proceed in parallel. We can assume that core count will be a simple number and core frequency will be a number representing frequency in mhz
https://github.com/getsentry/team-mobile/issues/77#issuecomment-1443809549

## Milestones
```[tasklist]
### Milestone 1 - _synthesize and ingest numeric device.class context_
- [ ] https://github.com/getsentry/sentry/issues/44841
- [ ] https://github.com/getsentry/sentry/issues/45245
- [ ] https://github.com/getsentry/sentry/issues/45587
```
```[tasklist]
### Milestone 2 - _promote to tag and enable querying device.class in discover_
- [ ] https://github.com/getsentry/sentry/issues/45333
- [ ] https://github.com/getsentry/sentry/issues/45334
- [ ] https://github.com/getsentry/sentry/issues/45335
- [ ] https://github.com/getsentry/sentry/issues/45336
- [ ] https://github.com/getsentry/sentry/issues/45337
```
```[tasklist]
### Milestone 3 - _format device.class everywhere else_
- [ ] https://github.com/getsentry/sentry/issues/45589
- [ ] https://github.com/getsentry/sentry/issues/45590
- [ ] https://github.com/getsentry/sentry/issues/45591
- [ ] https://github.com/getsentry/sentry/issues/45759
- [ ] https://github.com/getsentry/sentry/issues/45831
- [ ] https://github.com/getsentry/sentry/issues/45832
- [ ] https://github.com/getsentry/sentry/issues/45833
- [ ] https://github.com/getsentry/sentry/issues/45834
- [ ] https://github.com/getsentry/sentry/issues/46046
```
```[tasklist]
### Milestone 4 - _release to GA_
- [ ] https://github.com/getsentry/sentry/issues/46039
- [ ] https://github.com/getsentry/sentry/issues/46040
```

## Release Status
```[tasklist]
- [x] Internal
- [x] Early Adopters
- [x] General Availability
```

## External Links
* [Notion Page](https://www.notion.so/sentry/Investigate-Mobile-Device-Classification-for-Issues-Transactions-and-Discover-and-create-a-proje-ab93283c69db40968695bc77aa7fad7a?pvs=4)
* https://github.com/getsentry/sentry/discussions/44422
* [PRD](https://www.notion.so/sentry/Device-Classification-PRD-8180dc29b01240ad8f4d53177cfb798d)
* [JIRA Task](https://getsentry.atlassian.net/browse/MDX-9)

**Comment by edwardgou-sentry** [comment]
todo: 
- add memory to android medium classification
- look into creating device.class as a column instead of a tag
