### ISSUE TITLE
Crons: UI/UX updates to listing page

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#44460]
This issue tracks updates to our landing/listing page of Crons' monitors ([internal link](https://www.figma.com/file/cfcxnhwGet0cHZKEZXY5kV/Crons?node-id=0%3A1&t=etl2lQ6NZVzIWH7V-0)).

![Image](https://user-images.githubusercontent.com/1308394/218206184-4f0d0d20-80e2-4bce-8931-0757a2c5a1c1.png)

```[tasklist]
### Tasks
- [x] Update table headers and column ordering
- [x] Remove "Last check-in" and add a new "Next check-in" column
- [x] Update Crons Monitor status colors/icons
- [x] Add status column
- [x] Add actions column
- [x] Add schedule column
- [ ] https://github.com/getsentry/sentry/issues/44670
- [ ] https://github.com/getsentry/sentry/issues/44686
- [ ] https://github.com/getsentry/sentry/issues/43718
- [ ] https://github.com/getsentry/sentry/pull/44931
```

**Comment by gaprl** [comment]
This should fix https://github.com/getsentry/sentry/issues/43718.
