### ISSUE TITLE
Mobile Display Timing Performance Issue(s)

### ISSUE THREAD

**Issue by brentc** [getsentry/sentry#44504]
### Planning
- [x] GitHub discussion?
- [ ] Product requirements
- [x] Proposed design
- [x] [Standard project plan template](https://www.notion.so/sentry/GitHub-Epic-Issue-Template-72b517d97e4c46168b2670545d70b8dd) added to issue
- [x] Implementation proposal drafted
- [x] Dependent teams consulted
- [x] Milestones defined
- [x] Release schedule drafted
- [ ] Implementation proposal reviewed

 ## Proposal
Introduce a database on file IO Performance Issue, and then show them in the context of the Display Timing metrics; Time To Initial Display and Time To First Display.

## Milestones
```[tasklist]
### Milestone 1 - _Add TTID & TTFD to frontend & start collecting DB io metrics_
- https://github.com/getsentry/sentry/issues/45879
- https://github.com/getsentry/sentry/issues/45880
- https://github.com/getsentry/sentry/issues/45956
- https://github.com/getsentry/sentry/issues/45930
- [ ] https://github.com/getsentry/sentry/issues/45930
- [ ] https://github.com/getsentry/sentry/issues/45956
- [ ] https://github.com/getsentry/sentry/issues/45880
- [ ] #45879
- [ ] https://github.com/getsentry/sentry/issues/46010
```

## Dependent Mobile SDK Work
* [ ] https://github.com/getsentry/team-mobile/issues/102

## Release Status
```[tasklist]
- [ ] Early Adopters - April 14th
- [ ] General Availability - May 7
- [ ] Single Tenant & Self-Hosted - Depends
```

## External Links
* https://github.com/getsentry/sentry/discussions/45152
* [Product Requirements Doc](#)
* [Notion Page](https://www.notion.so/sentry/Identify-which-performance-issues-contribute-to-Display-Timings-and-EA-at-least-1-611c7bd1e0404787973889eae193eab4)
* [JIRA Issue](https://getsentry.atlassian.net/browse/MDX-11)

**Comment by brentc** [comment]
This is now in GA for iOS. Mobile team will be implementing any additional upgrades needed for the android support when it's ready.
