### ISSUE TITLE
Replay: Allow Inbound Filters to apply to replays

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#44700]
### Problem Statement

Replays can capture some sessions that are noisy. Sentry has some inbound filters for errors but those don't apply
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/1633368/219196840-48c20386-8d64-4367-a41a-764c425964f2.png">

See also:
1.  [Zendesk](https://sentry.zendesk.com/agent/tickets/115080)

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-javascript/issues/10036
- [ ] Update the product docs, quota management for Replays
- [ ] Apply React Hydration filters also React Hydration fail errors are not filtered even using Filter out hydration errors in Replay #53234
- [ ] Apply inbound filters from settings to Replays
```

**Comment by jiwon-mun** [comment]
Do you have any plans on when to start working on this?
Or is there any alternative to solve the problem?

For me, it's such a serious thing that I can't use Replay.

I'm looking forward to good news.

**Comment by bruno-garcia** [comment]
@jiwon-mun to help us prioritize things could you help us by explaining what filters exactly you rely on? 
As a work around, I wonder if you can detect them client-side, avoiding them leave the browser completely. With `beforeSend` or an `eventProcessor`. If the error is dropped client-side, the Replay also never leaves the browser.

**Comment by bruno-garcia** [comment]
One situation that we identified (perhaps it's the same serious case @jiwon-mun mentioned that makes Replay unsable) is for NextJS apps that have orders of magnitude more Hydration errors than any legit error. Sentry is dropping these by default, through inbound filters and Replays, unaware, get sampled in. Resulting in all quota used up without any links to errors in Sentry.

**Comment by bruno-garcia** [comment]
Relates to: 
* https://github.com/getsentry/sentry-javascript/issues/10036

**Comment by bruno-garcia** [comment]
For folks with React ChunkLoadError or Hydration errors that don't want those sampled, a work around is to filter them client side:

```
Sentry.int({
  inboundFilters: [
    // filter react hydration errors
    /reactjs\.org\/docs\/error-decoder\.html\?invariant=(418|419|422|423|425)/,
    /(does not match server-rendered HTML|Hydration failed because)/i,
    // filter chunk load errors
    "ChunkLoadError: Loading chunk",
    /Uncaught (.*): ChunkLoadError: Loading chunk/
  ]
});
```

**Comment by bruno-garcia** [comment]
Related: Generic inbound filters has been released: https://github.com/getsentry/sentry/issues/57799#issuecomment-1983388370

**Comment by bruno-garcia** [comment]
Through https://github.com/getsentry/relay/pull/3420 we now have **some** types of inbound filters now also applying to Replays. For example:
* IP Address
* Releases
* Request URL
* User-Agent

For other types of filters we'll need to further expand this capability

**Comment by bruno-garcia** [comment]
Pending documentation here and since this is live and users see a drop in accepted replay and a much more significant increase in filtered replays. That's because we count each filtered **segment**, where when we count an accepted replay, we only count 1 segment.
