### ISSUE TITLE
Crons: Update docs to indicate how to send environments

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry#45025]
Upon releasing multi-environment support, we need to update our documentation to reflect how to use in each platform we currently support.

```[tasklist]
### Tasks
- [x] https://github.com/getsentry/sentry-docs/pull/6634
- [ ] https://github.com/getsentry/sentry-docs/pull/6679
- [ ] https://github.com/getsentry/sentry-cli/issues/1564
```

**Comment by evanpurkhiser** [comment]
Closing, will follow up on for the CLI once we've merged completed https://github.com/getsentry/sentry-cli/issues/1564
