### ISSUE TITLE
Vital Annotated Traces

### ISSUE THREAD

**Issue by wmak** [getsentry/sentry#45395]
### Planning
- [x] GitHub discussion?
  - Skipping
- [ ] Product requirements
- [x] Proposed design
  - https://www.figma.com/file/4GvQDmTJ744oHqxk4uAKtJ/mdx---display-timings-(ttid%2C-ttfd)?node-id=53%3A125
- [x] [Standard project plan template](https://www.notion.so/sentry/GitHub-Epic-Issue-Template-72b517d97e4c46168b2670545d70b8dd) added to issue
- [x] Implementation proposal drafted
- [x] Dependent teams consulted
- [x] Milestones defined
- [x] Release schedule drafted
- [ ] Epic reviewed

## Proposal
Traces give important context to Vitals and Performance Issues, but currently we show neither in our trace view, or in our trace navigator

## Milestones

```[tasklist]
### Milestone 1 - _Trace View matches proposed design_
- [x] https://github.com/getsentry/sentry/issues/45314
- [x] https://github.com/getsentry/sentry/issues/45317
- [ ] https://github.com/getsentry/sentry/issues/45394
- [x] https://github.com/getsentry/sentry/issues/45393
- [ ] https://github.com/getsentry/sentry/issues/45778
```

## Release Status
- [ ] General Availability
- [ ] Single Tenant & Self-Hosted
