### ISSUE TITLE
[Epic] Replay: HTTP Request/Response in Network tab

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#45525]
This tracks the work required to deliver network request/response on Replay the Network tab.
It's a very common customer request. 

JS SDK tracking this: https://github.com/getsentry/sentry-javascript/issues/7103 (several 👍 here).

```[tasklist]
## Internal Release
- [ ] https://github.com/getsentry/team-replay/issues/43
- [ ] https://github.com/getsentry/sentry-javascript/issues/7373
- [ ] https://github.com/getsentry/sentry/issues/46051
- [ ] https://github.com/getsentry/sentry/issues/46052
- [ ] https://github.com/getsentry/sentry/issues/46080
- [ ] https://github.com/getsentry/sentry/issues/46054
- [ ] https://github.com/getsentry/sentry-javascript/pull/7589
- [ ] https://github.com/getsentry/team-replay/issues/52
```

```[tasklist]
## EA
- [ ] https://github.com/getsentry/sentry/issues/46603
- [ ] https://github.com/getsentry/sentry/issues/46637
- [ ] https://github.com/getsentry/sentry-javascript/issues/7531
- [ ] https://github.com/getsentry/relay/issues/2007
- [ ] https://github.com/getsentry/sentry-javascript/issues/7495
- [ ] https://github.com/getsentry/sentry/issues/47425
- [ ] https://github.com/getsentry/sentry-javascript/issues/7830
```

```[tasklist]
## GA
- [ ] https://github.com/getsentry/sentry/issues/47556
- [ ] https://github.com/getsentry/sentry/issues/47548
- [ ] https://github.com/getsentry/sentry/issues/47833
- [ ] https://github.com/getsentry/team-replay/issues/55
- [ ] https://github.com/getsentry/team-replay/issues/72
- [x] Move network body capture configuration to public API
- [ ] https://github.com/getsentry/sentry-javascript/issues/7103 (Close with link to docs and let everyone know it's ready)
- [ ] https://github.com/getsentry/sentry/issues/47835
```

**Comment by bruno-garcia** [comment]
We considered adding req/resp to breadcrumbs in this PR: 
* https://github.com/getsentry/sentry-javascript/pull/7287

Finally decided against it for a few reasons: We keep around by default 100 crumbs. This means changes are high that we'll go over the event size limit and the event will be dropped instead. Also that would require work on the event detail and transaction breadcrumb component to render these properly. Truncation was considered to keep the size within certain limits but as we did that with `event.request` in the past it often results in a broken JSON and has diminishing value.

**Comment by bruno-garcia** [comment]
PII stripping on Relay getting worked here:
* https://github.com/getsentry/relay/pull/2034

**Comment by bruno-garcia** [comment]
Enabled the feature to all EA customers. Let folks know in: https://github.com/getsentry/sentry-javascript/issues/7103#issuecomment-1527964052
