### ISSUE TITLE
[Epic] Replay: Search by DOM elements that were clicked

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#45524]
# Summary

This is a meta-issue to track the work to deliver **search on DOM elements that were clicked** for Session Replay to narrow down replay results. For example, searching for replays when a specific button has been clicked by an end-user. The goal is for users to have **faster time-to-value** when finding replays that are most relevant or important to them.

```[tasklist]
### Internal Release 
- [x] [Jasmin] Reach out to customers who have requested this feature
- [ ] https://github.com/getsentry/replay-backend/issues/263
- [ ] https://github.com/getsentry/sentry-javascript/issues/7394
- [ ] https://github.com/getsentry/snuba/pull/3845
- [ ] https://github.com/getsentry/sentry/pull/45663
- [ ] https://github.com/getsentry/snuba/pull/3855
- [ ] https://github.com/getsentry/sentry/pull/46249
- [ ] Hints for new search field names in the Replay Index page
- [ ] https://github.com/getsentry/sentry/issues/45898
```

```[tasklist]
### EA Release
- [x] Roll this feature out to Early Adopters (Rollout schedule is 20%, 40%, 70%, 100%)
- [ ] https://github.com/getsentry/sentry/pull/45763
- [ ] https://github.com/getsentry/sentry/issues/45741
- [ ] https://github.com/getsentry/sentry-docs/issues/6464
- [ ] https://github.com/getsentry/sentry/issues/46601
- [ ] https://github.com/getsentry/team-replay/issues/53
```

```[tasklist]
### GA Release
- [x] Roll this feature out to General Availability (Rollout schedule is 20%, 40%, 70%, 100%)
- [x] Decide if `data-testid` is going to be deployed (needs docs) or deleted (stop ingesting and indexing the dat)
- [ ] https://github.com/getsentry/sentry/issues/46602
- [ ] https://github.com/getsentry/sentry/issues/47181
- [x] Ready to merge: https://github.com/getsentry/sentry-docs/pull/6465
```

### Important Links 
**_Sentry employees only_**

- [Product Requirements Document](https://www.notion.so/sentry/47adebb97bc44ab19be2a786d4541576)
- [Project Kickoff Document](https://www.notion.so/sentry/d61b158c456c4ea8a053350081060d53)
- [Backend design discussion](https://www.notion.so/sentry/Replay-DOM-Search-ca1eea3e377845bfbec123cda0a068a9) TODO: Move to GitHub
- [SnS Specification](https://www.notion.so/sentry/Snuba-DOM-Search-Spec-5b6946f31bde42d7988458d9987cf163)

**Comment by adamrehill** [comment]
Just chiming in here as I think this was created from a question I asked support about (whether this feature would be in the roadmap in the future). Having used fullstory previously, it would be great to have some of the other interaction searches that they have like:  "Clicked Text/Element Is...", "Changed text...", etc. and to be able to create segments of replays that fall within that. For example, our product team may want to group users that struggled with a particular new feature.

**Comment by bruno-garcia** [comment]
DOM search is live! Blog post announcing will come out soon.

**Comment by bruno-garcia** [comment]
🥳 

https://blog.sentry.io/2023/04/26/introducing-search-by-user-click-for-session-replay-zero-in-on-interesting/
