### ISSUE TITLE
[Epic] Replay: Surface interesting replays on index page

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#45701]
Today the Replay Index page is a list of replays in chronological order, and can do more to guide the user to replays that they should be looking into. 

The approach that we've discussed taking is adding cards to the top of the index page. These will show a couple replays based on some search query (search against either the replay dataset, or the events dataset, etc).

Queries to start with are:
- Replays containing an issue where the issue affects many people
- Replays containing an issue where the issue is most recent

Other query ideas: 
- TBD

## Version 1
The goal of this release is to get something visible on the page and see how it feels.
With that accomplished we will be able to test: 

1. Page Performance -> can we load the previews quick enough?
2. Card/query relevance -> Should we use different/more queries?
3. Does this format work, is it interesting to see replays like this?

```[tasklist]
- [ ] https://github.com/getsentry/sentry/issues/36228
- [ ] https://github.com/getsentry/sentry/issues/39620
- [ ] Implement the Figma designs from #39620 -> https://www.figma.com/file/9KcBRp3IniYCtCuAwuu3e2/Specs%3A-Index-Widget?node-id=68%3A4140&t=npzMT8cw6IyPr1vT-0
```

**Comment by bruno-garcia** [comment]
Some designs from #39620
![image](https://user-images.githubusercontent.com/1633368/224762543-82dcef34-c626-4e22-881a-3ebc856dd43e.png)

**Comment by bruno-garcia** [comment]
We're putting a pause on this for the time being.

**Comment by bruno-garcia** [comment]
We released improvements to the index page in the form of widgets for Dead and Rage clicks.
![image](https://github.com/getsentry/sentry/assets/1633368/b72fc90a-f858-4cbd-92fc-82abf2f38b70)

More improvements planned on a separate Epic: https://github.com/getsentry/team-replay/issues/138
