### ISSUE TITLE
Crons: Allow edit of a monitor's slug

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#46071]
Now that Crons allows defining a slug for a monitor (ref https://github.com/getsentry/sentry/issues/45166) we need to consolidate the UX for both the "name" and "slug" fields during monitor creation and editing.

The expected UX should be as follows:
* During monitor creation:
    * Only the "Name" field is shown. The name field accepts Unicode characters.
    * In the background, we automatically slugify the name and set it as the monitor slug.
    * ~~In case a generated slug conflicts with an existing monitor with the same slug, a validation message is shown.~~
      - We can just suffix it with a unique identifier
* During monitor edit:
    * Name field is shown and editable.
    * Slug field is shown and editable. Notice that updating the slug might break existing jobs shown as well.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/46099
- [ ] https://github.com/getsentry/sentry/pull/46479
- [ ] https://github.com/getsentry/sentry/issues/46152
```
