### ISSUE TITLE
POC: Display the CPU & memory metrics provided by Android SDK on Transaction Details

### ISSUE THREAD

**Issue by narsaynorath** [getsentry/sentry#46532]
### Planning
- [x] ~~GitHub discussion?~~
- [x] Product requirements
- [x] Proposed design: https://www.figma.com/file/rKAQXGurSfpCUMCgya3OR5/mdx---cpu%2Fmemory-in-waterfall?node-id=1%3A11272&t=jAslelwOJBMvkEJu-1
- [x] ~~[Standard project plan template](https://www.notion.so/sentry/GitHub-Epic-Issue-Template-72b517d97e4c46168b2670545d70b8dd) added to issue~~ -- Probably just need a mini-description of the project here, not a full-blown "Standard project"
- [x] Implementation proposal drafted
- [x] Dependent teams consulted
- [x] ~~Milestones~~ Tasks defined -- Probably just 1 milestone here
- [x] ~~Release schedule drafted in Notion~~
- [x] Epic reviewed by PM & EM

### Description

Android SDK is storing CPU and memory metrics on profiles and when there's a transaction with a profile we want to display those metrics in a chart on the event details page.

### Product Requirements
CPU and memory are restrictive and important to consider when diagnosing performance issues, more-so than web. We want to display CPU and memory with transactions so users can correlate spikes to ongoing operations.

### Implementation Proposal
Profiles are currently loaded onto the event details page if it's a transaction and the transaction has a profile. The data is in the form of:

```js
measurements: {
  cpu: {
    unit: "percent",
    values: [{
      elapsed_since_start_ns: number,
      value: float
    }, ...]
  },
  memory: {...}
}
```
This is timeseries data that can be plotted with various charts, with line charts being the most intuitive initially. The `elapsed_since_start_ns` may have to be converted into timestamps given the start time of the profile.

```[tasklist]
### Tasks defined
- [ ] https://github.com/getsentry/sentry/issues/46534
- [ ] https://github.com/getsentry/sentry/issues/46685
- [ ] https://github.com/getsentry/sentry/issues/46686
- [ ] https://github.com/getsentry/sentry/issues/46689
- [ ] https://github.com/getsentry/sentry/issues/46687
- [ ] https://github.com/getsentry/sentry/issues/46535
```

**Comment by brentc** [comment]
Given this is a POC, I assume there isn't a full release schedule. That can be removed.
