### ISSUE TITLE
Inbound Filter for HealthChecks

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#46731]
As a user, I want to be able to filter out health check transactions using inbound filters, so they don’t count towards my quota.

**Acceptance Criteria:**
- a new inbound filter is added to filter our health check transactions (same way to identify as for DS)
- the control is just a toggle (ON/OFF)
- By default, the filter is OFF
- the new filter is ~~only available for customers on Business plans and is disabled for others.~~ available for all plans
- this will be under Filters (not Custom Filters)

![Image](https://user-images.githubusercontent.com/9060071/229368307-b8068249-ba49-4c60-8819-01b928f87f19.png)

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/49080
- [ ] https://github.com/getsentry/sentry/issues/49081
- [ ] https://github.com/getsentry/sentry/issues/49082
- [ ] https://github.com/getsentry/relay/pull/2118
- [ ] https://github.com/getsentry/sentry/issues/49089
- [ ] https://github.com/getsentry/sentry/issues/51243
```

**Comment by ale-cota** [comment]
After more recent discussion, we've decided to make this filter also available for customers on Team, not just Business.

**Comment by ale-cota** [comment]
@thinkocapo was asking if we can include `ping` also to the health check regex list https://github.com/getsentry/relay/issues/2227

@iambriccardo, @matejminar any concerns about that?

**Comment by matejminar** [comment]
> any concerns about that?

nope, added a subtask 👍

> we've decided to make this filter also available for customers on Team, not just Business.

also Developer, so essentially no plan gate, right?

**Comment by ale-cota** [comment]
Yes, no plan gate, like all the other non-custom filters.
