### ISSUE TITLE
[INC-336] Follow-up

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#46786]
```[tasklist]
### Tasks
- [ ] #47066
- [ ] https://github.com/getsentry/sentry/issues/47067
- [ ] https://github.com/getsentry/sentry/issues/47071
- [ ] https://github.com/getsentry/sentry/issues/47069
- [ ] https://github.com/getsentry/sentry/issues/47070
- [ ] https://github.com/getsentry/sentry/issues/47072
- [ ] https://github.com/getsentry/sentry/issues/47073
```
