### ISSUE TITLE
[Epic] Issues: Improve issue details page loading performance and UX

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#47527]
The issue details page is often cited as slow by users and has multiple opportunities for improvement in terms of performance. This ticket will track efforts in a few areas:

1. Decreasing the time it takes to go from a page render to seeing a successfully loaded event (we track this internally with the measurement `init_to_vcd`)
2. Caching endpoint responses so recently loaded data does not need to be refetched
3. Decreasing the cumulative layout shift web vital (CLS)

```[tasklist]
### Optimize loading path
- [ ] https://github.com/getsentry/sentry/issues/47520
- [ ] https://github.com/getsentry/sentry/issues/47521
- [ ] https://github.com/getsentry/sentry/issues/48499
- [ ] https://github.com/getsentry/sentry/issues/48783
- [ ] https://github.com/getsentry/sentry/issues/49018
- [ ] https://github.com/getsentry/sentry/issues/49281
```

```[tasklist]
### Cache endpoint responses
- [ ] https://github.com/getsentry/sentry/issues/47507
- [ ] https://github.com/getsentry/sentry/issues/47518
- [ ] https://github.com/getsentry/sentry/issues/47519
- [ ] https://github.com/getsentry/sentry/issues/48462
- [ ] https://github.com/getsentry/sentry/issues/49226
- [ ] https://github.com/getsentry/sentry/issues/49236
- [ ] https://github.com/getsentry/sentry/issues/49723
```

```[tasklist]
### General cleanup items
- [ ] https://github.com/getsentry/sentry/issues/48274
- [ ] https://github.com/getsentry/sentry/issues/49719
```
