### ISSUE TITLE
Crons: Improved Monitor Details Page

### ISSUE THREAD

**Issue by davidenwang** [getsentry/sentry#47579]
![Image](https://user-images.githubusercontent.com/9372512/232894598-440349cb-f4df-49cc-9bb5-03b65fbd0c37.png)

```[tasklist]
### Tasks
- [x] https://github.com/getsentry/sentry/issues/47917
- [ ] https://github.com/getsentry/sentry/issues/47956
- [x] [BE] Allow aggregation of stats along multiple environments
- [ ] https://github.com/getsentry/sentry/issues/48541
- [ ] https://github.com/getsentry/sentry/issues/47919
- [ ] https://github.com/getsentry/sentry/issues/48582
- [ ] https://github.com/getsentry/sentry/issues/49118
- [x] [FE] Modify check-ins graph to support multiple environments
- [ ] https://github.com/getsentry/sentry/issues/48592
- [ ] https://github.com/getsentry/sentry/issues/46901
```
