### ISSUE TITLE
Old Alerts with indexed metrics warning

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#47812]
We need to communicate to the user on the alerts index page that some of their existing alerts are not fully supported anymore and are based purely on indexed data.

Acceptance Criteria:
- ~~write a logic that will remove unsupported alerts after some date~~ 
- notify via email
- notify in UI
- we need a way to see the full list of unsupported alerts
- see if we can notify people via slack
- article in the docs/support to guide people through this transition

Design: Design: https://www.figma.com/file/Uwjb5TR5edgu95CbR0Ciou/Specs%3A-AM2-Performance-Alerts?node-id=16-3173&t=7mKP4pg091U6vVU7-0

```[tasklist]
### Tasks
- [x] [UI] - Create a figma design
- [ ] [Email] - Write a copy
- [ ] https://github.com/getsentry/sentry/issues/49316
- [ ] https://github.com/getsentry/sentry/issues/49317
- [ ] https://github.com/getsentry/sentry/issues/49318
```

**Comment by ale-cota** [comment]
As per this [slack discussion](https://sentry.slack.com/archives/C03B7A8GGLA/p1683102640809599?thread_ts=1682670219.479849&cid=C03B7A8GGLA), we should remove the "write a logic that will remove unsupported alerts after some date" acceptance criteria. As a user, I would rather want to make a conscious decision of removing the alert instead of things just disappearing (I might have not seen the email or slack notification). We are also giving users the option to bulk delete deprecated alerts, so that is sufficient.
