### ISSUE TITLE
Crons: Ability to delete/hide a monitor environment

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#47839]
With the latest support for environments, enabling the deletion or hiding of a monitor environment is important. 

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/47847
- [ ] https://github.com/getsentry/sentry/pull/47914
- [x] https://github.com/getsentry/sentry/issues/49268
```

**Comment by rjo100** [comment]
https://github.com/getsentry/sentry/pull/47847 <- Backend work
https://github.com/getsentry/sentry/pull/47914 <- Docs
