### ISSUE TITLE
Dashboard Widget Creation Improvements

### ISSUE THREAD

**Issue by brentc** [getsentry/sentry#47836]
A collection of improvements for reducing friction when creating new widgets

### To Do
* [x] Review each task in "To Fix", confirm resolution, estimate complexity, and schedule into milestone task lists below

```[tasklist]
### To Fix
- [ ] #44804
- [ ] #34420
- [ ] #44783
- [ ] #44792
- [ ] https://github.com/getsentry/sentry/issues/49616
- [ ] https://github.com/getsentry/sentry/issues/49869
```

```[tasklist]
## Milestone 1
- [ ] 
```

**Comment by om-ray** [comment]
@brentc Could I start working on this?

**Comment by brentc** [comment]
@om-ray Great! Some of these are in less of a "obvious clear solution" state than others. Let me do a quick review and see which ones would be least controversial for contributing!

**Comment by brentc** [comment]
@om-ray of the items on the list I would suggest diving into #44783 or #44792 before anything else in order get familiar with the code base and workflows. If this is your first time working with the sentry codebase you'll want to read through our "[Sentry Developer Documentation](https://develop.sentry.dev)"

**Comment by om-ray** [comment]
@brentc Thanks for the recommendations! I'll get started on those! And yes, I have read the dev docs, thanks for the reminder though.

**Comment by Abdkhan14** [comment]
Thank you for your contributions @om-ray!
