### ISSUE TITLE
[EPIC] Replay Bias

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#48137]
**Problem**: Because of transaction sampling, we are “losing” the tie between traces and replays. This correlation is a valued feature for customers in their investigation process

![Image](https://user-images.githubusercontent.com/26696515/236416143-faf02349-d2af-4dd9-91ed-9df24612bcd9.png)

**Proposed Solution**: The initial proposal was to sample all traces with Replay IDs. Initial testing on the Sentry org revealed this to lead to major oversampling also due to a bug in the SDK implementation, so alternative solutions are being explored.

**Expected Outcome**: Ensure the availability of full traces for replays whenever a correlation is possible*.

**Notion Doc**: https://www.notion.so/Replay-Bias-ae1194e2c37447c2824e9ff79a681644

*Note: Missing or incomplete traces can be caused by a [series of other factors](https://docs.sentry.io/product/sentry-basics/tracing/trace-view/#troubleshooting) including client-side sampling, rate limits and running out of quota. We are focusing on resolving exclusively the problems created by server-side sampling.

```[tasklist]
### Version 1
- [ ] https://github.com/getsentry/sentry/issues/47769
- [ ] https://github.com/getsentry/sentry-javascript/issues/8013
- [x] GA
```

```[tasklist]
### Version 2
- [ ] https://github.com/getsentry/sentry/issues/48936
```

**Comment by danielkhan** [comment]
I think we should add some heuristics for client-side sampling scenarios as well. Let's reopen this.
