### ISSUE TITLE
[EPIC] Expand the Supported Metrics

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#48139]
**Problem**: The metrics layer only supports a limited set of fields and needs to be expanded in order to support a larger range of use cases.

**Proposed Solution**: 
Extend automatically extracted metrics with [most frequent, low-cardinality metrics ](https://www.notion.so/sentry/Expand-Metrics-for-Alerts-cdfa32d7624e498b8246c3f131f753f1?pvs=4#17480955e2fb4407b619b9236bc2723a)

**Expected Outcome**: The new metrics are available in Alerts, Dashboards and Performance.

**Notion Doc**: https://www.notion.so/sentry/Expand-the-supported-metrics-6e6624c0fa304c3f817c0261e96f7313

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/team-ingest/issues/123
- [ ] https://github.com/getsentry/sentry/issues/48995
- [ ] https://github.com/getsentry/sentry/issues/49077
- [ ] https://github.com/getsentry/sentry/issues/49078
- [ ] https://github.com/getsentry/sentry/issues/49079
- [ ] https://github.com/getsentry/sentry/issues/50228
- [ ] https://github.com/getsentry/relay/issues/2225
```
