### ISSUE TITLE
[EPIC] Setup Docs Refactor

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#48144]
**Problem**:

The current experience to add, fetch and render our onboarding docs is very painful because:

1. It is not easy to see your changes in your local dev environment
2. To see your changes in production, sentry-docs has to be released
3. We have hacky CSS to make everything look like Sentry style
4. If you need to create a document in a format that does not match the defined pattern, the build won’t pass, forcing you to manually update functions in sentry-docs as well as the sentry repository. 
These updates are usually conditional on a case-by-case basis and the list can grow very large and this is not scalable.
6. To provide a dynamic code snippet experience it is necessary to replicate the same document in the docs. See https://github.com/getsentry/sentry-docs/pull/6633
   
**Proposed solution:**

At our last 2x Frontend TSC meetings we discussed the RFC “[Move Docs to Sentry Repository](https://github.com/getsentry/rfcs/blob/main/text/0084-move-docs-to-sentry-repository.md)”, coming to the conclusion that we would just like to move the quick start docs to our [sentry](https://github.com/getsentry/sentry) repository, where we will either continue to use MDX files or just use our own React components

**Expected outcome:**

- Transition the onboarding documentation (quick-start) from the [sentry-docs ](https://github.com/getsentry/sentry-docs/tree/master/src/wizard)repository to the main sentry repository, starting with JavaScript platforms.
- Implement a simple and user-friendly structure that is easy for non-developers to work with (create/update) and understand.
- Ensure that the documentation is properly rendered in all onboarding entry points, including in the onboarding for new organizations, and create project UI.
- Create a guide for creating and updating onboarding documents in the sentry repository. 

**Useful Link:**
https://github.com/getsentry/rfcs/blob/main/text/0084-move-docs-to-sentry-repository.md

**Notion Doc**: https://www.notion.so/sentry/Setup-docs-refactor-01ed795a111d43569e3ccebe9def4989

```[tasklist]
### PoC
- [ ] https://github.com/getsentry/sentry/issues/47470
- [ ] https://github.com/getsentry/sentry/issues/49934
```

```[tasklist]
### Gradually migrate "Getting Started" documentation from sentry-docs to sentry's main repository
- [ ] https://github.com/getsentry/sentry/issues/52121
- [ ] https://github.com/getsentry/sentry/issues/52133
- [ ] https://github.com/getsentry/sentry/issues/52137
- [ ] https://github.com/getsentry/sentry/issues/52138
- [ ] https://github.com/getsentry/sentry/issues/52139
- [ ] https://github.com/getsentry/sentry/issues/52140
- [ ] https://github.com/getsentry/sentry/issues/52141
- [ ] https://github.com/getsentry/sentry/issues/52142
- [ ] https://github.com/getsentry/sentry/issues/52155
- [ ] https://github.com/getsentry/sentry/issues/52156
- [ ] https://github.com/getsentry/sentry/issues/52157
- [ ] https://github.com/getsentry/sentry/issues/52154
- [ ] https://github.com/getsentry/sentry/issues/52122
- [ ] https://github.com/getsentry/sentry/issues/52153
- [ ] https://github.com/getsentry/sentry/issues/52152
- [ ] https://github.com/getsentry/sentry/issues/52151
- [ ] https://github.com/getsentry/sentry/issues/52150
- [ ] https://github.com/getsentry/sentry/issues/52149
- [ ] https://github.com/getsentry/sentry/issues/52148
- [ ] https://github.com/getsentry/sentry/issues/52147
- [ ] https://github.com/getsentry/sentry/issues/52146
- [ ] https://github.com/getsentry/sentry/issues/52145
- [ ] https://github.com/getsentry/sentry/issues/52143
- [ ] https://github.com/getsentry/sentry/issues/52144
```
