### ISSUE TITLE
[EPIC] DnD UI Fixes for Metrics

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#48143]
**Problem**: Discover works purely based on stored event data, whereas Dashboards can be a mix of both event and metrics data. The two are inextricably linked and this creates confusion for customers.

**Proposed Solution**: Give customers more visibility
- in Discover about the fact that what they're looking at is sampled event data
- in Dashboards regarding which data is based on sampled events and which is based on total event metrics (in the widget builder and when looking at a dashboard)

**Notion Doc**: https://www.notion.so/sentry/DnD-UI-fixes-for-metrics-b37a7bee22f24dfa85ba889a91c9614f

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/48622
- [ ] https://github.com/getsentry/sentry/issues/47005
- [ ] https://github.com/getsentry/sentry/issues/47005
- [ ] https://github.com/getsentry/sentry/issues/47147
- [ ] https://github.com/getsentry/sentry/issues/47811
- [ ] https://github.com/getsentry/sentry/issues/47006
- [ ] https://github.com/getsentry/sentry/issues/48633
```

**Comment by matejminar** [comment]
We'll be investing in on-demand metrics extraction, which will make this initiative obsolete.
