### ISSUE TITLE
[EPIC] Fidelity Rate Based on Usage

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#48140]
**Problem**: 
- If a customer buys more transactions than they consume, they’re penalised by lower fidelity. 
- For unlimited trials, there is a sawtooth-like effective sampling rate, which seems to make trends in Discover confusing.

**Proposed Solution**: Switch to a sliding window calculation based on actual usage.

**Expected Outcome**: Even distribution of indexed Transactions.

**Notion Doc**: https://www.notion.so/sentry/Fidelity-rate-based-on-usage-424154659f9e4d8ca396d43c25d22b57

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/48131
- [ ] https://github.com/getsentry/sentry/issues/48613
- [x] Finalize DACI to decide per-project vs per-org
- [x] How does recalibration work? - It needs to be disabled.
- [x] Handle the case of pre-am2 orgs and organization below the reserved volume that's needed for DS
- [x] Internal Release
- [ ] https://github.com/getsentry/sentry/issues/49534
- [ ] https://github.com/getsentry/sentry/issues/48998
- [ ] https://github.com/getsentry/sentry/issues/49309
- [x] Update internal and external docs
- [ ] https://github.com/getsentry/sentry/issues/50713
```
