### ISSUE TITLE
[Epic] Replay Canvas Support

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#48429]
Currently, Session Replay renders a white box when a canvas is found:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/1633368/235954924-1a9bbd36-09fc-4a85-9597-8477c40d1a8d.png">

The goal is to add an opt-in feature, to record canvas. Either by recording draw commands or screenshots.
PII stripping on images might be helpful, but not a requirement given this will be opt-in and users will be advised to avoid turning this on if their canvas usage includes PII.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/team-replay/issues/305
- [ ] https://github.com/getsentry/team-replay/issues/324
- [ ] https://github.com/getsentry/team-replay/issues/334
- [ ] https://github.com/getsentry/team-replay/issues/336
- [ ] https://github.com/getsentry/team-replay/issues/339
```

<details>
  <summary>Sentry dogfooding opportunities</summary>
At Sentry, we use canvas in our Profiling flamechart. Both 2d canvas (upper timeline) and webgl (bottom one):

![image](https://user-images.githubusercontent.com/1633368/236336623-ffbd1ec1-9eda-416a-9a1f-90e4e50c5f81.png)

The Replay without canvas support showing Profiling:
![image](https://user-images.githubusercontent.com/1633368/236344652-50c3befc-8a53-4e06-9885-f95983a353ee.png)
</details>

ref https://github.com/getsentry/sentry-javascript/issues/6519

**Comment by jas-kas** [comment]
@billyvg @c298lee From our SDK backlog discussion - https://github.com/getsentry/sentry/issues/48429

**Comment by bruno-garcia** [comment]
Canvas is available already, we're tracking GA'ing it through:
* https://github.com/getsentry/team-replay/issues/339
