### ISSUE TITLE
Cocoa Checklist

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#4846]
* [x] swift-objc registers and crash compatibility
* [ ] merge multiprocessing
* [ ] reprocessing basics
* [x] new relic swizzling test
* [ ] react native basic support for release (+ docs)
* [ ] blog post symbolication
* [ ] blog post bitcode
* [ ] bad dsym (#4807) handling
* [ ] check open issues for papercuts (#3608)
* [ ] reminders for system symbol releases

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
