### ISSUE TITLE
Crons: Enhanced Crons Issues

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#48558]
```[tasklist]
### Tasks
- [ ] Add a link to the issue details back to monitor details
- [x] Move Crons errors to the issues platform
- [x] Update issues titles, culprit, and subtitle to be more human friendly
- [x] Assure grouping of Crons issues don't break when updating the issue title
- [x] Dropdown filter in the issues screen show have a Crons option
- [x] Add Crons related filters to issues search
- [ ] Update "Related Issues" endpoint for the monitor details to return traced issues
```
