### ISSUE TITLE
Crons: Tracing for Errors and Transactions

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#48559]
Get related issues to show up here:

![Image](https://github.com/getsentry/sentry/assets/7078270/17bd586a-d280-40c4-a853-d9613104523d)

```[tasklist]
### Tasks
- [x] Send `trace_id` from PHP/Python SDKs with a failed check-in
- [ ] https://github.com/getsentry/sentry/issues/51383
- [ ] https://github.com/getsentry/sentry/issues/51384
- [ ] https://github.com/getsentry/sentry/issues/51385
- [ ] https://github.com/getsentry/sentry/issues/51386
- [ ] https://github.com/getsentry/sentry/issues/51387
- [ ] https://github.com/getsentry/sentry/issues/52689
- [ ] Have issues backlink to Monitors via `trace_id`
- [ ] Update docs
```
