### ISSUE TITLE
Cronjob default missed timeout makes no sense

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#49011]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

![image](https://github.com/getsentry/sentry/assets/51749023/f4a4d72b-6a05-4053-803a-bc15ef620ce5)\
^ This is what it currently says, which makes little sense. If the timeout were indeed 0 minutes, any check-in that doesn't happen precisely when it's expected to occur, would be too late. If this is one minute by default, then the input placeholder should say so 🙂 

---

**Edits from @evanpurkhiser**: See https://github.com/getsentry/sentry/issues/49011#issuecomment-1681324305

**Comment by evanpurkhiser** [comment]
Hey @jeengbe thanks for opening this. We were JUST talking about it as we were fixing https://github.com/getsentry/sentry/pull/48826.

Because of how the monitor checks happen, you have to send them within the minute, so yeah I think a one minute "default" would be right.

@davidenwang @rjo100 I think what we could do to account for this is subtract one from the configured margin to get `0` when the default is `1`. Then we can validate a minimum of 1. This should better communicate that the best resolution we have is 1 minute.

**Comment by jeengbe** [comment]
Hi @evanpurkhiser, thanks for the reply and link to the PR!

I added a comment on there with what seems like the best approach to me and how I (from the point of a user) assumed it works.

**Comment by evanpurkhiser** [comment]
Finally coming back around to this with a round of edge case timing cleanups :-)

### The problem

The issue here is that while we say the "default" is zero, it is not actually zero, indeed we give you a 1 minute grace period to complete your check-in. That logic is controlled here

https://github.com/getsentry/sentry/blob/774df5931d33dde241b742a34710b7ce16337179/src/sentry/monitors/tasks.py#L182-L194

This logic only exists because when you leave the missed status number blank, it defaults to computing `next_expected` and `next_expected_latest` to be the SAME. You can see that here

https://github.com/getsentry/sentry/blob/774df5931d33dde241b742a34710b7ce16337179/src/sentry/monitors/models.py#L295-L301

So for example, if your check-in is expected at `12:00` and we run the task to find monitors that did not check-in on time, we will use `next_checkin_latest` which is equal to `12:00`. This is why we use `_lt` (less than), so this task waits until `12:01` to mark checkins that were supposed to happen at `12:00` as missed.

```
next_checkin = 12:00
next_checkin_latest = 12:00 

# Task is not run
task_run_time = 12:00
next_checkin_latest < task_run_time #false

# Task is run a minute later
task_run_time = 12:01
next_checkin_latest < task_run_time # true
```

Note that this is related to why https://github.com/getsentry/sentry/issues/54641 happens.

### The solution

`next_checkin_latest` needs to be the actual latest time you can check-in by.

Here's what I propose

1. The **minimum** you should be allowed to set your check-in missed time to should be `1 minute`. This should **also be the default** and should be reflected in the UI.
2. When computing the `next_checkin_latest` if the user did not configure a margin, **use 1 as the default** [[here](https://github.com/getsentry/sentry/blob/774df5931d33dde241b742a34710b7ce16337179/src/sentry/monitors/models.py#L295-L301)]
3. Update the logic which determines which monitors have missed checkins to use `lte` (less than or equal) [[here](https://github.com/getsentry/sentry/blob/774df5931d33dde241b742a34710b7ce16337179/src/sentry/monitors/tasks.py#L182-L194)]. The logic would now look like this

   ```
	next_checkin = 12:00
	next_checkin_latest = 12:01

    # Note that `next_checkin_latest` and `next_checkin` will never be 
    # equal in our data-model now.
	
	# Task is not run
	task_run_time = 12:00
	next_checkin_latest <= task_run_time #false
	
	# Task is run a minute later
	task_run_time = 12:01
	next_checkin_latest <= task_run_time # true
	```

### Implementation

This is a little bit tricky because we need to be careful not to update logic in such a way that everyone gets a single missed check-in when we switch from `lt` to `lte`.

1. [ ] Create a migration to update all monitor configurations that have an explicit `0` missed status to be empty (which will use the default of 1) (there's ~90 monitors right now)
2. [ ] Update the UI to be clear that the default is `1`
3. [ ] Enforce with the validator that the minimum value is `1`
4. [ ] Update query to use `_lte` for `next_expected_latest`. 

    This includes implementing temporary logic to avoid the condition where a user's monitor had an equal `next_expected` and `next_expected_latest` to avoid their monitor being immediately marked as missed because `_lte` would include the monitor the moment the checkin window starts. We can detect this and add `1` to the `next_expected_latest` to have the same behavior as what exists

    If we find that monitors exist with a `next_expected` far in the future and we do not want to leave the temporary logic around, we can also write a migration to handle this after the fact.

**Comment by evanpurkhiser** [comment]
This should now be fixed! Thanks again for this feedback @jeengbe
