### ISSUE TITLE
Crons: Improved Monitor List Page (v1): New Timeline Components

### ISSUE THREAD

**Issue by davidenwang** [getsentry/sentry#49117]
![Image](https://user-images.githubusercontent.com/9372512/238430467-bc7e556a-9580-4e23-9fef-7df797dfbdf3.png)

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/44642
- [x] FE: Create timeline component
- [x] BE: Create separate endpoint for timeline data
- [x] FE: Allow changing resolution of timeline data
- [x] FE: Incorporate timeline component into monitors listing page
```
