### ISSUE TITLE
Crons: Introduce `timeout_at` column on checkins

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry#49283]
Currently when we check for monitors that are in progress that will be potentially timing out, we are looking at **every single in progress monitor**.

There is currently a hard cap on the number of in progress monitors we'll look at in one run of the task (it's 10k). This means if we have more than 10k in progress checkins we will fail to mark some checkins as timed out when they should be.

This can cause a major backlog (which we have had happen, https://github.com/getsentry/sentry/issues/47674 will help avoid it).

A solution to this is to change this code

https://github.com/getsentry/sentry/blob/0eaa4410f82d9c2499638ac06719f1ed9d74cf20/src/sentry/monitors/tasks.py#L87-L100

So instead of checking if it's past it's max run time for each in progress checkin, we instead record in the created `in_progress` checkin the time that we would expect it to fail (`timeout_at`) at and index on `(status, timeout_at)`.

Now we can explicitly query on that field to find monitors that have timed out (the same way we do for monitors that were missed)

We should empty out the column to NULL when the checkin becomes anything other than `IN_PROGRESS`

### Proposed solution

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/50502
- [ ] https://github.com/getsentry/sentry/issues/50572
- [ ] https://github.com/getsentry/sentry/issues/50991
- [ ] https://github.com/getsentry/sentry/issues/51295
- [x] **Wait for all in progress monitors without timeout_at to move to completed state**
- [ ] https://github.com/getsentry/sentry/issues/52563
- [ ] https://github.com/getsentry/sentry/issues/53015
- [x] Improve metric graphs
```
