### ISSUE TITLE
Improve tracking metrics

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#49950]
**Problem:** We don't know today whether the new approach with debug IDs is more successful than the old approach with releases. We need to answer this question before we can push adoption.
The [tracking](https://app.datadoghq.com/dashboard/fwg-ptn-s2k/javascript-sourcemaps?from_ts=1685434110159&to_ts=1685435910159&live=true) we have so far aren't helping us to understand much. We need a better reading/understanding of how the stack trace was processed, as well as how big the opportunity space is (we'll never be able to symbolicate 100%, but we need to have a number to aspire to. There are some frames that aren't important to us (e.g. native frames) and some fetching that can be towards public CDNs, which we also don't care about.

**Potential solution:** Start tracking the following metrics:
- Track the number of frames that are symbolicated per event (this should go up)
  - How many times did we symbolicate more than 50% of frames
  - Can we segment out frames that are not important for us (e.g. native frames)?
  - How many times the top frame we send to symbolicator is symbolicated
- How the source map was fetched by frame: debugID, release, release old, scraped
  - This is part of the Sentry response, still some work needs to be done
  - Was the fetching done from a public CDN or a customer's website CDN (we might come up with a list of CDNs we don’t care about). If it turns out that 90% of those CDNs are public, we only need to optimise a little bit. If 90% are customer CDNs, we have a lot of work to do.

**Desired outcome**: % of total issues that are symbolicated.  

**Acceptance Criteria:**
- Update the existing or create a new dashboard where we can track these numbers
- Be able to answer the question "How large is the set of frames that cannot be resolved by debug IDs?"
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/51587
- [ ] https://github.com/getsentry/symbolicator/pull/1205
- [ ] https://github.com/getsentry/sentry/issues/51596
- [ ] Compute derived metrics like number & ratio of symbolicated frames
- [ ] Decide which scraping hosts to filter out
```

**Comment by smeubank** [comment]
hi @loewenheim 

is this something still on your radar?

**Comment by loewenheim** [comment]
Yes, we're still working on this.
