### ISSUE TITLE
Update assignment filter on issue stream to differentiate issues assigned to you between those assigned to your teams

### ISSUE THREAD

**Issue by brianthi** [getsentry/sentry#50037]
AC:
- `assigned:me`, `assigned:<email>`, `assigned_or_suggested:me`, `assigned_or_suggested:<email>` should only show issues that are assigned/suggested to that specific person.
- Implement a new search, `assigned:my_teams`, `assigned_or_suggested:my_teams` to show issues that are assigned/suggested to all teams that you belong to.
- In the search dropdown, suggest values in this order in the dropdown: `me`, `my_teams`, `none` and everything else following as it originally was
- For Review tab should update to `assigned_or_suggested:[me, my_teams, none]`
- Implement a migration to support folks who have created saved searches so that their search behavior remains intact.  `assigned:me` should now change to `assigned:[me, my_teams]`
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/50848
- [ ] https://github.com/getsentry/sentry/issues/50847
- [ ] https://github.com/getsentry/sentry/issues/50845
- [ ] https://github.com/getsentry/sentry/issues/50842
- [ ] https://github.com/getsentry/sentry/issues/50844
```

**Comment by robinrendle** [comment]
<img width="1132" alt="aaaaaagh" src="https://github.com/getsentry/sentry/assets/1900676/3689f055-e648-4dd5-951d-b0ad75ea8627">

**Comment by lobsterkatie** [comment]
Out of curiosity, is `is: assigned` a thing that works?

**Comment by barkbarkimashark** [comment]
> Out of curiosity, is `is: assigned` a thing that works?

Yeah, I think that one just checks whether the issue is assigned to anyone.
