### ISSUE TITLE
[Epic] Recommended Event

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#50365]
There are certain features that make it easier to debug an issue, such as replays or traces. We know that users viewing events with this additional information resolve more issues. Due to sampling rules, only a small subset of events within an issues will have this additional information available. Since the issues page shows the latest event by default, we are not giving users the best information up front. If an issue has an event that has better information that the most recent event, we should show that instead.

[Internal product spec](https://www.notion.so/sentry/Most-Useful-Event-4070fb8dc41e4b959c32eeac07e22719#0a0d453f34d84f6aad196192402ea6b6)
[Internal tech spec](https://www.notion.so/sentry/Tech-Spec-Most-Useful-Event-30d7e69d5b46429893bfd444921c231b)

```[tasklist]
### Snuba updates
- [ ] https://github.com/getsentry/sentry/issues/50363
- [ ] https://github.com/getsentry/sentry/issues/50381
```

```[tasklist]
### Event ranking updates
- [ ] https://github.com/getsentry/sentry/issues/50890
- [ ] https://github.com/getsentry/sentry/issues/51070
- [ ] https://github.com/getsentry/sentry/issues/51076
```

```[tasklist]
### Frontend updates
- [ ] https://github.com/getsentry/sentry/issues/51736
- [ ] https://github.com/getsentry/sentry/issues/51769
- [ ] https://github.com/getsentry/sentry/issues/51770
- [ ] https://github.com/getsentry/sentry/issues/52487
- [ ] https://github.com/getsentry/sentry/issues/52738
- [ ] https://github.com/getsentry/sentry/pull/53377
- [ ] https://github.com/getsentry/sentry/issues/53714
- [ ] https://github.com/getsentry/sentry/issues/53738
- [ ] https://github.com/getsentry/sentry/issues/53739
- [ ] https://github.com/getsentry/sentry/issues/53915
- [ ] https://github.com/getsentry/sentry/issues/54220
```

```[tasklist]
### Settings
- [ ] https://github.com/getsentry/sentry/issues/53913
- [ ] https://github.com/getsentry/sentry/issues/53914
```
