### ISSUE TITLE
[Epic] Reduce set of grouping configs in use by projects

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#50633]
Do this after the 2023-01 release goes out.

- [x] Determine what projects are not using the default group config ([internal redash query](https://redash.getsentry.net/dashboards/155-grouping-configs))
- [ ] Adjust [SQL query](https://redash.getsentry.net/queries/4281#table) [1]:
   - Exclude customers that have set `sentry:grouping_auto_update` as `False`
   - Only include projects that have 0 issues
- [ ] Determine why certain customers are still using old configs (blocked on above) (we only upgrade configs when events come in)
- [ ] Upgrade projects not using the latest group config (currently `"newstyle:2019-10-29"`) if they do not have `sentry:grouping_auto_update` set as `False`
   - [ ] File ops ticket to run SQL update query
- [ ] Mark group configs not in use as hidden
   - There's a bunch of folks with the mobile config and auto-updates set as disabled, thus, we may have them there forever
- [ ] Investigate removing epochs ([code](https://github.com/getsentry/sentry/blob/f1baad2b116034428bb7d91d671d94e4b3111188/src/sentry/projectoptions/defaults.py#L22-L26))
  - This keeps older projects defaulting to older grouping configs

We cannot remove unused grouping configs because prem and single tenant. This would require an upgrade path for them.

[1]
```
select
  proj.id as proj_id,
  proj.slug as proj_slug,
  opt.value as group_config
from
  sentry_projectoptions as opt
  left join sentry_project as proj on proj.id = opt.project_id
where
  opt.key = 'sentry:grouping_config' and opt.value not in ('"newstyle:2019-10-29"', '"newstyle:2023-01-11"')
limit
  100;
```

[2]
![Image](https://github.com/getsentry/sentry/assets/44410/9a736a17-4521-4b9a-b3b9-96ee5b2b530a)
