### ISSUE TITLE
[Epic] Native stack trace improvements

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#50690]
There are a number of improvements we can make to the stacktrace components, focusing mostly on feedback related to native traces.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/50691
- [ ] https://github.com/getsentry/sentry/issues/50693
- [ ] https://github.com/getsentry/sentry/issues/50694
- [ ] https://github.com/getsentry/sentry/issues/50695
- [ ] https://github.com/getsentry/sentry/issues/50696
- [ ] https://github.com/getsentry/sentry/issues/50697
- [ ] https://github.com/getsentry/sentry/issues/50698
- [ ] https://github.com/getsentry/sentry/issues/52591
- [ ] https://github.com/getsentry/sentry/issues/52592
- [ ] https://github.com/getsentry/sentry/issues/53300
- [ ] https://github.com/getsentry/sentry/issues/53341
- [ ] https://github.com/getsentry/sentry/issues/53886
```
