### ISSUE TITLE
Set up Discord credentials

### ISSUE THREAD

**Issue by spalmurray** [getsentry/sentry#50887]
Will need to figure out how we usually handle this and talk to ops about making sure the correct secret can be used in production. Make sure we can manually set a value for this if developing locally.

```[tasklist]
### Tasks
- [ ] Create options in sentry
- [ ] Set options in getsentry
- [ ] Open ops ticket to have secret set for prod
```
