### ISSUE TITLE
Crons: Improvements to Timeline Components

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#51071]
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/48586
- [x] Crons: Bucketing Consecutive Check-ins (Front-end)
- [ ] https://github.com/getsentry/sentry/issues/52985
- [x] Crons: Add hover effect to timeline component
- [x] Crons: Add status indicator back to the environments
- [x] Crons: Add loading state to timeline component
- [x] Crons: Add timeline component to the details page
- [ ] Crons: Add variable width to allow for better time bucket intervals
- [x] Crons: Add click to zoom to timeline component
- [x] Crons: Add navigate arrows to timeline component
- [ ] Crons: Figure out how to navigate quickly to specific days
- [ ] Crons: Accessibility review for timeline component
- [ ] Crons: Review how to paginate in a way that I can see multiple monitors at once in timeline view
```
