### ISSUE TITLE
Metrics explorer - UI improvements

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#51230]
```[tasklist]
### Tasks
-  [x] Bug fix: 14D request fails because off too high granularity
-  [x] Add more chart colors to support use cases with 5+ series or limit the number of visible series
-  [x] Sort series by totals
-  [x] Add error handling
-  [x] Reformat the table view (interval, date format)
-  [x] Assign generic label to the first series that has no group by 
-  [x] Add stacked bar chart display type
```
