### ISSUE TITLE
Emit alert metrics into project config computation

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry#51445]
Metrics extraction requires to send a description of metrics from Sentry to Relay via project configs. The relevant specs for this are:
- [Project config format](https://www.notion.so/sentry/Metrics-Extraction-Project-Configs-87d8f1e9dc4a422196904ecafc53caf5)
- [Metrics and tagging](https://www.notion.so/sentry/Metrics-Extraction-Metrics-and-Tagging-b602506dc02e4bad8fe0f7ece3c37727)

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/51788
- [ ] https://github.com/getsentry/sentry/pull/51863
- [ ] https://github.com/getsentry/relay/pull/2266
```

**Comment by jan-auer** [comment]
This had to be reverted since it contained two bugs. Re-submitting a fixed PR with more tests, including a relay config validation roundtrip.
