### ISSUE TITLE
Relay Product Improvements

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#51600]
```[tasklist]
### Tasks
- [ ] We'll need a similar warning/report if one is still ingesting through sentry.io instead of org subdomain
- [ ] https://github.com/getsentry/sentry/issues/46757
- [ ] https://github.com/getsentry/sentry/issues/46753
- [ ] https://github.com/getsentry/sentry/issues/46752
- [ ] https://github.com/getsentry/sentry/issues/46754
- [ ] https://github.com/getsentry/sentry/issues/46756
- [ ] https://github.com/getsentry/sentry/issues/46760
- [ ] https://github.com/getsentry/sentry/issues/46755
- [ ] https://github.com/getsentry/sentry/issues/46761
```
