### ISSUE TITLE
Sunset the App Store Connect Integration

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry#51994]
### Problem Statement

Since Xcode 14, you can't download dSYMs anymore from AppStore Connect. See

> Debug symbols can only be downloaded from App Store Connect / TestFlight for existing bitcode submissions and are no longer available for submissions made with Xcode 14. (86118779) - https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes#Deprecations

We don't know why our integration worked for a couple of Xcode 14 versions. 

Anyways, since around June 28th, 2023, users reported problems ([Twitter](https://twitter.com/denrase/status/1673968897257603072?s=20)),  that our App Store Connect integration fails to download the dSYMs. The integration only confuses users and causes problems. Therefore, we have to remove it.

### Tasks

```[tasklist]
### User-facing
- [x] platform docs: we updated the platform SDK docs for Apple, providing clarity around why bitcode can't be used anymore and that dSYMs need to be manually managed
- [x] product docs: not featured (anymore)
- [x] decide on deprecation/grace period
- [x] ~~add deprecation note to ASC integration settings~~
- [x] (optional) email orgs that currently have ASC integration set up
- [x] hide ASC integration for all orgs that don't use it yet https://github.com/getsentry/sentry/pull/72202
- [x] wait for deprecation period to pass (July 10, 2024)
- [x] hide ASC integration settings for all orgs https://github.com/getsentry/sentry/pull/73071
```

```[tasklist]
### Cleanup
- [ ] https://github.com/getsentry/sentry/pull/72203
- [ ] https://github.com/getsentry/sentry/pull/72206
- [ ] https://github.com/getsentry/getsentry/pull/14222
- [ ] https://github.com/getsentry/sentry/pull/71987
- [ ] https://github.com/getsentry/sentry/pull/73952
- [ ] https://github.com/getsentry/sentry/pull/73960
- [ ] https://github.com/getsentry/sentry/pull/74100
```

### Product Area

Integrations

**Comment by kahest** [comment]
Wrt deprecation plans:

- [x] platform docs: we updated the platform SDK docs for Apple, providing clarity around why bitcode can't be used anymore and that dSYMs need to be manually managed
- [x] product docs: not featured (anymore)
- [ ] decide on deprecation/grace period (e.g. 1-2 months)
- [ ] add deprecation note to ASC integration settings
- [ ] (optional) email orgs that currently have ASC integration set up
- [ ] hide ASC integration for all orgs that don't use it yet
- [ ] wait for deprecation period to pass
- [ ] deactivate integration
- [ ] hide ASC integration settings for all orgs
- [ ] remove code (integration setup page, celery task, API endpoint/model, etc.), dashboards,...

**Comment by jernejstrasner** [comment]
@kahest can this even be used at all? Eg. if we just removed does anything actually change for customers?
Reading online it seems like for at least 1 year you can't upload bitcode builds anymore. So the only edge case is for customers that have a bitcode build that has been uploaded with Xcode 13?

**Comment by Apollon77** [comment]
hey all, one question. We are on Sentry 24.4.2 and the UI shows us on each issue recently

> The supplied API key does not have sufficient permissions.

When I dig through network tab I came across

> {"ee306cc5-02df-429f-9540-aed0a0768a5a":{"credentials":{"status":"invalid","code":"app-connect-forbidden-error"},"pendingDownloads":0,"latestBuildVersion":"6.1.2","latestBuildNumber":"331172","lastCheckedBuilds":"2024-06-24T03:00:50.009136Z"}}

But I can not find at all where to configure App store connect in sentrry. Do you have any hint where I should disable it? Or is the issue for the error not this one?

**Comment by kahest** [comment]
@Apollon77 the changes to sunset the integration are not included in 24.4.2, so you should be able to configure/remove the App Store Connect integration in your project settings under `Debug Files`.

**Comment by Apollon77** [comment]
Thank you! Found it now and deleted it
