### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry#52154]
Based on the folder https://github.com/getsentry/sentry-docs/tree/master/src/wizard/java migrate the following java documentation:

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/52200
- [ ] https://github.com/getsentry/sentry/issues/52201
- [ ] https://github.com/getsentry/sentry/issues/52202
- [ ] https://github.com/getsentry/sentry/issues/52203
- [ ] https://github.com/getsentry/sentry/issues/52204
```

**Comment by priscilawebdev** [comment]
done in the PR https://github.com/getsentry/sentry/pull/53139
