### ISSUE TITLE
Node

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry#52150]
Based on the folder https://github.com/getsentry/sentry-docs/tree/master/src/wizard/node migrate the following node documentation:
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/52866
- [ ] https://github.com/getsentry/sentry/issues/52191
- [ ] https://github.com/getsentry/sentry/issues/52192
- [ ] https://github.com/getsentry/sentry/issues/52193
- [ ] https://github.com/getsentry/sentry/issues/52196
- [ ] https://github.com/getsentry/sentry/issues/52194
- [ ] https://github.com/getsentry/sentry/issues/52195
- [ ] https://github.com/getsentry/sentry/issues/52197
```

**Comment by stephanie-anderson** [comment]
Done
