### ISSUE TITLE
UI: Alert creation for on demand metrics

### ISSUE THREAD

**Issue by obostjancic** [getsentry/sentry#52245]
```[tasklist]
### Tasks
- [x] Pass generic metrics dataset
- [x] Disallow unsupported fields
- [x] Fix failing validation for `transaction.duration`
```
