### ISSUE TITLE
Allow common fields in alert creation

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry#52503]
Add more fields that relay supports to extract. See [`FieldValueProvider`](https://github.com/getsentry/relay/blob/4df0036da81d166f514f870aa206d2034c4d040d/relay-sampling/src/lib.rs#L578) for a list of supported fields.

Additional fields that should be added are listed here:

https://github.com/getsentry/sentry/blob/debdb49d0fbdc527b5910f109538a8126c909056/src/sentry/snuba/metrics/extraction.py#L66-L69

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/relay/pull/2293
- [ ] https://github.com/getsentry/sentry/pull/52514
- [ ] https://github.com/getsentry/sentry/pull/52613
- [ ] https://github.com/getsentry/sentry/pull/52612
- [ ] https://github.com/getsentry/sentry/pull/52701
```
