### ISSUE TITLE
Support chart queries for on-demand metrics

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry#52508]
Add chart based on extrapolation on events data in:
- alert creation/editing
- view existing alert
- dashboard widgets creation/editing
- view exiting widgets

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/53053
- [ ] https://github.com/getsentry/sentry/pull/52962
- [ ] https://github.com/getsentry/sentry/pull/53426
- [ ] https://github.com/getsentry/sentry/pull/53435
- [ ] https://github.com/getsentry/sentry/pull/53428
```
