### ISSUE TITLE
Improve In-Product Comms ☎️

### ISSUE THREAD

**Issue by roggenkemper** [getsentry/sentry#52532]
```[tasklist]
### Milestone 1
- [ ] https://github.com/getsentry/sentry/issues/52533
- [ ] https://github.com/getsentry/sentry/issues/52535
- [ ] https://github.com/getsentry/sentry/issues/52536
```

```[tasklist]
### Milestone 2
- [ ] https://github.com/getsentry/sentry/issues/53164
- [ ] https://github.com/getsentry/sentry/issues/53168
- [ ] https://github.com/getsentry/sentry/issues/53166
- [ ] https://github.com/getsentry/sentry/issues/53167
- [ ] https://github.com/getsentry/sentry/issues/53169
- [ ] https://github.com/getsentry/sentry/issues/53170
- [ ] https://github.com/getsentry/sentry/issues/53171
- [ ] https://github.com/getsentry/sentry/issues/54409
- [ ] https://github.com/getsentry/sentry/issues/57917
```
