### ISSUE TITLE
[Epic] Issue sort w/ GroupAttributes

### ISSUE THREAD

**Issue by barkbarkimashark** [getsentry/sentry#52539]
The current issue stream sorting is missing crucial Group-level information useful for sorting. We need to build a new snuba dataset which mirrors a subset of postgres Groups-related columns so we can join the attributes with the Events/SearchIssues dataset when we search for issues.

Internal tech spec: 
https://www.notion.so/sentry/Issue-Sorting-v2-1000cd274ad84b5c8a2ea99c5dcb1e21

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/52544
- [ ] https://github.com/getsentry/sentry/issues/52547
- [ ] https://github.com/getsentry/sentry/issues/52546
- [ ] https://github.com/getsentry/sentry/issues/52549
- [ ] https://github.com/getsentry/sentry/issues/52548
```
