### ISSUE TITLE
Support computed measurements for on-demand metrics

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry#52795]
There are three computed measurements in the product that can all be created by Relay during normalization, which allows to treat them like any other measurement.

The measurements to support are:
- `measurements.frames_slow_rate`
- `measurements.frames_frozen_rate`
- `measurements.frames_stall_percentage`

```[tasklist]
### Tasks
- [x] Materialize measurement values in Relay normalization
- [x] Map measurements to source field expression
- [x] (optional) Switch the product to use materialized measurements
```
