### ISSUE TITLE
[EPIC] Support high-level functions in on-demand metrics

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry#52797]
Alerts and widget fields can contain high-level functions that internally map to filters or computations. On metrics, all of these functions are mapped to derived metrics with a built-in formula to compute the resulting value.

To support these functions, we need to perform three steps:
1. Split the derived metric [1] into its basic metric components
2. Apply conditions to each of the actual metrics and send those to Relay
3. At query time, compose the partial metrics and run arithmetics

Metrics layer needs to be extended so we can query dynamic expressions. So far, the only expressions are built-in derived metrics. See the [**Exploration Document**](https://www.notion.so/sentry/Exploration-Metric-Expression-Queries-44a8cad243d34562bc38669b3b3b1c9c). The final spec will be pasted into the [**MQL Tech Spec**](https://www.notion.so/sentry/Metrics-Query-Language-MQL-fd9b062427554519b45cf2cdc8361961).

[1] derived metrics behave like metrics on the query side, but internally they are computations over two or more metrics of possibly different types

The functions to support are ([documentation of metrics](https://docs.sentry.io/product/performance/metrics/)):
- `apdex(threshold)`
- `count_web_vitals(vital, satisfaction)`
- `eps()` / `tps()` / `epm()` / `tpm()`
- `failure_count()`
- `failure_rate()`
- `user_misery(threshold)`

```[tasklist]
### Tasks
- [x] Build a grammar and expression tree for metrics layer
- [x] Add a query interface for new metrics queries
- [x] Build stopgap hard-coded converters for known functions
- [x] Query the hard-coded metrics
```

```[tasklist]
### Functions
- [x] apdex(threshold)
- [x] failure_rate()
- [ ] https://github.com/getsentry/sentry/issues/56044
- [ ] https://github.com/getsentry/sentry/issues/56659
- [ ] https://github.com/getsentry/sentry/issues/56572
- [ ] https://github.com/getsentry/sentry/issues/56947
- [ ] https://github.com/getsentry/sentry/issues/58233
- [ ] https://github.com/getsentry/sentry/issues/58234
```

```[tasklist]
### PRs
- [ ] https://github.com/getsentry/sentry/pull/53929
- [ ] https://github.com/getsentry/sentry/pull/54017
```

**Comment by evanh** [comment]
You will also need `http_error_rate` and `time_spent_percentage`.

**Comment by jan-auer** [comment]
Follow-up:
- Create logical definitions for the derived metrics
- Refactor alert conversion to yield multiple metrics
- Create a rule converter for conditions on expressions
- Create a query converter for expression queries

**Comment by matejminar** [comment]
We've added the support for failure rate and apdex. That's all we need for now for alerts. 
This task will be continued on when we're addressing dashboards.

**Comment by armenzg** [comment]
> You will also need `http_error_rate` and `time_spent_percentage`.

I've added these two to the list of tasks.

**Comment by armenzg** [comment]
> > You will also need `http_error_rate` and `time_spent_percentage`.
> 
> I've added these two to the list of tasks.

Removed these as out of scope.

**Comment by armenzg** [comment]
All functions have been implemented.
