### ISSUE TITLE
[Epic] Issue Details UI Improvements

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#52911]
[Internal Product Doc](https://www.notion.so/sentry/Simplify-Issue-Details-e46fa194b0ef4256aa753ca9d6f4cd78)

### Problem: What problem is this solving?

We want to make Issue Details more actionable for our users, so that they can go from alert/stream → debugging/triaging → fix as quickly as possible.

We’ve added a lot of content to Issue Details, but haven’t taken a step back to prioritize & streamline what’s displayed.

### What are we aiming to do?

- Provide a framework for quick iteration of the issue details UI
- Improve the actionability of issue details
- Promote consistency of experience
- Make sure the experience per platform is great

```[tasklist]
### New experience toggle
- [ ] https://github.com/getsentry/sentry/issues/60282
```

```[tasklist]
### Stack trace
- [ ] https://github.com/getsentry/sentry/issues/53132
- [ ] https://github.com/getsentry/sentry/issues/44251
- [ ] https://github.com/getsentry/sentry/issues/47598
- [ ] https://github.com/getsentry/sentry/issues/52912
- [ ] https://github.com/getsentry/sentry/issues/58460
- [ ] https://github.com/getsentry/sentry/issues/59030
- [ ] https://github.com/getsentry/sentry/issues/60013
- [ ] https://github.com/getsentry/sentry/issues/60438
- [ ] https://github.com/getsentry/sentry/issues/61572
- [ ] https://github.com/getsentry/sentry/issues/61577
- [ ] https://github.com/getsentry/sentry/issues/61605
- [ ] https://github.com/getsentry/sentry/issues/61731
- [ ] https://github.com/getsentry/sentry/issues/61769
- [ ] https://github.com/getsentry/sentry/issues/62403
- [ ] https://github.com/getsentry/sentry/issues/62621
- [ ] https://github.com/getsentry/sentry/issues/60219
```

```[tasklist]
### Breadcrumbs
- [ ] https://github.com/getsentry/sentry/issues/52929
- [ ] https://github.com/getsentry/sentry/issues/54269
```

```[tasklist]
### Layout changes
- [ ] https://github.com/getsentry/sentry/issues/50912
- [ ] https://github.com/getsentry/sentry/issues/58388
```

```[tasklist]
### Replay in errors
- [ ] https://github.com/getsentry/sentry/issues/63157
```

```[tasklist]
### Context
- [ ] https://github.com/getsentry/sentry/issues/58573
```
