### ISSUE TITLE
Crons: Run monitor tasks `check_missing` + `check_timeout` via topic boundaries OR clock pulses

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry#53661]
### The problem

Currently we have two tasks which **must run once per minute**. These task are responsible for creating missed check-ins for monitors which did not receive check-ins on time, and for marking check-ins as timed-out when they pass their `timeout_at` window.

There are two problems with these tasks

 1. If we **backlog our consumer queue** monitors may be marked as missed or in-progress check-ins may be marked as timed out since the tasks may correctly run on time, but check-ins which should have been processed on time may have been backlogged. (we should be able to completely solve this)

 2. It is possible that we are late to marking missed or timed-out check-ins due to periodic tasks being skipped during deploys. This is an artifact of how the celery beat runner is stopped and restarted during deploys. (we can improve this, but not necessarily solve it)

    (This will not be completely solved by this issue)

### Solution

Instead of running our tasks via Celery's Period Tasks, we can provide a way to have our tasks be triggered via our consumer, in-time with our kafka topic. This will avoid our tasks being run out even when there is a backlog.

I propose we have **two modes** which this should be done in, due to constraints of SASS, single tenant, and on-premise.

(The mode would be configured with a `settings` flag)

 1. **Mode one:** _"High volume mode"_ -- When we are guaranteed to have a high volume of monitor check-ins from our producer. In this scenario we compute the timestamp of the message with seconds removed (floored to the minute) and compare that with the previously stored value. This would be stored in Redis. Any time we roll over the minute we hold a lock and schedule the two tasks (`check_missing` / `check_timeout`) for immediate execution via celery task runners. Importantly will **receive a timestamp from the messages as their reference time** and will use that to determine what monitors should be marked as missed or check-ins marked as timed out.

    #### Why this mode?

    Due to the high volume we're able to accurately trigger our tasks on minute markers **purely based on our kafka topic**. With high volume, this is the most accurate way to schedule our two monitor tasks for execution. 

 3. **Mode two:** _"low volume mode"_ -- When we do not have a high volume of check-ins, such as single tenant or on premise. In this scenario we have another periodic celery task which produces a clock pulse message **once per minute** and puts the message in the `ingest-monitors` topic. These messages should include the timestamp of when the pulse was generated. Ideally these pulses are generated **on the minute** exactly wall clock time so they are put into the queue in order. 
  
    Our `monitor_consumer` arroyo processor would then discriminate on clock pulse messages and schedule the two tasks (`check_missing` / `check_timeout`) for immediate execution via celery task runners. Importantly will **receive a timestamp from the messages as their reference time** and will use that to determine what monitors should be marked as missed or check-ins marked as timed out.

    #### Why this mode?

    When volume of check-ins is not high we are not able to simply use our messages as a clock. Instead we must have an external clock pulse that is **guaranteed** to trigger so we can ensure even in a backlog situation we have messages in the kafka queue that are in time with when the tasks should be run.

### Task execution order

Another important aspect is that when we **do backlog** and we push many of our two tasks into queue for celery to process, each set of tasks SHOULD happen in order and NOT at the same time. To guarantee this we need to create a new worker queue for each task with the size of 1, so each task runs sequentially. 

### Notes

 * We should validate that when we DO have a backlog, we do not run into a scenario where the `next_checkin` value is generated based on the current time, it MUST use the reference time, so future messages in the backlog are correctly processed.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/54204
- [ ] https://github.com/getsentry/sentry/pull/54319
- [ ] https://github.com/getsentry/sentry/pull/54341
- [ ] https://github.com/getsentry/getsentry/pull/11372
- [ ] https://github.com/getsentry/getsentry/pull/11373
- [ ] https://github.com/getsentry/sentry-options-automator/pull/171
- [ ] https://github.com/getsentry/ops/pull/7658
- [ ] https://github.com/getsentry/sentry/pull/54647
- [ ] https://github.com/getsentry/sentry/pull/54768
- [ ] https://github.com/getsentry/sentry/pull/54646
- [ ] https://github.com/getsentry/sentry-options-automator/pull/177
- [ ] Define a single worker queue for the two monitor topics
```

**Comment by fpacifici** [comment]
Regarding the two modes:
Can we just have the pulse message running in both modes and treat everything as high volume mode? 
Having two separate modes that have to be manually selected and are not adaptive to the actual load makes the system more fragile.
- It adds moving parts some of which are not stressed in the development environment. That creates blind spots. We will likely develop based only on one, and break production on what is not tested. 
- More failure modes to deal with.
- The system does not adapt to to the load itself but requires manual intervention to switch from one mode to another if the load profile changes. And it will.

If you add the pulse in all environments you are guaranteed to have at least one message per minute everywhere, unless the consumer is backlogging, and just run in high volume mode.

**Comment by fpacifici** [comment]
Regarding using Kafka as a clock. 
How are we dealing with cases where one partition is slower than others? It happens during backlogs. Few partitions backlog first and some clear before others. 

If one partition is further back from another and the more recent  one is triggering the task to fill in missing checkins you may be filling in check ins that are still stuck in the slower partition but not missing. 

There are two ways to address this and we do for subscriptions:
- Use the subscriptions scheduler, which instead of using one partition as a clock, uses all of them together. Basically it keeps track of a watermark across all partitions, and only executes a task (evaluating subscriptions there) when all partitions have reached minute = X. This would require you to have some sort of commit log as one consumer needs visibility on all partitions.
- Semantically partition your data and make each replica take care only of the tasks that concerns the partitions it is consuming. The way to break down your topic semantically depends on the content of the topic. For events we used project which is horrible asindividual projects are too big. But maybe we can find a dimension that is sensible here. This way you would also not need Redis.

**Comment by fpacifici** [comment]
re: locks. 
You do not need an explicit lock on Redis. 
Redis has atomic SET operations that return the previous value of the key you are setting. 
Your consumer can work this way:
```
previous_value_set = None
if message.timestamp % whatever != previous_value_set:
   previous_redis_value = SET(key, message.timestamp & whatever
   if previous_redis_value != previous_value_set:
      # We changed the value in redis so nobody ran into that minute before 
     schedule_task
   else:
      # somebody else scheduled the task
   previous_value_set = message.timestamp & whatever.
   # This so that for the rest of this minute this specific consumer will not bother redis as we already know what the result would be
```

**Comment by evanpurkhiser** [comment]
Thanks for the feedback @fpacifici

> You do not need an explicit lock on Redis.

Thanks for this feedback, I've addressed this here: https://github.com/getsentry/sentry/pull/54341

> Can we just have the pulse message running in both modes and treat everything as high volume mode?

This is good, yes. I will follow up and implement this.

> How are we dealing with cases where one partition is slower than others? It happens during backlogs. Few partitions backlog first and some clear before others.

Also a good catch, we didn't take into consideration a partial partition backlog. I will follow up with @wedamija about this tomorrow and we'll come up with a plan.

**Comment by evanpurkhiser** [comment]
This is now completed!
