### ISSUE TITLE
[EPIC] Simplify multi-snippet onboarding

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry#53859]
We aim to simplify the getting started docs by consolidating code snippets for various languages into a single snippet with multiple tabs for easy alternation.

We'd like to replicate the following example from our [Java docs](https://docs.sentry.io/platforms/java/) on the Getting Started docs:

https://github.com/getsentry/sentry/assets/29228205/435bf915-4759-4cdd-99fe-59bfb31ee486

## Phase 1: Proof of Concept

_Planned Completion: 2023-09-25_
```[tasklist]
### Tasks
- [x] Pick a complicated platform on which we'll do PoC
- [ ] https://github.com/getsentry/sentry/issues/55325
- [ ] https://github.com/getsentry/sentry/issues/50226
- [ ] https://github.com/getsentry/sentry/issues/55761
```

## Phase 2: All Platforms

_Planned Completion: 2023-10-09_
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/51586
- [ ] https://github.com/getsentry/sentry/issues/56838
- [ ] https://github.com/getsentry/sentry/issues/56839
```
