### ISSUE TITLE
[Epic] Alert Rule Endpoint Deprecation

### ISSUE THREAD

**Issue by ceorourke** [getsentry/sentry#54005]
We have some unnecessary duplication between the `ProjectAlertRuleIndexEndpoint` and the `OrganizationAlertRuleIndexEndpoint`, and the `ProjectAlertRuleDetailsEndpoint` and the `OrganizationAlertRuleDetailsEndpoint` - these roughly do the same thing (fetch, create, and delete metric alert rules) except one is passed a project param. Having both leads to confusion about which one to use and duplicate code to maintain in two places (which already have differences).

I made [this Datadog chart](https://app.datadoghq.com/dashboard/i4m-tvq-hxr/notifications-dashboard?fullscreen_end_ts=1689726862953&fullscreen_paused=false&fullscreen_section=overview&fullscreen_start_ts=1687134862953&fullscreen_widget=2096549740134976&from_ts=1687133512702&to_ts=1689725512702&live=true) to see usage of the index endpoint's GET and POST methods. The project endpoint has far less usage and the organization endpoint can be passed multiple projects (though we don't do this in practice, the `AlertRule` model technically supports it) which is why I think we should stop using it and use the organization one instead. We have customers using the some of the endpoints in sentry apps, and the Terraform plugin uses one too, so to begin I'm "soft deprecating" them by moving the code into shared functions they can both call, and then later on we can actually deprecate them.

```[tasklist]
### Soft deprecate the `ProjectAlertRuleIndexEndpoint` in favor of using the `OrganizationAlertRuleIndexEndpoint`
- [x] [Share POST method code between endpoints](https://github.com/getsentry/sentry/pull/53126)
- [x] [Replace front end usage of POST method](https://github.com/getsentry/sentry/pull/53630)
- [x] [Share GET method code between endpoints](https://github.com/getsentry/sentry/pull/53658)
```

```[tasklist]
### Soft deprecate the `ProjectAlertRuleDetailsEndpoint` in favor of using the `OrganizationAlertRuleDetailsEndpoint`
- [x] [Share GET method code between endpoints](https://github.com/getsentry/sentry/pull/53999)
- [x] [Share PUT method code between endpoints](https://github.com/getsentry/sentry/pull/54152)
- [x] [Replace front end usage of PUT method](https://github.com/getsentry/sentry/pull/54336)
- [x] [Share DELETE method code between endpoints](https://github.com/getsentry/sentry/pull/53970)
- [x] [Replace front end usage of DELETE method](https://github.com/getsentry/sentry/pull/54003)
```

```[tasklist]
- [ ] Contact the [terraform plugin](https://github.com/jianyuan/terraform-provider-sentry) repo maintainer as they are the only user of this endpoint. We may end up stuck with this endpoint for longer if the deprecation would affect older versions of the plugin.
- [ ] Set the deprecation decorator to enable the headers. See the [API Deprecation Policy](https://www.notion.so/sentry/Sentry-API-Deprecation-Policy-ccbdea15a34c4fdeb50985685adc3368). Need to decide on timeline.
```
