### ISSUE TITLE
[EPIC] Investigation Bias

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#54094]
# Problem
Our current biases work well generically in order to collect a baseline of samples, because they prioritise retaining data that is valuable for any customer at any given time. But there are (1) needs specific to the individual customer we simply can’t know and (2) temporary scenarios, where very specific data becomes more important (which we again can’t predict). Today a customer has no way to collect this data when needed.

# Proposed solution
When troubleshooting a particular issue, a customer can specify certain criteria and for a limited amount of time (e.g. 1h) or until a certain amount of samples have been gathered (e.g. 100) and we keep all events that match that criteria.

Note: we either only allow users to set criteria that can guarantee full traces, or make them aware that we will only collect transactions and this can break traces.

## Phase 1: Proof of Concept

_Planned Completion: 2023-09-25_
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/55685
- [ ] https://github.com/getsentry/sentry/issues/55679
- [ ] https://github.com/getsentry/sentry/issues/55680
- [ ] https://github.com/getsentry/sentry/issues/55682
- [ ] https://github.com/getsentry/sentry/issues/55683
- [ ] https://github.com/getsentry/sentry/issues/57264
- [ ] https://github.com/getsentry/sentry/issues/56864
- [ ] https://github.com/getsentry/sentry/issues/57265
```

## Phase 2: Internal

_Planned Completion: 2023-10-23_
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/54449
- [ ] https://github.com/getsentry/sentry/issues/57263
- [ ] https://github.com/getsentry/sentry/issues/57755
- [ ] https://github.com/getsentry/sentry/issues/56840
- [ ] https://github.com/getsentry/sentry/issues/58986
- [ ] https://github.com/getsentry/sentry/issues/57543
- [ ] https://github.com/getsentry/sentry/issues/57752
- [ ] https://github.com/getsentry/sentry/issues/57756
```
```[tasklist]
### Phase 3: EA
- [ ] Update docs
- [ ] https://github.com/getsentry/sentry/issues/55914
- [ ] https://github.com/getsentry/sentry/issues/56841
- [ ] https://github.com/getsentry/sentry/issues/57276
```

**Comment by aellett** [comment]
We’ve got a use case that’s sort of adjacent to this. We occasionally receive a report that “Executive E saw odd behavior in the app” and the request is to understand why.

We’ve got an assortment of manually instrumented performance transactions that should capture some or all of the user’s journey. However, we find that we’re not able to reliably find any transactions associated with that user even though we have 1) a unique user identifier in the form of a tag set on the scope of that session and 2) the sampling rate set at 100%.

It doesn’t sound to me like this approach would address our issue, as you’d have to know that something was about to happen before specifying the criteria. Is there a better way to achieve what we’re looking for? If we sample at 100%, is there a way to guarantee that we’ll be able to find a user’s performance transactions in recent history?

**Comment by hubertdeng123** [comment]
@aellett Thanks for writing in. Could you file a separate issue for this where we can address your concern? This way we can properly respond and keep track of your use case, since this issue is an epic used for project tracking purposes.

**Comment by aellett** [comment]
Thanks, filed https://github.com/getsentry/sentry/issues/55706 for this.

**Comment by Jesse-Box** [comment]
@matejminar @RaduW 

Do we have any understanding as to how people typically investigate performance problems on Sentry? If so, can you elaborate on the most common workflows?
