### ISSUE TITLE
Crons: Alert Thresholds + Issue Lifecycle

### ISSUE THREAD

**Issue by rjo100** [getsentry/sentry#54202]
Allow customers to set failed/recovered thresholds for monitors. Monitors will only alert/move into failed state after X number of successive failures and only recover/move into OK state after Y number of successive OK check-ins.

Notion scratchpad:
https://www.notion.so/sentry/Stateful-Monitors-6b96e53a48c543b6a38846fc01e74841
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/54514
- [ ] https://github.com/getsentry/sentry/issues/54704
- [x] Make sure index is properly done for mark_ok + mark_failed "lookbacks"
- [ ] Investigate simplifying MonitorEnvironment statuses + fixing sort
- [ ] https://github.com/getsentry/sentry/issues/55421
- [ ] https://github.com/getsentry/sentry/issues/55573
- [x] Add frontend setting to allow customer to set new values
- [ ] Document new config parameters
- [ ] https://github.com/getsentry/sentry/issues/56354
```

**Comment by evanpurkhiser** [comment]
How will we represent the "incidents" (Sentry Issues).

Are we planning to store those in our own table so they are easy to query on for monitors, or are we going to use the issues platform as a source of truth.

@wedamija any thoughts here?
