### ISSUE TITLE
Implement Metric Alerts

### ISSUE THREAD

**Issue by spalmurray** [getsentry/sentry#54396]
🤠 
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/55930
- [ ] https://github.com/getsentry/sentry/pull/57034
- [ ] https://github.com/getsentry/sentry/pull/57068
- [ ] https://github.com/getsentry/sentry/pull/57079
- [ ] https://github.com/getsentry/sentry/pull/57092
- [ ] https://github.com/getsentry/sentry/pull/57094
```
