### ISSUE TITLE
[Ingest Investigation] Reservoir of samples

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#54449]
We need to communicate to Relay that the user would like to upsample specific transaction with applied query filters.
E.g. upsample transaction X with custom tag value Y and transaction duration more than Z.

Ideally, this would not just multiply the base sample rate for a limited amount of time, but it would set it to 100% until we collect 10 samples. (10 is made up number)

```[tasklist]
### Tasks
- [x] Update this issue description
- [x] Write a basic tech solution
- [x] Implement the solution in relay
```

**Comment by jan-auer** [comment]
Moving this back through triage one more time to discuss with the team.

**Comment by TBS1996** [comment]
Ingest-side is finished 🤞

Next phase will be implementation of sentry-side and a test to see if it works, waiting for @RaduW  for status here.
