### ISSUE TITLE
[Epic] Prevent and Remove Bad Alerts

### ISSUE THREAD

**Issue by ceorourke** [getsentry/sentry#54482]
Spec [here](https://www.notion.so/sentry/Prevent-and-remove-bad-alerts-b474e018c47e4d86b69cdb93b345640f)

```[tasklist]
### Prevention of Bad Alerts \[Milestone 1]
- [x] [Prevent users from making alerts that don’t have any actions or are a duplicate of an existing rule in that project](https://github.com/getsentry/sentry/pull/54515)
- [x] [Prevent front end from passing name data in conditions and actions](https://github.com/getsentry/sentry/pull/54739)
- [x] [Prevent back end from saving name data in conditions and actions](https://github.com/getsentry/sentry/pull/54746)
- [x] [Pre-save Rule to prevent any name data in conditions and actions](https://github.com/getsentry/sentry/pull/55091)
- [x] [Migrate rule data for consistency](https://github.com/getsentry/sentry/pull/54915)
- [x] [Implement the proper disabled state for issue alerts so they don’t trigger at all if they are disabled](https://github.com/getsentry/sentry/issues/55097)
- [x] [Add rule status to response for individual rule and combined rules](https://github.com/getsentry/sentry/issues/55098)
- [x] [Create endpoint to return data about whether an alert is "bad"](https://github.com/getsentry/sentry/issues/55101)
- [x] Enable a disabled alert on save if it passes conditions
```
```[tasklist]
### Prevention of Noisy Alerts \[Milestone 2]
- [x] [[FE] Add warning to users who try to make an alert that is triggered on every event and goes to a communication channel](https://github.com/getsentry/sentry/issues/55116)
```
```[tasklist]
### Migrate Existing Bad Alerts \[Milestone 3]
- [x] [[FE] Show the disabled and muted state in the issue list view](https://github.com/getsentry/sentry/issues/55099)
- [x] [[FE] Show the disabled state on the alert details page](https://github.com/getsentry/sentry/issues/55100)
- [x] [Write a migration to disable alerts with no actions and alerts that are exact duplicates of another in the same project](https://github.com/getsentry/sentry/issues/55502)
```
```[tasklist]
### Migrate Neglected Alerts \[Milestone 4]
- [x] [Data] [Write a Redash query to get all rules with 0% CTR](https://github.com/getsentry/sentry/issues/56188)
- [ ] https://github.com/getsentry/sentry/issues/56190
- [ ] https://github.com/getsentry/sentry/issues/56191
- [ ] https://github.com/getsentry/sentry/issues/56192
- [ ] https://github.com/getsentry/sentry/issues/56193
- [ ] https://github.com/getsentry/sentry/issues/56194
- [ ] https://github.com/getsentry/sentry/issues/56195
- [ ] https://github.com/getsentry/sentry/issues/56196
- [ ] https://github.com/getsentry/sentry/issues/56197
- [ ] https://github.com/getsentry/sentry/issues/56198
- [ ] https://github.com/getsentry/sentry/issues/56681
- [ ] https://github.com/getsentry/sentry/issues/56682
- [ ] https://github.com/getsentry/sentry/issues/57339
```
