### ISSUE TITLE
[tracker] Enable GA for escalating and issue states V1

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#55270]
```[tasklist]
### V1 GA
- [ ] Request ops to run the script
- [ ] Staggered GA ([Adjust flag](https://github.com/getsentry/getsentry/blob/8f2f1b1348b9163febce6494229d2b693a9cce85/getsentry/features.py#L1583-L1593)) - Add increments of x% from the beginning of the block
- [ ] See if the code can be made safer to not require the script
```
```[tasklist]
### V1 Post-GA
- [ ] Run forecast generation less frequently ([link](https://github.com/getsentry/sentry/blob/master/src/sentry/conf/server.py#L1106-L1111)) 
```
