### ISSUE TITLE
[Milestone] Instrumented MiniMetrics in Production

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#55439]
**Acceptance criteria**

* minimetrics is running on sentry.io with a low sample rate
* emit measurements for number of data points and envelopes

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-python/issues/2330
- [x] Add dual writing in `sentry.metrics` to prod and minisentry
- [x] instrumentation that measures number of data points and envelopes is emitted for load estimations
- [x] Deploy minimetrics prototype to sentry.io
```

**Comment by mitsuhiko** [comment]
@iambriccardo did we already deploy this?

**Comment by iambriccardo** [comment]
The code is currently operating in production with a 0.1 sample rate for ds tasks. I have prepared pull requests for tomorrow to introduce high-volume metrics and to test the system's scalability.
