### ISSUE TITLE
Add a new "custom" usecase for metrics

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry#55451]
To isolate custom metrics from built-in ones, they will be associated with a new "custom" use case. This use case needs to be defined in Relay, Sentry, and Snuba.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/relay/pull/2443
- [ ] https://github.com/getsentry/sentry/pull/55453
- [x] Check Snuba
- [ ] https://github.com/getsentry/getsentry/pull/11540
```

See also: 
- https://github.com/getsentry/relay/issues/2441

**Comment by jan-auer** [comment]
Snuba does not need to be updated since the use case is a plain string.
