### ISSUE TITLE
[Epic] Replay Accessibility Information - Alpha

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#55501]
Building off the hackweek project: https://hackweek.getsentry.net/projects/-Nc4gc8-qFU20Q5zGuKj/accessibliity-issues-via-session-replay

KTTR: https://www.notion.so/sentry/8dad2130ed2c497c834b79d90af0bb7a?v=c4d436af7be140a095ce28a6cc869830&p=3f444b1c00044aa8b17015d59ed2c1e8&pm=s
Lets ship this!

v0 retrospective: https://www.notion.so/sentry/Accessibility-Insights-V0-Open-Beta-6d61574b4d1e4b89a54207333a9a9021

```[tasklist]
### Backend Tasks:
- [x] https://github.com/getsentry/sentry/issues/55293
- [x] Build nodejs docker image (pipeline, tests, `sentry devserver`, etc)
- [x] Implement docker image code: see https://github.com/getsentry/sentry/pull/55198/files
- [x] Create python api's to, synchronously, forward a11y requests to the nodejs server, and proxy response back
- [ ] https://github.com/getsentry/session-replay-analyzer/issues/22
```

```[tasklist]
### UI Tasks
- [x] Merge basic table view from https://github.com/getsentry/sentry/pull/55198
- [x] Highlight rows with a background color, to match their impact/severity
- [x] Implement table search&filtering from https://github.com/getsentry/sentry/pull/55198
- [x] Implement click-for-details pane from https://github.com/getsentry/sentry/pull/55198
- [x] Render clicked DOM element in details pane
- [x] Switch to prod endpoint and cleanup mockA11yData loader
- [x] Relabel the tab on Replay Details page
- [x] Link on _Help_ to suggestion should open a new page
- [x] Create a 'analyze the replay at this time' button
```
```[tasklist]
### Alpha Launch
- [ ] Product Docs Callout on https://docs.sentry.io/product/session-replay/replay-details/ [Needs to say it's for EA]
- [ ] Change log Post [Jasmin]
- [x] "Alpha" badge
```

**Comment by bruno-garcia** [comment]
GitHub discussion about Accessibility: https://github.com/getsentry/sentry/discussions/58423

**Comment by ryan953** [comment]
Meeting notes: https://www.notion.so/sentry/Meeting-Notes-12-4-8d4e427c88aa41f8bce74d5756750375

**Comment by ryan953** [comment]
Ideas for followup projects: https://www.notion.so/sentry/Accessibility-Ideas-273c6c74095542168672507190b24670

**Comment by bruno-garcia** [comment]
The accessibility tab in Replay Details is available to all organizations.
This is an `alpha` release to get feedback from the community.

Let us know what you think on: https://github.com/getsentry/sentry/discussions/58423
