### ISSUE TITLE
Make metrics queryable in the admin interface

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#55635]
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/55749
- [ ] https://github.com/getsentry/getsentry/pull/11562
- [ ] https://github.com/getsentry/sentry/pull/55772
- [ ] Update https://www.notion.so/sentry/Metrics-API-373168c15ed44ebbbca300e9a3861949
```
