### ISSUE TITLE
[Milestone] Store and Query Metrics

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#55647]
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/55635
- [ ] https://github.com/getsentry/relay/issues/2461
- [ ] https://github.com/getsentry/snuba/issues/4675
- [ ] https://github.com/getsentry/relay/issues/2463
```
