### ISSUE TITLE
[EPIC] On-demand metrics - Dashboards

### ISSUE THREAD

**Issue by obostjancic** [getsentry/sentry#55646]
Large-scale customers are currently faced with a degraded experience in Dashboards on AM2 plans compared to AM1. Previously, customers could effectively slice and dice their event data based on ANY event property and obtain metrics and trends based on 100% of transactions sent. AM2 plans restrict this to a [limited set of fields (or tags)](https://docs.sentry.io/product/alerts/create-alerts/metric-alert-config/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2F#tags--properties) for which we extract metrics.

This results in the following limitations in dashboards:

* Queries with unsupported metrics will fall back to sampled data and not be backed by total transactions/metrics. This may result in certain trends which are not representative of the whole and lead to incorrect interpretation, thus, rendering them unusable.

See: [**Tech Design**](https://www.notion.so/sentry/002792cba68441eba5abb217710c2c23)

```[tasklist]
### Extraction
- [ ] https://github.com/getsentry/sentry/issues/52797
- [ ] Support Discover equation expressions for queries
- [ ] Support all context fields in conditions
- [ ] Evaluate tag cardinality to guard grouping in widgets
- [ ] Emit tags into metrics spec for group_by in widgets
- [ ] Cogs estimation for dashboards
- [ ] Refactor expression transformation for ondemand metrics
- [ ] (optional) Remove country_code and status_code from standard metrics
- [ ] https://github.com/getsentry/sentry/issues/55990
```

```[tasklist]
### Querying
- [ ] https://github.com/getsentry/sentry/issues/54668
- [ ] https://github.com/getsentry/sentry/issues/54669
- [ ] https://github.com/getsentry/sentry/issues/52797
- [ ] Support Discover equation expressions for queries
- [ ] Support all context fields in conditions
- [ ] Issue groupby when running metrics query
```

**Comment by armenzg** [comment]
We're using https://github.com/orgs/getsentry/projects/156 to track the work.
