### ISSUE TITLE
[Milestone] Metrics Explorer UI Polish

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#55655]
Improve the metrics explorer experience to turn into a decent out of the box user experience as a starting point for further experimentation.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/55652
- [ ] https://github.com/getsentry/sentry/issues/55654
- [ ] https://github.com/getsentry/sentry/issues/56370
- [ ] https://github.com/getsentry/sentry/issues/56371
- [ ] https://github.com/getsentry/sentry/issues/56373
- [ ] https://github.com/getsentry/sentry/issues/56374
- [ ] https://github.com/getsentry/sentry/issues/56372
- [ ] https://github.com/getsentry/sentry/issues/56711
- [ ] https://github.com/getsentry/sentry/issues/56714
- [ ] https://github.com/getsentry/sentry/issues/56715
- [ ] https://github.com/getsentry/sentry/issues/56726
- [ ] https://github.com/getsentry/sentry/issues/55653
- [ ] https://github.com/getsentry/sentry/issues/56728
- [ ] https://github.com/getsentry/sentry/issues/56732
- [ ] https://github.com/getsentry/sentry/issues/56738
- [ ] https://github.com/getsentry/sentry/issues/56712
```
