### ISSUE TITLE
In-Product Source Maps Debugger

### ISSUE THREAD

**Issue by lforst** [getsentry/sentry#55662]
We want to build a proper source maps debugger. Something like `sentry-cli sourcemaps explain` but inside the product.

The idea is to show something on every unsymbolicated stack frame that lets you open a modal to understand why that stack frame wasn't properly symbolicated.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/55663
- [ ] https://github.com/getsentry/sentry/issues/55664
- [ ] https://github.com/getsentry/sentry/pull/56257
- [ ] https://github.com/getsentry/sentry/pull/56321
- [ ] https://github.com/getsentry/symbolicator/issues/1300
- [ ] https://github.com/getsentry/sentry/pull/57655
- [ ] https://github.com/getsentry/sentry/pull/57802
- [ ] https://github.com/getsentry/sentry/issues/57567
- [ ] https://github.com/getsentry/sentry/issues/57561
- [ ] https://github.com/getsentry/sentry/issues/57553
```
