### ISSUE TITLE
Publish Issue and Metric Alert Rule APIs

### ISSUE THREAD

**Issue by isabellaenriquez** [getsentry/sentry#55920]
Now that [the appropriate Issue and Metric Alert APIs have been identified](https://www.notion.so/sentry/Issue-and-Metric-Alert-APIs-for-Publishing-73a21245d24643bc8e72e5957fb8ca1b?pvs=4), we need to actually publish them. After publishing, the APIs should be added to the docs.

[Product Spec](https://www.notion.so/sentry/Publish-Issue-and-Metric-Alert-APIs-e4c64fb03e96461799ca57e1d9a1910a?pvs=4)
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/56674
- [ ] https://github.com/getsentry/sentry/issues/56675
- [ ] https://github.com/getsentry/sentry/issues/56676
- [ ] https://github.com/getsentry/sentry/issues/56677
```
