### ISSUE TITLE
Support custom gauge metrics

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry#55984]
Sentry uses gauges a lot, so we will have to add support for them in generic metrics. See the definition of [`GaugeValue`](https://getsentry.github.io/relay/relay_metrics/struct.GaugeValue.html).

## Aggregation

Gauges are fixed-size lossy aggregations without stochastic sketches. Per bucket, they store:
 - The number of raw values inserted (similar to distributions)
 - The minimum, and maximum values
 - The sum of all values
 - The "last" value, which is an implementation-defined value chosen from the inserted values. It should be the latest inserted value, however there are no consistency guarantees over which one is to be considered last.

Supported aggregation functions on metrics layer to query gauges are:
- `min()`, `max()` to retrieve the minimum and maximum value
- `count()` and `sum()` to retrieve the number of values and their sum
- A function to be named that resolves the "last" value
- `avg()` to compute the average of reported values (calculated via `sum() / count()`)

## JSON Schema

Gauges are objects with five values, see [`GaugeValue`](https://getsentry.github.io/relay/relay_metrics/struct.GaugeValue.html).

```[tasklist]
### Tasks
- [ ] Implement a gauge dataset in generic metrics
- [ ] Add Kafaka schemas for indexer and snuba
- [ ] Support gauges in the indexer
- [ ] Support queries for gauges
```
