### ISSUE TITLE
[EPIC] No on-demand metrics support for equations work

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#55994]
We are not going to support on-demand metrics for equations. If we find there's great demand or high usage we will but for now we're going to make sure we make it clear and measure the impact.

```[tasklist]
### Research
- [ ] Determine how many widgets use equation
- [ ] https://github.com/getsentry/sentry/issues/57472
```

```[tasklist]
### UI, docs and design
- [ ] Determine where in the docs to describe this
- [ ] Communicate with sales the decision
- [ ] https://github.com/getsentry/sentry/issues/55990
- [ ] UI work to complete this
```

**Comment by ale-cota** [comment]
No longer relevant.
