### ISSUE TITLE
Cleanup manual SDK instrumentation

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry#56248]
see https://www.notion.so/sentry/Sentry-SDK-Custom-Code-and-why-we-Should-fix-it-932c8493c29b4bb2bf18c2fc4b729ef1?pvs=4

### motivation

* custom transactions don't propagate tracing headers properly, so dynamic sampling is broken
* sometimes they shouldn't even be needed, check which ones we can just delete
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/63590
- [ ] https://github.com/getsentry/sentry/issues/63591
- [x] [canceled] Clean up Multiplexing Transport
```

**Comment by szokeasaurusrex** [comment]
Once version 2.0 of the SDK is released, we can implement #65869
