### ISSUE TITLE
Migrate product specific getting-started docs

### ISSUE THREAD

**Issue by ArthurKnaus** [getsentry/sentry#56387]
### Background

We already migrated the general onboarding docs from `sentry-docs` to `sentry`.
No we want to do the same for the product specific ones.

Currently they load the content from `sentry-docs` and display it in a sidebar.
The platforms that are supported for each product are allow-listed for each one:

* Performance docs are enabled for `javascript` & `javascript-react`
* Replay docs are enabled for every platform in [replayPlatforms](https://github.com/getsentry/sentry/blob/f9e62f5767804f9844f92348cb4b8cb4f22d8195/static/app/data/platformCategories.tsx#L330).
* Profiling is enabled  every platform that returns a string in [getDocsPlatformSDKForPlatform](https://github.com/getsentry/sentry/blob/afba7e83a7e94894cb183da412070f75445c3eba/static/app/utils/profiling/platforms.tsx#L27).

So there is a slight miss-match between supported products per platform in the onboarding & supported platform per product in the product specific docs.

### Proposal

1. Update the `steps()` functions so they always build the whole content. Atm for some platforms a part of the content is being injected.
2. Ensure the functions share a common interface that allows for switching single features on / off.
(e.g. only render performance content)
3. Support experimental & beta profiling platforms in those functions.
4. Adapt product specific docs to load the content via the relevant `step()` function and render it using their own layout.

 ### Open questions
 
 * How should we handle multi-snippet docs?
   * e.g. display the selector, store the onboarding selection or just display the default choice for each platform
 * Should we extend the supported platforms for the performance docs?
 * Should platforms with experimental profiling display it in the onboarding docs?
 
 ### Further todos

* clicking on “set up profiling” does not pre-fill the currently selected project in the profiling docs -> we should fix that.

---

This issue is a result of this spike https://github.com/getsentry/sentry/issues/53861
```[tasklist]
### Phase 1
- [ ] https://github.com/getsentry/sentry/issues/56547
- [ ] https://github.com/getsentry/sentry/issues/56548
- [ ] https://github.com/getsentry/sentry/issues/57447
- [ ] https://github.com/getsentry/sentry/issues/56549
- [ ] Update contribution docs https://docs.sentry.io/contributing/onboarding-wizard/
```

```[tasklist]
### Phase 2
- [ ] https://github.com/getsentry/sentry/issues/56550
- [ ] https://github.com/getsentry/sentry/issues/56551
- [ ] https://github.com/getsentry/sentry/issues/56552
- [ ] https://github.com/getsentry/sentry/issues/56553
```
