### ISSUE TITLE
Crons: Enforce margin minimum of 1 minute

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry#56526]
This is the implementation tracking issue for https://github.com/getsentry/sentry/issues/49011#issuecomment-1681324305

Fixes https://github.com/getsentry/sentry/issues/49011

### The problem

The issue here is that while we say the "default" is zero, it is not actually zero, indeed we give you a 1 minute grace period to complete your check-in. That logic is controlled here

https://github.com/getsentry/sentry/blob/774df5931d33dde241b742a34710b7ce16337179/src/sentry/monitors/tasks.py#L182-L194

This logic only exists because when you leave the missed status number blank, it defaults to computing `next_expected` and `next_expected_latest` to be the SAME. You can see that here

https://github.com/getsentry/sentry/blob/774df5931d33dde241b742a34710b7ce16337179/src/sentry/monitors/models.py#L295-L301

So for example, if your check-in is expected at `12:00` and we run the task to find monitors that did not check-in on time, we will use `next_checkin_latest` which is equal to `12:00`. This is why we use `_lt` (less than), so this task waits until `12:01` to mark checkins that were supposed to happen at `12:00` as missed.

```
next_checkin = 12:00
next_checkin_latest = 12:00 

# Task is not run
task_run_time = 12:00
next_checkin_latest < task_run_time #false

# Task is run a minute later
task_run_time = 12:01
next_checkin_latest < task_run_time # true
```

Note that this is related to why https://github.com/getsentry/sentry/issues/54641 happens.

### The solution

`next_checkin_latest` needs to be the actual latest time you can check-in by.

Here's what I propose

1. The **minimum** you should be allowed to set your check-in missed time to should be `1 minute`. This should **also be the default** and should be reflected in the UI.
2. When computing the `next_checkin_latest` if the user did not configure a margin, **use 1 as the default** [[here](https://github.com/getsentry/sentry/blob/774df5931d33dde241b742a34710b7ce16337179/src/sentry/monitors/models.py#L295-L301)]
3. Update the logic which determines which monitors have missed checkins to use `lte` (less than or equal) [[here](https://github.com/getsentry/sentry/blob/774df5931d33dde241b742a34710b7ce16337179/src/sentry/monitors/tasks.py#L182-L194)]. The logic would now look like this

   ```
	next_checkin = 12:00
	next_checkin_latest = 12:01

    # Note that `next_checkin_latest` and `next_checkin` will never be 
    # equal in our data-model now.
	
	# Task is not run
	task_run_time = 12:00
	next_checkin_latest <= task_run_time #false
	
	# Task is run a minute later
	task_run_time = 12:01
	next_checkin_latest <= task_run_time # true
	```

### Implementation

This is a little bit tricky because we need to be careful not to update logic in such a way that everyone gets a single missed check-in when we switch from `lt` to `lte`.

```[tasklist]
### Deploy 1
- [ ] https://github.com/getsentry/sentry/pull/56704
- [ ] https://github.com/getsentry/sentry/pull/56533
```

```[tasklist]
### Deploy 2
- [ ] https://github.com/getsentry/sentry/pull/56635
```

```[tasklist]
### Deploy 3
- [ ] https://github.com/getsentry/sentry/pull/56527
- [ ] https://github.com/getsentry/sentry/pull/56634
- [ ] https://github.com/getsentry/sentry/pull/56887
- [ ] https://github.com/getsentry/sentry/pull/56767
```

This includes implementing temporary logic to avoid the condition where a user's monitor had an equal `next_expected` and `next_expected_latest` to avoid their monitor being immediately marked as missed because `_lte` would include the monitor the moment the checkin window starts. We can detect this and add `1` to the `next_expected_latest` to have the same behavior as what exists

If we find that monitors exist with a `next_expected` far in the future and we do not want to leave the temporary logic around, we can also write a migration to handle this after the fact.

**Comment by evanpurkhiser** [comment]
This is complete 💯
