### ISSUE TITLE
Preparations for replicating existing dashboard

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#56847]
We'd like to completely replicate an existing dashboard we're using with DDM. The goal of this issue is to make all the preparation work that's needed.

```[tasklist]
### Tasks
- [x] Pick the dashboard that we'd like to replicate with DDM
- [x] Start extracting metrics in that dashboard so that we have historical data
- [x] Collect and document features that would be required to make this dashboard and are missing today (e.g. multiple queries, equations, smoothening, customizing colors, table view)
```

**Comment by iambriccardo** [comment]
The document containing the findings is available here -> https://www.notion.so/sentry/Dashboards-to-Migrate-090483f2603e4886992256af02bace1e
