### ISSUE TITLE
[Milestone] Optional Product Improvements

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#56857]
This is a running backlog of product issues that are not crucial for the 6-week sprint but would be nice to get fixed/implemented eventually.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/56905
- [ ] https://github.com/getsentry/sentry/issues/56906
- [ ] https://github.com/getsentry/sentry/issues/56907
- [ ] https://github.com/getsentry/sentry/issues/56908
- [ ] https://github.com/getsentry/sentry/issues/56740
- [ ] https://github.com/getsentry/sentry/issues/56909
- [ ] https://github.com/getsentry/sentry/issues/56999
- [ ] https://github.com/getsentry/sentry/issues/57000
- [ ] https://github.com/getsentry/sentry/issues/57001
- [ ] https://github.com/getsentry/sentry/issues/56945
- [ ] https://github.com/getsentry/sentry/issues/56918
- [ ] https://github.com/getsentry/sentry/issues/57063
- [ ] https://github.com/getsentry/sentry/issues/57102
- [ ] https://github.com/getsentry/sentry/issues/57073
- [x] rendering more than one widget component (+ changing the url format) + changing the display to be per widget + adding a basic recall feature with local storage
- [x] Fix `instrument.js:122 TypeError: Cannot read properties of undefined (reading 'unit')
- [ ] https://github.com/getsentry/sentry/issues/57554
- [ ] Explore button - Go to performance/starfish with same filters (project,time, env, etc.)
- [ ] Metric autocompletion should show only metrics that happened in the timeframe (or always last 30d?)
- [ ] Add support for equations
- [ ] Customization of series colors
- [ ] https://github.com/getsentry/sentry/issues/57965
- [ ] Table view
- [ ] https://github.com/getsentry/sentry/issues/56919
- [ ] Display matching transactions/releases underneath the explorer
- [ ] https://github.com/getsentry/sentry/issues/57014
- [ ] Consider preselecting environment by default to reduce noise from canaries
- [ ] Make it nice on the phone
- [ ] https://github.com/getsentry/sentry/issues/57011
- [ ] https://github.com/getsentry/sentry/issues/57555
- [ ] https://github.com/getsentry/sentry/issues/57556
- [ ] https://github.com/getsentry/sentry/issues/57202
- [ ] https://github.com/getsentry/sentry/issues/57557
- [ ] https://github.com/getsentry/sentry/issues/57450
- [ ] The ability to hide one series (we only have hide all except this)
- [ ] https://github.com/getsentry/sentry/issues/57204
- [ ] https://github.com/getsentry/sentry/issues/57268
- [ ] https://github.com/getsentry/sentry/issues/57269
- [ ] https://github.com/getsentry/sentry/issues/57558
- [ ] https://github.com/getsentry/sentry/issues/57451
- [ ] DDM headers are too chunky on mbp
- [ ] on a smaller screen, when the selectors start to go on a second row, they can end up in various positions. think it would be nice to have a horizontal separator line as well, so it’s a bit clearer?
- [ ] it would be cool to have a way to remove widgets. I just clicked and created a bunch of meaningless ones, but since we’re persisting them I can’t “clean them up” without starting from scratch :grimacing: I’d suggest an “x” or the 3 dot menu we can also reuse for the “edit” function you wanted to add later to hide the selectors.
- [ ] https://github.com/getsentry/sentry/issues/57784
- [ ] would be good to be able to select the date range for each widget separately (but I also understand this might be slightly confusing)
- [x] The lines marking releases on a 30d window get kinda too dense to see anything
- [ ] https://github.com/getsentry/sentry/issues/57559
- [ ] https://github.com/getsentry/sentry/issues/57560
- [ ] https://github.com/getsentry/sentry/issues/57584
- [ ] https://github.com/getsentry/sentry/issues/57588
- [ ] Jan: global filters?
- [ ] https://github.com/getsentry/sentry/issues/57758
- [ ] https://github.com/getsentry/sentry/issues/57966
- [ ] When we are grouping by releases, we are hitting the 20groups limit and have holes in the data.
- [ ] https://github.com/getsentry/sentry/issues/57765
- [ ] https://github.com/getsentry/sentry/issues/57829
- [ ] rank metrics by usefulness and sort them by it in the selector
- [ ] https://github.com/getsentry/sentry/issues/57834
- [ ] Have an option to prefill half-empty charts with zeros - or connect distant datapoints with line?
- [ ] lyn: Click "DDM" and then "Add widget". Immediately get presented with this. I'm already a bit confused, Why is the metric box duplicated? (we might want to de-prioritize the add widget button)
- [ ] lyn: is there some weird bug where things are getting repainted/recalculated way more then it should even if i'm not changing the others? just click add widget (and pick any random metric) like 5 times.. then you will see when you add the next one that it slows right down
- [ ] lyn: how are you ensuring the charts stay below this number if everything is encoded in the URL? are you enforcing a max per page? also just curious how many of those charts do you load concurrently?
- [ ] lyn: i would love to write a comment about each one, we do that quite extensively on datadog to explain each metric inline so someone looking at it knows what to look for and what it means
- [ ] focus summary table row if you hover over chart group line
- [ ] vertical cursor line should be as wide as a bar in bar charts
- [ ] consider always focusing on only one series (also showing just one in tooltip)
- [ ] I was trying out the new layer and there is a 500 thrown by the server but this ends up not being shown in the UI and instead it remains blocked with the white loading overlay.
```

**Comment by matejminar** [comment]
Unfinished tasks were moved to https://github.com/getsentry/sentry/issues/59525
