### ISSUE TITLE
[Milestone] Internal Release

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#56936]
```[tasklist]
### Tasks
- [x] Deep Dive with EPD Leadership for demo & plan going forward
- [x] Shipped/Vanguard Post
- [x] Post in #discuss-product-announcements
- [x] Show & Tell Demo
- [x] Set up discussion channel for feedback
- [ ] Add DDM analytics
- [ ] Link to github discussion from DDM UI
- [x] Publish github discussion
- [x] Enable feature flag for more internal orgs (custom-metrics, ddm-ui)
- [ ] https://github.com/getsentry/sentry/issues/57012
- [ ] https://github.com/getsentry/sentry/issues/57758
- [ ] https://github.com/getsentry/sentry/issues/58576
- [ ] https://github.com/getsentry/sentry/issues/58577
- [ ] https://github.com/getsentry/sentry/issues/55984
- [ ] https://github.com/getsentry/sentry/issues/58571
```
