### ISSUE TITLE
Support new Issue states in Integration Platform webhooks

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry#57138]
### Problem Statement

Sentry has introduced new issue states: https://docs.sentry.io/product/issues/states-triage/ 

We now have New, Ongoing, Escalating, Archived, Resolved and Regressed states.

But the issue webhooks in our Integration platform don't reflect these changes: https://docs.sentry.io/product/integrations/integration-platform/webhooks/issues/

This hampers our integration partners from taking advantage of these enhancements- For eg. Linear can't automatically change ticket statuses when an issue regresses or escalates.

Please enhance state information in our webhooks

### Product Area

Settings - Integrations
```[tasklist]
### Tasks
- [x] Add event subsctiption for for issue.unresolved: distinguish between ongoing and regressed
- [x] Update docs
- [x] Update UI to reflect all the supported status
- [x] Add event subscription for issue.escalating
- [x] Script to update all existing webhooks to listen to new events
```

**Comment by gaiabeatrice** [comment]
I agree with this. We have a bunch of issues opened by Linear still marked as Resolved, even if they later regress.

In the beginning I assumed this was a bug, but it seems it is a new feature to request.

**Comment by Dhrumil-Sentry** [comment]
@gaiabeatrice is there any other issue state changes that you'd want a better sync for from Sentry to Linear? Any other feedback for this integration?

**Comment by gaiabeatrice** [comment]
I think I would love the bidirectional update between Sentry and Linear statuses, so if a change is made in Sentry, it reflects in Linear and vice versa.

No other feedback that comes to mind right now, but I will let you know!

**Comment by sobeslavsky** [comment]
As a Sentry customer I can just add that we have already missed critical production alerts due to this issue.

Pleae note that the page where we configure alerts creates an impression that alerting on regression is supported:

<img width="957" alt="image" src="https://github.com/getsentry/sentry/assets/3476434/81d52fa2-70dd-4f07-aa34-6360fe7e728a">

We only found out after investigating missing alerts and contacting Sentry support that this feature actually does not work and that we are at risk of missing alerts from regressed issues.

**Comment by Dhrumil-Sentry** [comment]
@sobeslavsky Thanks for sharing this feedback, At the very least we should give a warning on the alert rule when a trigger and action don't work together. 

cc @rachrwang @leedongwei

**Comment by sentaur-athena** [comment]
The issue got autoclosed by mistake. Still working on it.

**Comment by sentaur-athena** [comment]
This is completed. I will launch tomorrow morning.
