### ISSUE TITLE
Adding Dead/Rage clicks counts to the details header

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#57271]
### Problem
It's hard to quickly see all dead and or rage clicks within a given replay
### Acceptance Criteria

```[tasklist]
### Tasks
- [x] Users can see a count of dead clicks
- [x] Users can see a count of rage clicks
- [x] Users can click the count of either dead and rage clicks, and it filters the breadcrumb view to those respective breadcrumb types
```

### Designs
![Image](https://github.com/getsentry/sentry/assets/6508377/1e32d6f8-2ef9-4d6e-9678-8bbe98e3c550)

### Blocked by
[57270](https://github.com/getsentry/sentry/issues/57270)
