### ISSUE TITLE
[Epic] Improving Suspect Commits 🔎

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#57293]
Suspect commits are an important and useful feature for many users, but there are some problems with the current iteration. First, code mappings (which are required) are difficult to setup, especially for native platforms which are not fully documented. For projects that _do_ have code mappings setup, the majority of issues still do not have a suspect commit. This means there is a large opportunity to improve the coverage of this feature. Additionally, user feedback suggests that when suspect commits are present, the selected commit/author is often not the true source of the issue. We can expand the number and quality of suspect commits by searching more files of the stack trace for recent commits.

[Internal Product Doc](https://www.notion.so/sentry/Improving-Suspect-Commits-84a3f0e891ac4e0b98b1a5d54d0adbde)
[Internal Tech Spec
](https://www.notion.so/sentry/Tech-Spec-Improving-Suspect-Commits-By-Searching-More-Files-f536768b35f74aeba92eb9143d630f19#53e6b9f32c49475f8ae60ab6b94a3bbe)[GH Discussion](https://github.com/getsentry/sentry/discussions/47522)

```[tasklist]
### Docs updates
- [ ] https://github.com/getsentry/sentry/issues/54764
- [ ] https://github.com/getsentry/sentry/pull/57879
```

```[tasklist]
### Improve accuracy by searching more files
- [ ] https://github.com/getsentry/sentry/issues/57434
- [ ] https://github.com/getsentry/sentry/issues/57433
- [ ] https://github.com/getsentry/sentry/issues/57438
- [ ] https://github.com/getsentry/sentry/issues/57836
- [ ] https://github.com/getsentry/sentry/issues/58253
- [ ] https://github.com/getsentry/sentry/issues/59446
- [ ] https://github.com/getsentry/sentry/issues/59351
```

```[tasklist]
### Managing rate limits
- [ ] https://github.com/getsentry/sentry/issues/57431
- [ ] https://github.com/getsentry/sentry/issues/57430
- [ ] https://github.com/getsentry/sentry/issues/57437
```
