### ISSUE TITLE
SDK Crash Detection: Make it extendable

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry#57542]
### Problem Statement

Make the SDK crash detection extendable for multiple platforms. The plan is that every SDK has to define a subclass SDKCrashDetector to get SDK crash detection up and running. 

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/58578
- [ ] https://github.com/getsentry/sentry/pull/59078
- [ ] https://github.com/getsentry/sentry/pull/59080
- [ ] https://github.com/getsentry/sentry/pull/59082
- [ ] https://github.com/getsentry/sentry/pull/59083
- [ ] https://github.com/getsentry/sentry/pull/59084
- [ ] https://github.com/getsentry/sentry/pull/59256
- [ ] https://github.com/getsentry/sentry/pull/59257
```

**Comment by philipphofmann** [comment]
All PRs / issues for this task are complete. We can close this.
