### ISSUE TITLE
[Epic] Participant Purge :skull:

### ISSUE THREAD

**Issue by ceorourke** [getsentry/sentry#57715]
[Product Spec](https://www.notion.so/sentry/Up-to-date-Issue-Participants-eff59f2a9ad24b92a740a4d5672314e3#e6a70290f9784d55b6d7f08eb2b4a79a)

```[tasklist]
- [ ] https://github.com/getsentry/sentry/issues/57719
- [ ] https://github.com/getsentry/sentry/issues/57720
- [ ] https://github.com/getsentry/sentry/issues/57725
- [ ] https://github.com/getsentry/sentry/issues/57721
- [ ] https://github.com/getsentry/sentry/issues/57722
- [ ] https://github.com/getsentry/sentry/issues/57723
- [ ] https://github.com/getsentry/sentry/issues/57724
```
