### ISSUE TITLE
[EPIC] Generic Inbound Filters

### ISSUE THREAD

**Issue by iambriccardo** [getsentry/sentry#57799]
# Problem

The inbound filters configuration is currently quite limited, since it's based on a pre-defined set of filters, that are defined statically in both Sentry and Relay. Such manual configuration is a tedious process and is quite limited, since it requires quite a lot of manual work to satisfy even the simplest of constraints.

An example of inbound filters config:
```
"filterSettings": {
  "legacyBrowsers": {
    "isEnabled": true,
    "options": [
    "ie_pre_9",
    "safari_pre_6",
    "opera_pre_15",
    "ie9",
    "ie10",
    "android_pre_4",
    "ie11",
    "opera_mini_pre_8"
    ]
  },
  "webCrawlers": {
    "isEnabled": true
  },
},
```

# Possible Solution

Relay offers a DSL for matching incoming events which is now used in both dynamic sampling and metric extraction. Such DSL enables developers to express composite conditions on the incoming event's payload, which can already satisfy a lot of existing matching logic implemented for inbound filters. 

The idea would be to introduce a new `generic` field that will contain key-value pairs of inbound filters and their condition for filtering. _For efficiency reasons the definition of rules could leverage the new global config system of Relay and just propagate the active status as project scoped configuration._

The implementation of inbound filters could look something like:
```
"filterSettings": {
  # All non-generic filters are expressed like before for backwards compatibility.
  "legacyBrowsers": {
    "isEnabled": true,
    "options": [
    "ie_pre_9",
    "safari_pre_6",
    "opera_pre_15",
    "ie9",
    "ie10",
    "android_pre_4",
    "ie11",
    "opera_mini_pre_8"
    ]
  },
  "webCrawlers": {
    "isEnabled": true
  },
  # Here all the generic inbound filters should go.
  “generic”: {
  		“hydrationErrors”: {
  			“condition”: # ds condition,
  			“isEnabled”: true
  		}
  	}
},
```

_Such a new configuration will be backward compatible by having Sentry generate inbound filters with both DSLs for a fixed amount of time. After that time the old configuration will be faded out resulting in old custom Relays not inbound filtering._

# Work To Do

```[tasklist]
- [ ] https://github.com/getsentry/sentry/issues/57962
- [ ] https://github.com/getsentry/relay/pull/3161
- [ ] https://github.com/getsentry/sentry/pull/66134
- [ ] https://github.com/getsentry/sentry/pull/66401
- [ ] https://github.com/getsentry/sentry/pull/66410
- [ ] https://github.com/getsentry/sentry/issues/57803
```

**Comment by jjbayer** [comment]
Remaining steps depend on https://github.com/getsentry/relay/issues/2584: When the filter config moves to global config, we cannot apply filters as long as global config is not yet loaded.

**Comment by bruno-garcia** [comment]
Related: Replay customers currently suffer from issues when sampling *OnError* replays and inbound filters drop the event that triggers the replay to start:

* https://github.com/getsentry/sentry/issues/44700

**Comment by jernejstrasner** [comment]
This work is on the Ingest plate. We're all busy with metrics but the config merge part we will do asap. It could get done in the next couple of weeks but we'll keep you posted.
After that you all can then add whichever filters you need.
How does this sound @sentaur-athena ?

**Comment by sentaur-athena** [comment]
@jernejstrasner sounds good. Since the partner need this faster and we don't want to get your focus away from metrics work either, I will write private documentation for them to use the Project Update Endpoint meanwhile. When we do the refactory, before re-moving the inbound filter from projects endpoint we should make sure to let them know to move to the new solution.

@iambriccardo I will send over the doc to you to review before sending to them. Thank you.

**Comment by sentaur-athena** [comment]
@jernejstrasner to be clear, is the work that is on ingest plate moving all filters out of project details endpoint and to a filters endpoint?
Would be great to have timelines when you have them and make sure we're all aligned on a rollout plan. Appreciate it.

**Comment by jjbayer** [comment]
@sentaur-athena creating a new sentry API endpoint for inbound filters is out of scope for this epic IMO, because it's a different concern (API <-> client communication vs. sentry <-> relay communication).
