### ISSUE TITLE
Platform Icons suck in dark mode

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#58147]
### Problem
Read the title

### Acceptance Criteria
No matter the theme, the svg graphics are visible
```[tasklist]
### Tasks
- [x] Node
- [x] Serverless Category (AWS, Google Cloud, Azure Functions, Serverless)
- [x] Desktop Category (Mac OS, .NET Java etc.)
- [x] Mobile Category (Android iOS, React Native etc.
- [x] Javascript
- [x] Server Category (The rest)
```

**Comment by Jesse-Box** [comment]
Relates to 
* https://github.com/getsentry/sentry/issues/57749

**Comment by Jesse-Box** [comment]
Marking this as done
