### ISSUE TITLE
Notify users with transaction alerts

### ISSUE THREAD

**Issue by obostjancic** [getsentry/sentry#58141]
We need a way (email) to notify users that have alerts that will be impacted by migration (AM2 orgs with transaction alerts and dynamic sampling). It should be an entrypoint that takes users to migration UI
```[tasklist]
### Tasks
- [x] Give a heads up to support before sending out email
- [ ] https://github.com/getsentry/sentry/issues/58987
- [ ] https://github.com/getsentry/sentry/issues/59408
```
