### ISSUE TITLE
[Epic] Team Workflow Notifications

### ISSUE THREAD

**Issue by jangjodi** [getsentry/sentry#58353]
Project Documents:
- [PRD](https://www.notion.so/sentry/Team-Workflow-Notifications-52b44756595a4f3fb8e7a227f6a131fe)
- [Tech spec](https://www.notion.so/sentry/Team-Workflow-Notifications-Tech-Spec-309f9446cb434c909b6c74d22ce7f357)

```[tasklist]
### Milestone 1
- [ ] https://github.com/getsentry/sentry/issues/58346
- [ ] https://github.com/getsentry/sentry/issues/58347
- [ ] https://github.com/getsentry/sentry/issues/58351
- [ ] https://github.com/getsentry/sentry/issues/58352
- [ ] https://github.com/getsentry/sentry/issues/58551
- [ ] https://github.com/getsentry/sentry/issues/58874
```

```[tasklist]
### Milestone 2
- [ ] https://github.com/getsentry/sentry/issues/58362
- [ ] https://github.com/getsentry/sentry/issues/58363
- [ ] https://github.com/getsentry/sentry/issues/58366
- [ ] https://github.com/getsentry/sentry/issues/58368
- [ ] https://github.com/getsentry/sentry/issues/58369
- [ ] https://github.com/getsentry/sentry/issues/58552
```

```[tasklist]
### Milestone 3
- [ ] https://github.com/getsentry/sentry/issues/58372
- [ ] https://github.com/getsentry/sentry/issues/58373
```
