### ISSUE TITLE
SDK Crash Detection: Enable React Native

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry#59263]
Enable React Native for the SDK Crash Detection.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/59261
- [ ] https://github.com/getsentry/sentry/pull/59407
- [ ] https://github.com/getsentry/sentry/pull/59515
- [ ] https://github.com/getsentry/sentry/pull/59601
- [ ] https://github.com/getsentry/sentry/pull/62990
- [ ] https://github.com/getsentry/sentry/pull/62991
- [ ] https://github.com/getsentry/sentry/pull/63005
- [ ] https://github.com/getsentry/sentry/pull/63009
- [ ] https://github.com/getsentry/sentry/pull/63226
- [ ] https://github.com/getsentry/sentry-options-automator/pull/586
- [ ] https://github.com/getsentry/sentry/pull/63582
- [ ] https://github.com/getsentry/sentry/pull/63817
- [ ] https://github.com/getsentry/sentry/pull/63833
```

**Comment by philipphofmann** [comment]
The SDK crash detection for RN is enabled at 100% sample rate. We can consider this as done.
