### ISSUE TITLE
[Milestone] Alerts Support

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#59512]
### Problem
Customers can create performance alerts today, but only based on OOTB metrics.

### Solution
Let users create alerts and potential issues based on custom metrics, with manually defined thresholds.

### Expected Outcome
We can migrate all application-level Datadog alerts to Sentry.

![Image](https://github.com/getsentry/sentry/assets/9060071/e696a1f4-dfd1-4b19-9378-2eed76867e6d)

### Notes
- we can only alert on single series (either no groupBys or we need specific filter)
- we need an action button on widget - for now we can put it wherever we want and core experience initiative will polish it
- when going from DDM we can have more than one project+env, alerts support only one
- when going from DDM we can have absolute timeselection, alerts support only predefined set of intervals
- replace existing measurements with MRIs
- hide the event type selector when configuring custom metrics alert
- project selection comes after the MRI selector, which should be the other way around
- figure out if we have own filter on alerts index page

```[tasklist]
### Phase I
- [ ] https://github.com/getsentry/sentry/issues/59826
- [ ] https://github.com/getsentry/sentry/issues/59822
- [ ] https://github.com/getsentry/sentry/issues/59823
- [ ] https://github.com/getsentry/sentry/issues/59824
- [ ] https://github.com/getsentry/sentry/issues/60248
- [ ] https://github.com/getsentry/sentry/issues/59516
- [ ] Ensure all relevant query builders support metrics
- [ ] Ensure that queries subscriptions work with metrics
- [ ] https://github.com/getsentry/sentry/issues/59613
- [ ] https://github.com/getsentry/sentry/issues/59831
- [ ] https://github.com/getsentry/sentry/issues/59832
- [ ] https://github.com/getsentry/sentry/issues/60090
- [ ] https://github.com/getsentry/sentry/issues/60092
- [ ] https://github.com/getsentry/sentry/issues/60093
- [ ] https://github.com/getsentry/sentry/issues/60166
- [ ] https://github.com/getsentry/sentry/issues/60352
- [ ] https://github.com/getsentry/sentry/issues/60353
- [ ] https://github.com/getsentry/sentry/issues/60354
- [ ] https://github.com/getsentry/sentry/issues/60381
- [ ] https://github.com/getsentry/sentry/issues/60382
- [ ] https://github.com/getsentry/sentry/issues/60575
```

```[tasklist]
### Phase II
- [ ] https://github.com/getsentry/sentry/issues/60249
- [ ] https://github.com/getsentry/sentry/issues/60380
- [ ] https://github.com/getsentry/sentry/issues/60572
- [ ] https://github.com/getsentry/sentry/issues/60573
- [ ] https://github.com/getsentry/sentry/issues/60574
- [ ] https://github.com/getsentry/sentry/issues/60576
- [ ] https://github.com/getsentry/sentry/issues/60577
- [ ] https://github.com/getsentry/sentry/issues/60578
```
