### ISSUE TITLE
[Milestone] Dashboards Support

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#59511]
### Problem
Scratchpads are a quick and easy way to get some analysis going, but some things you want to monitor on a regular basis.

### Proposed Solution
Enable customers to create/save metrics-based widgets in Dashboards.

### Expected Outcome
We can migrate all application-level Datadog dashboards to Sentry.

### Notes
- when exporting should we expose "raw" JSON or config of the widget?
- ddm right now does not support big number and table

![Image](https://github.com/getsentry/sentry/assets/9060071/073f4987-0d50-4fbb-9792-bc3888af44e6)

```[tasklist]
### Phase I
- [ ] https://github.com/getsentry/sentry/issues/59827
- [ ] https://github.com/getsentry/sentry/issues/59828
- [ ] https://github.com/getsentry/sentry/issues/59829
- [ ] https://github.com/getsentry/sentry/issues/60246
- [ ] https://github.com/getsentry/sentry/issues/60257
- [ ] https://github.com/getsentry/sentry/issues/60351
- [ ] https://github.com/getsentry/sentry/issues/60507
- [ ] https://github.com/getsentry/sentry/issues/60602
- [ ] https://github.com/getsentry/sentry/issues/60603
- [ ] https://github.com/getsentry/sentry/issues/60604
- [ ] https://github.com/getsentry/sentry/issues/60605
```

```[tasklist]
### Phase II (not happening now)
- [ ] Have a meeting about our strategy with original dashboards crew
- [ ] https://github.com/getsentry/sentry/issues/60247
- [ ] https://github.com/getsentry/sentry/issues/62538
- [ ] Aim for feature parity
- [x] Have one component type that's used in both scratchpads and dashboards
- [ ] Update Text in step 4 for custom metrics
- [ ] https://github.com/getsentry/sentry/issues/62539
- [ ] https://github.com/getsentry/sentry/issues/62540
- [ ] https://github.com/getsentry/sentry/issues/62541
```
