### ISSUE TITLE
[Milestone] Core Experience

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#59525]
```[tasklist]
### Cleaning
- [ ] https://github.com/getsentry/sentry/issues/62304
- [ ] https://github.com/getsentry/sentry/issues/62358
- [ ] https://github.com/getsentry/sentry/issues/62385
- [ ] https://github.com/getsentry/sentry/issues/62310
- [ ] https://github.com/getsentry/sentry/issues/62302
- [ ] https://github.com/getsentry/sentry/issues/62305
- [ ] https://github.com/getsentry/sentry/issues/62313
- [ ] https://github.com/getsentry/sentry/issues/62307
- [x] figure out nulti widget experience (two columns?, horizontal scroll?)
- [ ] https://github.com/getsentry/sentry/issues/62301
- [ ] https://github.com/getsentry/sentry/issues/62380
- [ ] https://github.com/getsentry/sentry/issues/62359
- [ ] https://github.com/getsentry/sentry/issues/62382
- [ ] https://github.com/getsentry/sentry/issues/62363
- [ ] https://github.com/getsentry/sentry/issues/62362
- [ ] https://github.com/getsentry/sentry/issues/62376
- [ ] https://github.com/getsentry/sentry/issues/62332
- [ ] https://github.com/getsentry/sentry/issues/61924
- [ ] https://github.com/getsentry/sentry/issues/62364
- [ ] https://github.com/getsentry/sentry/issues/62365
- [ ] https://github.com/getsentry/sentry/issues/62366
- [ ] https://github.com/getsentry/sentry/issues/62383
- [ ] https://github.com/getsentry/sentry/issues/62423
```

```[tasklist]
### Alignment
- [ ] https://github.com/getsentry/sentry/issues/62732
- [ ] https://github.com/getsentry/sentry/issues/62733
- [ ] https://github.com/getsentry/sentry/issues/62734
- [ ] https://github.com/getsentry/sentry/issues/62735
- [ ] https://github.com/getsentry/sentry/issues/62736
- [ ] https://github.com/getsentry/sentry/issues/62737
- [ ] https://github.com/getsentry/sentry/issues/62738
```

```[tasklist]
### Other
- [ ] https://github.com/getsentry/sentry/issues/59701
- [ ] https://github.com/getsentry/sentry/issues/59702
- [ ] https://github.com/getsentry/sentry/issues/57011
- [ ] https://github.com/getsentry/sentry/issues/59704
- [ ] https://github.com/getsentry/sentry/issues/59697
- [ ] https://github.com/getsentry/sentry/issues/59708
- [ ] https://github.com/getsentry/sentry/issues/59705
- [ ] https://github.com/getsentry/sentry/issues/57555
- [ ] https://github.com/getsentry/sentry/issues/57965
- [ ] https://github.com/getsentry/sentry/issues/59711
- [ ] https://github.com/getsentry/sentry/issues/59713
- [ ] https://github.com/getsentry/sentry/issues/59712
- [ ] https://github.com/getsentry/sentry/issues/59717
- [ ] https://github.com/getsentry/sentry/issues/57450
- [ ] https://github.com/getsentry/sentry/issues/59714
- [ ] https://github.com/getsentry/sentry/issues/59715
- [ ] https://github.com/getsentry/sentry/issues/59694
- [ ] https://github.com/getsentry/sentry/issues/59696
- [ ] https://github.com/getsentry/sentry/issues/59698
- [ ] https://github.com/getsentry/sentry/issues/59699
- [ ] https://github.com/getsentry/sentry/issues/59703
- [ ] https://github.com/getsentry/sentry/issues/59706
- [ ] https://github.com/getsentry/sentry/issues/59709
- [ ] https://github.com/getsentry/sentry/issues/59710
- [ ] Explore button - Go to performance/starfish with same filters (project,time, env, etc.)
- [ ] Metric autocompletion should show only metrics that happened in the timeframe (or always last 30d?)
- [ ] Add support for equations
- [ ] Customization of series colors
- [ ] Table view
- [ ] Consider preselecting environment by default to reduce noise from canaries
- [ ] Make it nice on the phone
- [ ] https://github.com/getsentry/sentry/issues/63599
- [x] DDM headers are too chunky on mbp
- [x] on a smaller screen, when the selectors start to go on a second row, they can end up in various positions. think it would be nice to have a horizontal separator line as well, so it’s a bit clearer?
- [ ] Jan: global filters?
- [ ] rank metrics by usefulness and sort them by it in the selector
- [x] lyn: Click "DDM" and then "Add widget". Immediately get presented with this. I'm already a bit confused, Why is the metric box duplicated? (we might want to de-prioritize the add widget button)
- [x] lyn: is there some weird bug where things are getting repainted/recalculated way more then it should even if i'm not changing the others? just click add widget (and pick any random metric) like 5 times.. then you will see when you add the next one that it slows right down
- [x] lyn: how are you ensuring the charts stay below this number if everything is encoded in the URL? are you enforcing a max per page? also just curious how many of those charts do you load concurrently?
- [ ] focus summary table row if you hover over chart group line
- [ ] consider always focusing on only one series (also showing just one in tooltip)
- [x] I was trying out the new layer and there is a 500 thrown by the server but this ends up not being shown in the UI and instead it remains blocked with the white loading overlay.
- [ ] Add instrumentation to DDM (how many widgets are people creating per scratchpad, how many alerts, dashboards, etc.)
- [ ] https://github.com/getsentry/sentry/issues/60250
- [x] The headers are misaligned when you select something and the other widget is empty
- [ ] https://github.com/getsentry/sentry/issues/60256
- [ ] https://github.com/getsentry/sentry/issues/60585
- [ ] https://github.com/getsentry/sentry/issues/60789
- [ ] https://github.com/getsentry/sentry/pull/60543
- [ ] https://github.com/getsentry/sentry/issues/60586
- [ ] Make it possible to query multiple use cases at once from api
- [ ] https://github.com/getsentry/sentry/issues/60608
- [ ] https://github.com/getsentry/sentry/issues/61345
- [ ] https://github.com/getsentry/sentry/issues/62417
- [ ] https://github.com/getsentry/sentry/issues/62537
- [ ] https://github.com/getsentry/sentry/issues/62672
```

Q4 prios:
- no data experience (getting started product banners)
- missing data points experience (either zero-fill, connect existing data points with a different line, etc.)
- performance of charts/tables
- stabilize/production metrics API
- chart color palettes
- fix chunky headers
- go from widget to metrics settings
