### ISSUE TITLE
[Epic] Q4 Grouping Improvements (WIP)

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/sentry#59731]
All project documents linked in the project's [Notion page](https://www.notion.so/sentry/Grouping-5cf2cbf117a24235a85cd7faea95ef74?pvs=4)

### Optimizing config transitions

Tech spec: https://www.notion.so/sentry/Tech-Spec-Optimizing-transitions-between-grouping-configs-39e562cf8bec4aefaa79bbbd320b4aec?pvs=4
Tracking issue: https://github.com/getsentry/sentry/issues/61661

### Changing how we store grouping rules

Tech spec: https://www.notion.so/sentry/Spec-for-Storing-Grouping-Rules-in-DB-43db5fcf485c4f4f9232085603fad350?pvs=4

### Miscellaneous tasks
- [ ] [Tag metrics with SDK info](https://github.com/getsentry/sentry/issues/59746) (to be able to see how often nextjs issues get merged)  - see issue for individual tasks
- [ ] [Fix alerting in project channel](https://github.com/getsentry/sentry/issues/60996)
- [ ] [Remove hierarchical hashing code](https://github.com/getsentry/sentry/issues/61641)
