### ISSUE TITLE
[Epic] Severity-Based Alerts

### ISSUE THREAD

**Issue by ceorourke** [getsentry/sentry#59868]
[Severity Alerts Product Spec](https://www.notion.so/sentry/Severity-based-Notifications-5190df47141b47c796eb143b0171623b)

[Severity Alerts Tech Spec](https://www.notion.so/sentry/Release-Severity-Tech-Spec-df83dc1696424075bd3a0ba2e565d916)

```[tasklist]
### EA
- [ ] https://github.com/getsentry/sentry/issues/66334
- [ ] https://github.com/getsentry/sentry/issues/66335
- [ ] https://github.com/getsentry/sentry/issues/66336
- [ ] https://github.com/getsentry/sentry/issues/66338
- [ ] https://github.com/getsentry/sentry/issues/66337
```

### New to Escalating
```[tasklist]
- [ ] https://github.com/getsentry/sentry/issues/60057
- [ ] https://github.com/getsentry/sentry/issues/60415
- [ ] https://github.com/getsentry/sentry/issues/60413
- [ ] https://github.com/getsentry/sentry/issues/60418
```

### Alerts
```[tasklist]
- [ ] https://github.com/getsentry/sentry/issues/59872
- [ ] https://github.com/getsentry/sentry/issues/59957
```
```[tasklist]
### Bug Fixes
- [ ] https://github.com/getsentry/sentry/issues/61816
- [ ] https://github.com/getsentry/sentry/issues/61817
```

```[tasklist]
### Release Process
- [x] Send email before LA
- [x] Convert org alerts for LA
- [x] Send confirmation email after alerts are converted
```

**Comment by Angelodaniel** [comment]
Hey @ceorourke, do I understand that it would be possible to trigger alerts from Alerts that are Escalating.
And not just from Archived to Escalated but also New / Ongoing -> Escalating?

**Comment by ceorourke** [comment]
@Angelodaniel new -> escalating yes, ongoing -> escalating is not planned for this, but I've heard it might be in a future project.
