### ISSUE TITLE
[Milestone] Productionize DDM and add guardrails

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry#59893]
```[tasklist]
### LA Requirements
- [ ] https://github.com/getsentry/sentry/issues/58576
- [x] Scaling: https://github.com/orgs/getsentry/projects/180/views/4
- [x] Rust Consumers: https://getsentry.atlassian.net/browse/SNS-2424
- [ ] https://github.com/getsentry/team-ingest/issues/256
- [ ] https://github.com/getsentry/relay/issues/2717
```
