### ISSUE TITLE
[Milestone] Use New Metrics Layer

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#60086]
The goal of this milestone is that DDM and /metrics APIs use the [new metrics layer](https://www.notion.so/sentry/Metrics-Query-Layer-91fc5a1e11274019a0d51985f7f91892) fully and completely.

3S tasks needed for this milestone to finish are specified here:
https://www.notion.so/sentry/New-Metrics-Layer-Feedback-616ead65900d49d7949e5b7d72ac1c61

```[tasklist]
### Major Blockers for DDM Usage
- [ ] https://github.com/getsentry/sentry/issues/60685
- [ ] https://github.com/getsentry/sentry/issues/60167
- [ ] https://github.com/getsentry/sentry/issues/59774
```

```[tasklist]
### Minor DDM Usage Concerns
- [ ] https://github.com/getsentry/sentry/issues/62465
- [ ] https://github.com/getsentry/sentry/issues/60785
- [ ] https://github.com/getsentry/sentry/issues/62466
```

```[tasklist]
### Nice to Haves
- [ ] https://github.com/getsentry/sentry/issues/61832
- [ ] https://github.com/getsentry/sentry/issues/61591
- [ ] https://github.com/getsentry/sentry/issues/60686
- [ ] https://github.com/getsentry/sentry/issues/60084
- [ ] https://github.com/getsentry/sentry/issues/59597
- [ ] https://github.com/getsentry/sentry/issues/59817
```

_Major blockers are needed in order to fulfill the basic DDM usage, whereas minor blockers are still blocking DDM but only a subset of features._
