### ISSUE TITLE
[Epic] User Feedback

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#60114]
Continuation of https://github.com/getsentry/team-replay/issues/273

```[tasklist]
### Short-term & quick tasks
- [ ] https://github.com/getsentry/sentry/issues/62793
- [ ] https://github.com/getsentry/sentry/issues/61768
- [ ] https://github.com/getsentry/sentry/issues/64697
- [ ] https://github.com/getsentry/sentry/pull/59641
- [ ] https://github.com/getsentry/sentry/issues/61313
- [ ] https://github.com/getsentry/sentry/issues/62792
- [ ] https://github.com/getsentry/team-replay/issues/293
- [ ] https://github.com/getsentry/sentry/issues/60697
- [ ] https://github.com/getsentry/sentry/issues/62707
- [ ] https://github.com/getsentry/sentry-docs/issues/8752
- [ ] https://github.com/getsentry/sentry/issues/64698
- [ ] https://github.com/getsentry/sentry/issues/64699
- [ ] https://github.com/getsentry/sentry/issues/64700
- [ ] https://github.com/getsentry/sentry/issues/64701
- [ ] https://github.com/getsentry/sentry/issues/64702
```

```[tasklist]
### Mid-term & optional tasks
- [ ] https://github.com/getsentry/sentry/issues/61372
- [x] Emit outcomes for feedback
- [ ] https://github.com/getsentry/sentry/issues/64703
- [ ] https://github.com/getsentry/sentry/issues/60113
- [ ] https://github.com/getsentry/sentry/issues/64704
- [ ] https://github.com/getsentry/sentry/issues/60978
- [ ] https://github.com/getsentry/sentry/issues/61767
- [ ] https://github.com/getsentry/sentry/issues/60941
- [ ] https://github.com/getsentry/sentry/issues/63438
- [ ] https://github.com/getsentry/sentry/issues/64705
```

```[tasklist]
### Long-term ideas and future projects
- [ ] https://github.com/getsentry/sentry-javascript/issues/9460
- [ ] https://github.com/getsentry/sentry/issues/62893
- [ ] https://github.com/getsentry/sentry/issues/62172
- [ ] https://github.com/getsentry/sentry/issues/64706
```

```[tasklist]
### Questions & Open-ended discussions
- [ ] https://github.com/getsentry/team-replay/issues/328
- [x] Discussion around Pricing
- [x] Discussion around filtering Feedback (so we surface high quality feedbacks)
- [x] Discussion around Merging and Grouping of Feedbacks
```

**Comment by bruno-garcia** [comment]
With the goal of improving "debugging context" on feedbacks:
* https://github.com/getsentry/sentry-javascript/issues/10526

**Comment by ryan953** [comment]
Closing. This was always an incomplete list of backlog items for user feedback. Instead of maintaining the list we have the project board to look at.

**Comment by bruno-garcia** [comment]
> This was always an incomplete list of backlog items for user feedback

Originally this tracked what we wanted for GA.
<img width="715" alt="image" src="https://github.com/getsentry/sentry/assets/1633368/ce05a465-3da7-44fd-a3fa-49db12651f37">

Recently work on that scope happened outside of this ticket and new tickets were created and things copied out of here.

**Comment by bruno-garcia** [comment]
GA milestone tracked:

* https://github.com/getsentry/sentry/issues/64671
