### ISSUE TITLE
[Epic] Prevent logging from causing outages in Prod (INC-564)

### ISSUE THREAD

**Issue by vartec** [getsentry/sentry#60225]
Errors occurring during logging should not cause unhandled errors, but rather be ignored when in Production. 
These errors should still be surfaced in non-production environments. 

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/60224
- [ ] https://github.com/getsentry/sentry/issues/60227
- [ ] https://github.com/getsentry/sentry/issues/60229
- [ ] https://github.com/getsentry/sentry/issues/60890
```

**Comment by vartec** [comment]
- https://github.com/getsentry/sentry/pull/60131 resolves https://github.com/getsentry/sentry/issues/60224
- https://github.com/getsentry/sentry/issues/60227 cannot feasibly be done without performance impac
- https://github.com/getsentry/sentry/issues/60229 has been deemed as not necessary
