### ISSUE TITLE
[Milestone] Metrics Meta Data

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry#60260]
DDM wants to show code locations with metrics. This is semi-static information, in that it changes infrequently between deploys, but doesn't need to be reported with every data point. 

**Feature Set:**
- Code Location
- (optional) Descriptions
- (potentially) Cached span flag

# PoC

Goals:
 1. Estimate cost scaling
 2. SDK protocol + impl in Py
 3. Transient storage
 4. Expose in products

Constraints:
- Multiple locations per metric possible
- Concept of time (esp for endpoint)
- No explicit release-support, no location per tag
- No symbolication yet, but consider it for future
- Debouncing doesn't have to be persistent (ie. not survive restarts)

```[tasklist]
### Stage 1: PoC
- [ ] Envelope Item + protocol
- [ ] Define what is stored for locations
- [ ] SDK implementation with debouncing
- [ ] Support parent locations (required for Sentry)
- [ ] Relay: Ingestion
- [ ] Relay: Store in Redis
- [ ] Create an API to query Redis from Sentry
- [ ] Update UI to show code locations
- [ ] Compare projects from S4S and SaaS
```

# Productionize

TBD
