### ISSUE TITLE
[Milestone] Configuration and Visibility

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#60263]
## Problems we're solving
- visibility: give DDM customers visibility onto which metrics and tags are being ingested (will become more important also for cost control once we start charging)
- addressing PII concerns: allow users to delete existing stored metrics data
- “blocking” rogue metrics: ability to stop future ingestion of a specific metric or ignore certain tags
- surfacing cardinality limits: customers need to know when this is happening and which metrics are affected 

# Product Requirements

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/60583
```

```[tasklist]
### Metrics visibility
- [ ] https://github.com/getsentry/sentry/issues/60764
- [ ] https://github.com/getsentry/sentry/issues/60765
- [ ] https://github.com/getsentry/sentry/issues/60766
- [ ] https://github.com/getsentry/sentry/issues/60768
```

```[tasklist]
### Block / delete metrics
- [ ] https://github.com/getsentry/relay/pull/2954
- [ ] https://github.com/getsentry/sentry/issues/60860
- [ ] https://github.com/getsentry/sentry/issues/60769
```

# Post-Launch Improvements (stretch)

The following milestone depends on metric-based cardinality limits. We'll link the corresponding initiative here.

```[tasklist]
### Cardinality
- [ ] https://github.com/getsentry/sentry/issues/60772
- [ ] https://github.com/getsentry/sentry/issues/60773
- [ ] https://github.com/getsentry/sentry/issues/60309
- [ ] (optional) show which metrics have been cardinality limited
```

```[tasklist]
### Tag visibility / manangement
- [ ] https://github.com/getsentry/sentry/issues/60770
- [ ] https://github.com/getsentry/sentry/issues/60862
- [ ] https://github.com/getsentry/sentry/issues/60771
- [ ] https://github.com/getsentry/relay/issues/2797
```

```[tasklist]
### Other
- [ ] https://github.com/getsentry/sentry/issues/60767
- [ ] update last seen even for blocked metrics
```
