### ISSUE TITLE
Alerts - Support ignoring archived issues in metric alerts (ui)

### ISSUE THREAD

**Issue by scttcper** [getsentry/sentry#60439]
https://www.notion.so/sentry/Metric-alerts-Ignoring-Archived-Issues-8b5ce2b77a084256bda3591394372a14?pvs=4#51ce2e7fef7a483cb652818d7c5ca7a0

```[tasklist]
### Tasks
- [x] Create a migration flow to opt users into filtering their metric alerts with a banner on the details page that takes them to the edit page https://github.com/getsentry/sentry/pull/60232
- [x] Dismiss the banner for a user https://github.com/getsentry/sentry/pull/60232
- [x] Dismiss the banner when date created or date modified > reaturerelease date https://github.com/getsentry/sentry/pull/61330
- [x] Add the filter by default to new error metric alerts https://github.com/getsentry/sentry/pull/60433
- [x] Add the status/is tag to the query autocomplete https://github.com/getsentry/sentry/pull/60441
- [ ] Set `dataset=errors` when filtering by status in discover
```
