### ISSUE TITLE
Deploy & Test

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#60580]
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-options-automator/pull/461
- [ ] https://github.com/getsentry/sentry-options-automator/pull/463
- [ ] https://github.com/getsentry/getsentry/pull/12160
- [x] Add redis metrics to Minimetrics dashboard
- [x] Verify code locations in UI
```
