### ISSUE TITLE
Improve code location rendering

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry#60684]
```[tasklist]
### Tasks
- [ ] Show a platform icon next to the location
- [x] Fix font rendering (should not be monospaced)
- [x] Copy to clipboard (in format `path:lineno`)
- [x] Show latest location (last in list)
- [x] Show source context where available, behind toggle
- [x] Collect up to 5 distinct entries from past timestamps
- [ ] https://github.com/getsentry/sentry/pull/60883
```
