### ISSUE TITLE
[Epic] Replay Index Zero-State

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#60793]
The goal of the project is to see more organizations setting up Replay for the first time via the Index page. See the [PRD Doc](https://www.notion.so/sentry/FY-24-Q4-Improve-the-Zero-State-Experience-of-the-Replay-Index-b599ac581c7c43358219aca507822056) for details.

[KTTR Tracking](https://www.notion.so/sentry/Improve-the-Zero-state-Experience-006a8e68662e4241856d59c06f3f93b5)
Feature flag: `organizations:session-replay-new-zero-state`

**Problem Statements:**
1. The Replay in-app onboarding provides a misleading/confusing message for web backend projects. Additionally, it’s not clear what SDKs are supported.
2. Our Replay Index page doesn’t sufficiently communicate the value of the Replay product and relies on the user to click through to our set up docs site to learn more, which is similar to the information they would see in the onboarding fly-out tray.
3. Our Replay Index does not provide any guidance or information on some common objections users have to installing Replay. This requires the user to seek out this information themselves from our docs/blog post, but most will just not use the product.
4. Many projects are on old JS SDK versions not eligible for Session Replay, they must upgrade their SDK version before they can use the product. 

### Figma Files:
- [Userflow (FigJam)](https://www.figma.com/file/DZOMcbl7iU3WBSrKtREEPB/Exploration%3A-Onboarding-v3?type=whiteboard&node-id=0-1&t=Li42MsvKtws0iYqA-0)
- [UI](https://www.figma.com/file/ltrSBJHvlz0TB1b96vlEtn/Specs%3A-Onboarding-v3?type=design&node-id=103-1243&mode=design&t=SVfHJiPXVMiOeDsY-0)

```[tasklist]
### Sidebar Revamp
- [x] Create a remote feature-flag to wrap the zero-state ui changes
- [x] Docs for backbone? -> Answer: Not needed, I think they would be the same as the base @sentry/javascript docs. - Ryan
- [ ] https://github.com/getsentry/sentry/issues/61001
- [ ] https://github.com/getsentry/sentry/issues/61070
- [ ] https://github.com/getsentry/sentry/issues/61266
- [ ] https://github.com/getsentry/sentry/issues/61267
- [ ] https://github.com/getsentry/sentry/issues/61069
- [ ] https://github.com/getsentry/sentry/issues/61071
- [ ] https://github.com/getsentry/sentry/issues/62082
```

```[tasklist]
### Issue Details, Index Iteration, Sidebar Improvements
- [ ] https://github.com/getsentry/sentry/issues/61760
- [ ] https://github.com/getsentry/sentry/issues/61141
- [ ] https://github.com/getsentry/sentry/issues/62482
- [ ] https://github.com/getsentry/sentry/issues/62081
```

```[tasklist]
### Sample Replay
- [ ] https://github.com/getsentry/sentry/issues/60981
- [ ] https://github.com/getsentry/sentry/issues/61092
- [ ] https://github.com/getsentry/sentry/issues/63292
```

```[tasklist]
### Bugs
```

```[tasklist]
### Zero State GA
- [ ] https://github.com/getsentry/sentry/issues/63290
- [ ] https://github.com/getsentry/sentry/issues/63291
- [ ] Are we happy with the docs? https://docs.sentry.io/product/session-replay/getting-started/#supported-sdks
```
