### ISSUE TITLE
SDK Rate Limit Backoff for DDM

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry#61040]
As a failsafe, Sentry needs to communicate rate limit backoffs to SDKs so they stop sending `custom` metrics (DDM) to Sentry. 

### Initial Limitations

The only requirement is to enforce a general "drop all" limit for SDKs: a quota with static limit of `0`. Therefore, it is not required to define how metrics are being counted and instead the only required implementation is the fast-path in Relay.

### Spec

- The new data category will be defined in [**Develop Docs**](https://develop.sentry.dev/sdk/rate-limiting/#definitions)
- Counting of items is undefined as this point, Relays are permitted to count items/requests as one towards the rate limit.

```[tasklist]
### Tasks
- [ ] Specify data category for rate limit in develop docs
- [ ] Define how to count items in Relay
- [ ] https://github.com/getsentry/sentry-python/issues/2565
- [ ] Implement in JavaScript SDK
- [ ] Emit `x-sentry-rate-limits` header from Relay
```

**Comment by jan-auer** [comment]
Duplicate of https://github.com/getsentry/team-ingest/issues/303
