### ISSUE TITLE
Support Mixed Profiles RN/Android

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry#61142]
Backend changes for

- https://github.com/getsentry/sentry-react-native/pull/3397

```[tasklist]
### Tasks
- [x] Store JS profiles sent along the Android profile
- [x] Display the JS profile (aggregated and details)
- [ ] https://github.com/getsentry/vroom/pull/375
- [ ] https://github.com/getsentry/sentry/pull/61357
- [ ] https://github.com/getsentry/vroom/pull/390
- [ ] https://github.com/getsentry/vroom/pull/386
- [ ] https://github.com/getsentry/vroom/pull/397
- [ ] https://github.com/getsentry/sentry-react-native/pull/3397
```
