### ISSUE TITLE
Support images

### ISSUE THREAD

**Issue by DominikB2014** [getsentry/sentry#61161]
We want to have a similar flow for images as we do with cs and jss. The task is to add support for images in ingestion and the UI.

```[tasklist]
### Tasks
- [x] [Ingestion] Group `resource.image` by domain and file type. For example `https://something-cdn.com/images/something.png` becomes `https://*.something-cdn.com/*/*.png`.
- [x] [UI] (resource table) Add new type in dropdown for `images`, which filters for `resource.image || extension:[png, jpg, etc]`
- [x] [UI] (resource summary) The resource summary page for an image shall contain the 5 largest render blocking examples of an image at the top. Mocks available on slack
- [ ] https://github.com/getsentry/sentry/issues/62861
- [ ] https://github.com/getsentry/sentry/issues/62862
- [x] Update resource docs for images functionality
- [ ] https://github.com/getsentry/sentry/issues/62896
- [ ] https://github.com/getsentry/sentry/issues/63208
```

**Comment by DominikB2014** [comment]
@jjbayer any thoughts on this from the ingestion perspective? Grouping by domain + file extension will make it much better from a cardinality perspective

**Comment by jjbayer** [comment]
@DominikB2014 domain + file extension sounds great! I can open a PR for it.
