### ISSUE TITLE
Future Web Vitals Work

### ISSUE THREAD

**Issue by edwardgou-sentry** [getsentry/sentry#61363]
List of future Web Vitals Module features planned
https://github.com/getsentry/sentry/discussions/59620

```[tasklist]
### Tasks
- [ ] Desktop vs Mobile perf score profiles
- [ ] Replace FID in Web Vitals module and Performance Score calculation with INP
- [ ] Cross-Sentry metrics for web vitals
- [ ] https://github.com/getsentry/relay/issues/2873
- [ ] Statistical detectors for web vitals
- [ ] Transaction Summary migration into page overview
```

Dependancies:
Support INP: https://github.com/getsentry/sentry/issues/57907

**Comment by edwardgou-sentry** [comment]
Added https://github.com/getsentry/relay/issues/2873

**Comment by edwardgou-sentry** [comment]
Closing, no longer relevant
