### ISSUE TITLE
[Epic] Rich Slack Notifications

### ISSUE THREAD

**Issue by ceorourke** [getsentry/sentry#61455]
[Product Spec](https://www.notion.so/sentry/Rich-Slack-Notifications-f41a8d39e97f4cc68d0812a1413c5882)

[Tech Spec](https://www.notion.so/sentry/Rich-Slack-Notifications-Tech-Spec-867736397b4f4ef29b1d0251f5ae98c8#38995e2f5d1a4ba4adf598e6842d6e6d)

### Convert notifications to use block kit
```[tasklist]
- [ ] https://github.com/getsentry/sentry/issues/61456
- [ ] https://github.com/getsentry/sentry/issues/61457
- [ ] https://github.com/getsentry/sentry/issues/61459
- [ ] https://github.com/getsentry/sentry/issues/61460
- [ ] https://github.com/getsentry/sentry/issues/61461
- [ ] https://github.com/getsentry/sentry/issues/61463
- [ ] https://github.com/getsentry/sentry/issues/61465
- [ ] https://github.com/getsentry/sentry/issues/61464
- [ ] https://github.com/getsentry/sentry/issues/61468
```

### Message formatting updates
```[tasklist]
- [ ] https://github.com/getsentry/sentry/issues/62899
- [ ] https://github.com/getsentry/sentry/issues/62901
- [ ] https://github.com/getsentry/sentry/issues/62902
- [ ] https://github.com/getsentry/sentry/issues/62904
- [ ] https://github.com/getsentry/sentry/issues/62905
- [ ] https://github.com/getsentry/sentry/issues/63147
- [ ] https://github.com/getsentry/sentry/issues/63152
- [ ] https://github.com/getsentry/sentry/issues/63642
- [ ] https://github.com/getsentry/sentry/issues/64116
```
