### ISSUE TITLE
Determine which of Issues API endpoints should be publish, and which should be private or experimental

### ISSUE THREAD

**Issue by vartec** [getsentry/sentry#61480]
As part of Improve APIs Initiative for each API endpoint and REST verb which currently don't have ApiPublishStatus set, we need to determine if it should be published as a public API, or marked as Private or Experimental. 

Documentation on determining if API should or shouldn't be public and how to publish: https://develop.sentry.dev/api/public/

If an endpoint is determined as a candidate to be published, create an issue and link it in this[ placeholder epic](https://github.com/getsentry/sentry/issues/61479) (note: scope of _current_ work is just creation of the these tickets, not actually publishing).

If endpoint is determined to be kept private or experimental, it should be marked as such with `ApiPublishStatus`. Example:
https://github.com/getsentry/sentry/blob/dc65f986f481a27b3a13db224b4a096f009e1a48/src/sentry/api/endpoints/user_notification_email.py#L19-L24
This a minimal change, so no point in creating a separate ticket. 

Full list of our APIs to review:
https://github.com/getsentry/sentry-api-schema/blob/55650d39a6d2e95812568a97ff1937c1ec14d175/api_ownership_stats_dont_modify.json#L50-L188
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/61481
- [ ] https://github.com/getsentry/sentry/issues/61482
- [ ] https://github.com/getsentry/sentry/issues/61483
- [ ] https://github.com/getsentry/sentry/issues/61485
- [ ] https://github.com/getsentry/sentry/issues/61486
- [ ] https://github.com/getsentry/sentry/issues/61487
- [ ] https://github.com/getsentry/sentry/issues/61488
- [ ] https://github.com/getsentry/sentry/issues/61489
- [ ] https://github.com/getsentry/sentry/issues/61490
- [ ] https://github.com/getsentry/sentry/issues/61491
- [ ] https://github.com/getsentry/sentry/issues/61492
- [ ] https://github.com/getsentry/sentry/issues/61493
- [ ] https://github.com/getsentry/sentry/issues/61494
- [ ] https://github.com/getsentry/sentry/issues/61496
- [ ] https://github.com/getsentry/sentry/issues/61497
- [ ] https://github.com/getsentry/sentry/issues/61498
- [ ] https://github.com/getsentry/sentry/issues/61499
- [ ] https://github.com/getsentry/sentry/issues/65747
- [ ] https://github.com/getsentry/sentry/issues/65748
```
