### ISSUE TITLE
[Polish] Updates to Replay Hydration Diff

### ISSUE THREAD

**Issue by rachrwang** [getsentry/sentry#62095]
### Tasks
- [ ] Add beta sticker right of the Hydration Error breadcrumb in the Replay
- [ ] [Modal] Add beta sticker right of the modal header
- [x] https://github.com/getsentry/sentry/issues/62098
- [ ] [Modal] Add "Discussion" button with https://github.com/getsentry/sentry/discussions/62097 linked in the upper right hand corner
- [ ] [Analytics] Add analytics to the Discussion button
