### ISSUE TITLE
Get delightful_metrics.minimetrics_sample_rate to 1.0

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#62542]
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/63178
- [ ] https://github.com/getsentry/ops/pull/9010
- [x] Increase sample rate to 1.0
```

**Comment by jan-auer** [comment]
Done and validated.
