### ISSUE TITLE
[Epic] Issue Priority 🔺

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#63026]
[Internal Product Doc](https://www.notion.so/sentry/Priority-in-Issue-Details-Stream-dd6e314c7e9247369ffef0680afc3eb6)
[Internal Tech Spec](https://www.notion.so/sentry/Tech-Spec-Priority-in-Issue-Details-Stream-ac9ecbbc5cfd4baaae39ecf32f8e74ce)

The current Issue Stream is a mix of low, medium, and high priority issues, which can make it difficult for developers to find the issues they care about. By adding priority as an explicit issue state, we can give our users tools to reduce stream noise and prioritize meaningful work.

## Goals

- Add concept of priority to issues
- Allow priority to be defined by issue type owners (on creation and update over time)
- Allow priority to be changed by the end user, both in issue details and in the stream
- Update priority automatically through escalation
- Allow sorting and filtering by priority in the issue stream

## Milestone 1: Introduce priority to issues

The first step will be introducing priority to our database model, issue platform, and to the UI surfaces (issue details and stream). After this milestone is complete, users should be able to see and change priority. Additionally, partner teams owning other issue types should be able to set priority on creation or update over time using the issue platform APIs.

```[tasklist]
### Rollout
- [ ] https://github.com/getsentry/sentry/issues/63653
- [ ] https://github.com/getsentry/sentry/issues/64599
- [ ] [After GA] Remove feature flag
- [ ] EA Issue Priority
- [ ] Add documentation for issue priority
- [ ] GA Issue Priority
- [ ] https://github.com/getsentry/sentry/issues/66264
```

```[tasklist]
### Database schema changes
- [ ] https://github.com/getsentry/sentry/issues/63280
- [ ] https://github.com/getsentry/sentry/issues/63283
```

```[tasklist]
### Add new Activity and GroupHistory entry types
- [ ] https://github.com/getsentry/sentry/issues/63649
- [ ] https://github.com/getsentry/sentry/issues/63650
```

```[tasklist]
### Modify issue endpoints
- [ ] https://github.com/getsentry/sentry/issues/63266
- [ ] https://github.com/getsentry/sentry/issues/63267
- [ ] https://github.com/getsentry/sentry/issues/63268
```

```[tasklist]
### Issue creation
- [ ] https://github.com/getsentry/sentry/issues/63310
```

```[tasklist]
### Escalation
- [ ] https://github.com/getsentry/sentry/issues/63764
- [ ] https://github.com/getsentry/sentry/issues/63766
- [ ] https://github.com/getsentry/sentry/issues/63765
- [ ] https://github.com/getsentry/sentry/issues/65663
```

```[tasklist]
### Issue Platform
- [ ] https://github.com/getsentry/sentry/issues/63917
- [ ] https://github.com/getsentry/sentry/issues/63918
- [ ] https://github.com/getsentry/sentry/issues/64185
```

```[tasklist]
### Alerts 
- [ ] https://github.com/getsentry/sentry/issues/64420
```

```[tasklist]
### UI Changes
- [ ] https://github.com/getsentry/sentry/issues/64187
- [ ] https://github.com/getsentry/sentry/issues/64423
- [ ] https://github.com/getsentry/sentry/issues/64424
- [ ] https://github.com/getsentry/sentry/issues/63654
```

## Milestone 2: Add the ability to sort and filter on priority in the issue stream

Milestone 1 added priority to the data model and UI surfaces. This milestone goes one step further and allows filtering and sorting by priority in the issue stream. When this milestone is complete, users should have a new default issues stream view which filters out low priority issues. They should be able to create custom searches for priority types and be able to sort on priority as well.
```[tasklist]
### Issue priority search
- [ ] https://github.com/getsentry/sentry/issues/65097
- [ ] https://github.com/getsentry/sentry/issues/65098
```

```[tasklist]
### UI Changes
- [ ] https://github.com/getsentry/sentry/issues/65209
- [ ] https://github.com/getsentry/sentry/issues/65212
- [ ] https://github.com/getsentry/sentry/issues/65208
```

## Milestone 3: User education and UI polish

[Internal PRD](https://www.notion.so/sentry/Priority-Stream-Next-Steps-6043892cc36d4adcbfdd45b145ca2f72?pvs=4)

```[tasklist]
- [ ] https://github.com/getsentry/sentry/issues/66452
- [ ] https://github.com/getsentry/sentry/issues/66268
- [ ] https://github.com/getsentry/sentry/issues/66270
- [ ] https://github.com/getsentry/sentry/issues/66347
- [ ] https://github.com/getsentry/sentry/issues/66816
- [ ] https://github.com/getsentry/sentry/issues/66919
- [ ] https://github.com/getsentry/sentry/issues/66920
```
