### ISSUE TITLE
[Epic] Mobile Replay: Private Alpha Release

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#63255]
Part of: https://github.com/getsentry/sentry/issues/64379

Tracking of our first milestone, which we intend to make available to folks who submitted interest via the wait list:

* https://github.com/getsentry/sentry/discussions/63138

The scope is flexible, but we're aiming an MVP that's stable enough to get some users feedback.

```[tasklist]
### SDK Common
- [x] Keep `replay_id` on the scope's context and apply it to outgoing events, and trace `baggage` (https://github.com/getsentry/relay/blob/6f997888a23ac545362e75464d69cda50f1278eb/relay-sampling/src/dsc.rs#L55)
```

```[tasklist]
### SDK Android
- [x] Add breadcrumbs https://github.com/getsentry/sentry-java/pull/3372
- [x] ~Test that video codecs with the current default size (720) are available on different devices (AppCenter)~ Fixed by https://github.com/getsentry/sentry-java/pull/3327
- [x] Implement video on-demand (store screenshots to disk, every 5 seconds create a video and send an envelope and delete the video + screenshots locally) https://github.com/getsentry/sentry-java/pull/3272
- [x] If errorSampleRate is set, rotate the screenshot cache every 30sec https://github.com/getsentry/sentry-java/pull/3291
- [x] Implement new envelope items: Replay, ReplayRecording, ReplayVideo: https://github.com/getsentry/sentry-java/issues/3213
- [x] Handle orientation changes (send rrweb event/breadcrumb and change video size) https://github.com/getsentry/sentry-java/pull/3335 https://github.com/getsentry/sentry-java/pull/3357
- [x] Use dominant color for redacting
- [x] Set `replayId` to link replay and errors
```

```[tasklist]
### SDK iOS
- [x] Implement ReplayEvent
- [x] Core Options and parameters
- [x] Limit to 60 minutes maximun
- [x] Send DSC header to connect to backend errors
- [x] Use average color for redacting
```

**Comment by bruno-garcia** [comment]
Publish job for the first Alpha for Android [7.8.0-alpha.0](https://github.com/getsentry/publish/issues/3666)

**Comment by bruno-garcia** [comment]
Publish job for the first Alpha for iOS [8.24.0-alpha.0 ](https://github.com/getsentry/publish/issues/3668)

**Comment by bruno-garcia** [comment]
Alpha for iOS and Android shipped.
To get access, it requires adding your Sentry org to our feature flag. This way data can be ingested and displayed in Sentry.
[Please let us know on the waitlist if you're interested](https://sentry.io/lp/mobile-replay-beta/)

Once we add you to the feature flag, you can get it rolling with:

```
To install it, you need the SDK preview versions mentioned below, and the following code snippet:

// iOS: Update the Sentry SDK for iOS to version: 8.24.0-alpha.0
SentrySDK.start(configureOptions: { options in
  options.dsn = "your DSN"
  options.debug = true
  
  // Currently under experimental options:
  options.experimental.sessionReplay.errorSampleRate = 1.0
  options.experimental.sessionReplay.sessionSampleRate = 1.0
})
// Android: Update the Sentry SDK for Android to version: 7.8.0-alpha.0
// If you use the `io.sentry:sentry-android` dependency then no additional steps needed, otherwise you'd have to also include `io.sentry:sentry-android-replay` module directly
SentryAndroid.init(context) { options ->
  options.dsn = "your DSN"
  options.isDebug = true

  // Currently under experimental options:
  options.experimental.sessionReplay.errorSampleRate = 1.0
  options.experimental.sessionReplay.sessionSampleRate = 1.0
}
```

**Comment by Matthew-Jimenez** [comment]
Very nice @bruno-garcia 

Whats the timeline for React Native alpha?

**Comment by bruno-garcia** [comment]
> Very nice @bruno-garcia
> 
> Whats the timeline for React Native alpha?

We're aiming to have our first release out in a couple of weeks. Reminder that to see the data you not only need the right SDK and option enabled, but have your Sentry org in our alpha cohort feature flag. We'll be reaching out to folks [through the waitlist](https://sentry.io/lp/mobile-replay-beta/).

**Comment by bruno-garcia** [comment]
React Native first alpha is out and first cohort of ~100 orgs opt'ed in to the feature flag: https://github.com/getsentry/sentry-react-native/releases/tag/5.23.0-alpha.0

We've added native iOS and Android as well as React Native customers to the alpha cohort. We're moving on to our new milestone: Open Beta
* https://github.com/getsentry/sentry/issues/70065
