### ISSUE TITLE
[Epic] Mobile Session Replay

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#64379]
We started 2024 by building our Mobile Session Replay product.

For **Discussion on the topic** please refer to:
* https://github.com/getsentry/sentry/discussions/63138

We also track SDK specific support on their specific repositories:
* https://github.com/getsentry/sentry-java/issues/2476
* https://github.com/getsentry/sentry-cocoa/issues/2616
* https://github.com/getsentry/sentry-react-native/issues/2703
* https://github.com/getsentry/sentry-dart/issues/1193
* https://github.com/getsentry/sentry-dotnet/issues/2136

# Private Alpha
* https://github.com/getsentry/sentry/issues/63255

# Open Beta
* https://github.com/getsentry/sentry/issues/70065

Future areas of work:

```[tasklist]
### Post Open Beta stuff
- [ ] Capture request/response body and send along with Network spans
- [ ] iOS: Document multi click needs swizzling: https://docs.sentry.io/platforms/apple/guides/ios/configuration/swizzling/
- [ ] SDKs: Switch breadcrumbs logic to use beforeBreadcrumb callback + hint and storing rrweb breadcrumbs in replay
```

```[tasklist]
### UI: Mobile Replay - GA
- [ ] https://github.com/getsentry/sentry/issues/69230
- [ ] https://github.com/getsentry/sentry/issues/67695
- [ ] https://github.com/getsentry/sentry/issues/69256
- [ ] https://github.com/getsentry/sentry/issues/72231
```

```[tasklist]
### UI: Mobile Replay - Post-GA
- [ ] [Replay Details - UI] Surface gaps in the playback (e.g. if segment creation failed or other reasons)
- [ ] [Replay Details - UI] Surface soft keyboard interactions (e.g. based on `ui.input` breadcrumb)
```

```[tasklist]
### SDKs
- [ ] Offline support
```

**Comment by bruno-garcia** [comment]
We've GA'ed the product and iOS/Android/React Native are also GA.
This issue tracks some follow up areas but we don't need an epic to group them all anymore so closing.
