### ISSUE TITLE
[Milestone] Formulas

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#64542]
## Opportunity ##
Other competitors support the creation of formulas based on metrics (e.g. a/b, (a-b)/b, etc.). This has become a table stakes feature that users have come to accept and is also one of the main blockers for transitioning internally from Datadog to Sentry.

## Solution ##
- Add support for basic arithmetic operations and use of brackets in order to express formulas: +, -, *, /, (, ).
- Introduce use of formulas in the Metrics explorer page and metrics based Dashboard widgets (already supported for other datasets)

## Know limitations
- In the first iteration it will only be possible to use queries that access the same namespace and metric type in one formular. 

## Milestones ##
```[tasklist]
### Formulas in Metrics Page
- [ ] https://github.com/getsentry/sentry/issues/64543
- [ ] https://github.com/getsentry/sentry/issues/64544
- [ ] https://github.com/getsentry/sentry/issues/64776
- [ ] https://github.com/getsentry/sentry/issues/64777
- [ ] https://github.com/getsentry/sentry/issues/65226
- [ ] https://github.com/getsentry/sentry/issues/65603
- [ ] https://github.com/getsentry/sentry/issues/65765
- [ ] https://github.com/getsentry/sentry/issues/65866
- [ ] https://github.com/getsentry/sentry/issues/66201
- [ ] https://github.com/getsentry/sentry/issues/66558
- [ ] https://github.com/getsentry/sentry/issues/66559
- [ ] https://github.com/getsentry/sentry/issues/66560
- [ ] https://github.com/getsentry/sentry/issues/66585
- [ ] https://github.com/getsentry/sentry/issues/66674
- [ ] https://github.com/getsentry/sentry/issues/66675
```

```[tasklist]
### Investigation
- [ ] https://github.com/getsentry/sentry/issues/64545
```
```[tasklist]
### Feature refinement
- [ ] https://github.com/getsentry/sentry/issues/64778
- [ ] https://github.com/getsentry/sentry/issues/64779
```
