### ISSUE TITLE
[Milestone] Dashboard Widget Builder

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#64548]
## Problem ##
While aiming to make metrics widgets fast and easy to use in dashboards, we've essentially created two totally separate experiences in Dashboards depending on the dataset. This is suboptimal and can be confusing for the user.

## Solution ## 
Move metrics widget builder into a modal and reuse Metrics UI

## Designs
https://www.figma.com/file/MDl4ys3IgaQQKkW5KH6UNI/Specs%3A-Unify-Dashboard-Query-Builders?type=design&node-id=85%3A9075&mode=design&t=TaKKiOOxOcrZdr9n-1

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/65398
- [ ] https://github.com/getsentry/sentry/pull/65397
- [ ] https://github.com/getsentry/sentry/pull/65519
- [ ] https://github.com/getsentry/sentry/pull/64644
- [ ] https://github.com/getsentry/sentry/pull/64939
- [ ] https://github.com/getsentry/sentry/pull/64936
- [ ] https://github.com/getsentry/sentry/pull/65523
- [ ] https://github.com/getsentry/sentry/pull/65375

**Comment by HazAT** [comment]
This is done
