### ISSUE TITLE
[Epic] Terms of Service Updates

### ISSUE THREAD

**Issue by 17hogeju** [getsentry/sentry#64675]
[Internal Product Doc](https://www.notion.so/sentry/Improving-Legal-UI-UX-7d7b422358574b63b42506fa8dda4120)
[Internal Designs](https://www.figma.com/file/YV4bVoL5DNsGvlHXixQGgE/ToS-Updates?type=design&node-id=0-1&mode=design&t=m37zepwS5MR2mbXs-0)

The current UI/UX on the Legal page is confusing, and doesn’t fully meet the needs of our business or our customers. 

## Milestone 1: Update the Billing & Owner Experience
```[tasklist]
### Billing/owner role
- [ ] Remove CCPAA
- [ ] Move `Penetration Test Summary` to Compliance and Security section
- [ ] Add version date stamps
- [ ] Use primary CTA for something that needs to be reviewed and signed
- [ ] Use secondary CTA for review in new tab
- [ ] Version label dropdown updates 
- [ ] Move privacy policy, terms of service, and the other docs in compliance section to read-only section
- [ ] Contact details add/update modal
```

### Billing/owner role
- [ ] Any user has access to Legal & Compliance tab
- [ ] Any user can cmd+k to Legal & Compliance
- [ ] BAA upsell visible to all
- [ ] As a non-billing/owner all documents are read only
- [ ] As a non-billing/owner can't modify or save inputs
```
