### ISSUE TITLE
[Milestone] Dashboard Widget Details

### ISSUE THREAD

**Issue by obostjancic** [getsentry/sentry#65532]
## Problem ##
While aiming to make metrics widgets fast and easy to use in dashboards, we've essentially created two totally separate experiences in Dashboards depending on the dataset. This is suboptimal and can be confusing for the user.

![Image](https://github.com/getsentry/sentry/assets/86684834/b94093a5-952f-4c6a-8a1f-c0d58602128d)

## Designs
https://www.figma.com/file/MDl4ys3IgaQQKkW5KH6UNI/Specs%3A-Unify-Dashboard-Query-Builders?type=design&node-id=85%3A9075&mode=design&t=TaKKiOOxOcrZdr9n-1
```[tasklist]
### Tasks
- [ ] Take all the stuff from the custom metrics modal and put it in a tray found in Performance
- [x] Add table and big number visualisations
- [ ] Create view and edit modes for tray for the custom metrics data set
- [ ] Migrate Samples & Code Locations from edit state to view state
- [ ] Create view state for tray for the rest of the data-sets
- [ ] Add summary table for other data-sets (without aggregations)
- [ ] Show the query string inside of chart
```

**Comment by matejminar** [comment]
Pausing work on this.
