### ISSUE TITLE
SDK Crash Detection: Enable Java/Android

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry#65770]
Enable the SDK crash detection for the sentry-java SDK.
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/65771
- [ ] https://github.com/getsentry/sentry/pull/65773
- [ ] https://github.com/getsentry/sentry/pull/65968
- [ ] https://github.com/getsentry/sentry-options-automator/pull/844
```

**Comment by philipphofmann** [comment]
All tasks completed. We can close this.
