### ISSUE TITLE
Move Feedback Ingestion to its own Topic / Consumer

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry#66100]
```[tasklist]
### Tasks
- [x] Work with ops to create kafka topic `ingest-feedbacks`
- [x] modify sentry to have feedbacks on their own consumer. should be fairly easy since we just need to define the config here. (transactions did something very similar) https://github.com/getsentry/sentry/blob/fd777f2ad0bfc3de886c720ef6952ece2ec0074f/src/sentry/consumers/__init__.py#L259
- [x] Work with ops to deploy this new consumer, test it out
- [x] Cut over the topic on relay
```

Motivation: when errors pipeline has problems, we don't want to lose feedbacks. Additionally, we can add things like a dead letter queue, etc.

**Comment by cmanallen** [comment]
@aliu-at-sentry You've been volunteered for this issue but don't worry! I'll pair with you and we can tackle it together.  Let's plan to start on this on Monday.  We can use our first standup as the jumping off point.

**Comment by aliu3ntry** [comment]
![IMG_7242](https://github.com/getsentry/sentry/assets/159852527/db727dd3-fce5-4bfa-a90f-88a27cf53219)
Red is TODO

**Comment by JoshFerge** [comment]
Relay TODO:
- [ ] Add an option backed feature flag, make sure it is available in relay. Add this flag to relay
- [ ] add a KafkaTopic to the kafka topic enum 
- [ ] Modify services/store.rs so that it produces ItemType::UserReportV2 to the new kafka topic. sidenote: Attachments should still go to the attachments topic

**Comment by aliu3ntry** [comment]
Metrics to track ingest in s4s:
[relay](https://app.datadoghq.com/metric/explorer?fromUser=false&fullscreen_end_ts%5B0%5D=1713304879%5B%E2%80%A6%5D218479170&fullscreen_end_ts%5B1%5D=1713304879170&fullscreen_paused=false&fullscreen_refresh_mode=sliding&fullscreen_start_ts=1713218479170&start=1713301852146&end=1713305452146&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYAEwGIFCeGE4a+NoAxkrIIOoIulmWgWZxykaYWAB08to4ORoaojDVcABucCIItfVQeDlQwFrdcU5GMJIiyBoIALQjhVgALItxPAAEAEZYG8NdS+Nwk1IUCDjyEFk81Rga455wABQAlCA8ALpUru54mKHhH6qP4YGJlBLvL4gWZYNC5UDyDBwhAIXLJHAwJxZf7NLJJNCiOBOOSKZQZAlQfGEpz0JjKERuDxod78CD2KrEhRogkiJSfHh8aHyAkIADCUmEMBQIj+aB4QA) -- corresponds to [this code](https://github.com/getsentry/relay/blob/56c3eb8a4f6d72d86d18ee34d01de15d5c42acea/relay-server/src/services/store.rs#L597)

[consumer group (see "consumer offset rate")](https://app.datadoghq.com/dashboard/qkh-eey-uxf/sentry-consumers?fromUser=false&refresh_mode=sliding&tpl_var_consumer_group%5B0%5D=ingest-feedback-events-consumers&tpl_var_sentry_region%5B0%5D=st-sentry4sentry&view=spans&from_ts=1713391616377&to_ts=1713392516377&live=true)

[create_feedback_issue](https://app.datadoghq.com/metric/explorer?fromUser=false&start=1713470151701&end=1713473751701&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGABuMMhaIgVYAHSCcHBQAEYYmQDWDZlGnnAuLe2dXU4QGhpmDXB1Oq3AtfVORjCSIjUIALRLcQAsu1g8DRgaTpn4dQAUAJQgPAC6VK7ueJih4S+qbxgxpfH3J4gDRyNA5UDyDBghAIHJJHAwc7vDQQTKJNCiQZyRTKdIYqDozFOehMZQiNweND3fgTeSYLBObFwjEiJSPHh8YF08QAYSkwhgKBEbzQPCAA)

**Comment by aliu3ntry** [comment]
🎉🎉🎉🎉🎉
