### ISSUE TITLE
Change Crons front-end endpoints to use project slug

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#66615]
We have decided to switch cron monitor slugs from being **unique to organizations** to now being **unqiue to projects**.

We have already done the work required on the backend to provide API endpoints for these:

```[tasklist]
### Backend API updates
- [ ] https://github.com/getsentry/sentry/pull/65900
- [ ] https://github.com/getsentry/sentry/pull/65914
- [ ] https://github.com/getsentry/sentry/pull/65925
- [ ] https://github.com/getsentry/sentry/pull/65940
- [ ] https://github.com/getsentry/sentry/pull/65953
```

We now need the frontend to use these APIs. There's some complexity to this however, since migrating these is somewhat non trivial

1. Let's pick the route for the monitors that has the project slug in it: `/crons/[:projectSlug]/[:monitorSlug]/` seems reasonable, and is aligned with what we do in other places.

2. To start, let's create routes that include the project slug, which still use the same component logic (discarding the project slug).

4. We can now do a few things that make use of the new routes without needing to actually start introducing the new API endpoint usage.
   - Update the monitor listing page to use the project-based URLs.
   - Update all emails that are linking directly to monitors
   - Update monitor issues to correctly link to the new routes

5. We should track metrics for the views when they **do not receive** the project slug as part of the URL parameters. This will help us to understand if we are still missing some links.

6. Once we are confident most links back to monitors are being done through the redirect, we can remove the old routes and update the views to use the new project based APIs.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/66887
- [ ] https://github.com/getsentry/sentry/pull/66914
- [x] Verify low usage of projectId-less routes
- [ ] https://github.com/getsentry/sentry/pull/67066
- [ ] https://github.com/getsentry/sentry/pull/67026
```

**Comment by evanpurkhiser** [comment]
Going to close this out now. The follow up is going to be https://github.com/orgs/getsentry/projects/51/views/9?filterQuery=week%3A%40previous%2C%40current+&pane=issue&itemId=56619831
