### ISSUE TITLE
SDK Crash Detection: Enable Dart/Flutter

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry#66762]
Enable the SDK crash detection for the [sentry-dart](https://github.com/getsentry/sentry-dart) SDK.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-dart/pull/2050
- [ ] https://github.com/getsentry/sentry/pull/71233
- [ ] https://github.com/getsentry/sentry/pull/71318
- [ ] https://github.com/getsentry/sentry-options-automator/pull/1464
- [ ] https://github.com/getsentry/sentry-options-automator/pull/1465
- [ ] https://github.com/getsentry/sentry/pull/71545
- [ ] https://github.com/getsentry/sentry-dart/pull/2072
- [ ] https://github.com/getsentry/sentry-options-automator/pull/1518
```

**Comment by philipphofmann** [comment]
@buenaflor, I need your input, please. If you need a refresher on what SDK crash detection is, read [this](https://github.com/getsentry/sentry/tree/master/src/sentry/utils/sdk_crashes).

I plan to enable the SDK crash detection for the Dart SDK. To do this, I need to create a configuration similar to what we already have for the Java SDK.

https://github.com/getsentry/sentry/blob/3e90887a3632585b048f607668e20927321a39a0/src/sentry/utils/sdk_crashes/sdk_crash_detection_config.py#L154-L202

This is how the native configuration would roughly look:

```python
dart_config = SDKCrashDetectionConfig(
    # ...
    sdk_names=["sentry.dart", "sentry.dart.flutter"],
    # 7.9.0 was released in July 2023, see https://github.com/getsentry/sentry-dart/releases/tag/7.9.0
    min_sdk_version="7.9.0",
    system_library_path_patterns={
        r"third_party/dart/sdk/**",  # Dart
        r"/opt/flutter/packages/flutter/**",  # Flutter
    },
    sdk_frame_config=SDKFrameConfig(
        function_patterns=set(),
        path_patterns={
            r"**/sentry-**",
        },
        path_replacer=KeepAfterPatternMatchPathReplacer(
            patterns={
                r"\/sentry-.*",
            },
            fallback_path="sentry",
        ),
    ),
    sdk_crash_ignore_functions_matchers=set(),
)
```

@buenaflor, please answer the following questions:

1. Does the Dart SDK have more SDK names? If yes, which ones?
2. Which `system_library_path_patterns` should I add? This is for keeping system library or system binary frames in the stacktrace for SDK crashes?
3. If I'm not mistaken, all Sentry Dart SDK frames have `sentry-` in their `abs_path` followed by the version number of the SDK? Is there a better reliable way to detect Sentry Dart SDK frames? 
4. Regarding `sdk_crash_ignore_functions_matchers`: For Cocoa we have a test function causing a crash we want to ignore. Does the Sentry Dart SDK have something similar?

**Comment by buenaflor** [comment]
1. afaik the names include:`sentry.dart`, `sentry.dart.flutter`, `sentry.dart.browser`
2. Judging by some of the abs_paths: `package:flutter/src/gestures/tap.dart`, `dart:ui/platform_dispatcher.dart`, something like `r"flutter/**" and `r"dart:**", but I'm not too sure about the syntax. As for web errors it seems a bit more complicated since there is no obvious system library path, e.g **[this web stacktrace](https://us.sentry.io/api/0/projects/sentry-sdks/sentry-flutter/events/a8e9ba1f08cf43af8a6f2c55ef2f5b0d/json/)**, for example `http://localhost:53744/binding.dart` 
3. The abs path usually looks like `package:sentry**` or `package:sentry_flutter**` just wondering though how we can detect sdk frames since we remove them: https://github.com/getsentry/sentry-dart/blob/6575860857eb9784ce13785f3a2eeade01013808/dart/lib/src/sentry_stack_trace_factory.dart#L44
4. No we don't

**Comment by philipphofmann** [comment]
> I'm wondering though how we can detect sdk frames at all since we remove them: https://github.com/getsentry/sentry-dart/blob/6575860857eb9784ce13785f3a2eeade01013808/dart/lib/src/sentry_stack_trace_factory.dart#L44

@buenaflor, upsi, that's a blocker. Can we start sending them? On Java, we send SDK frames in case of a crash (https://github.com/getsentry/sentry-java/pull/3021), but it's better to do this in the next major because it can affect grouping. Otherwise, the SDK crash detection won't work.

**Comment by buenaflor** [comment]
Hmm is it still feasible to do it in the current major? we've released v8 but it's still pretty new. otherwise we can add this to v9 but tbh I'm not sure when the next major for dart would be released

**Comment by philipphofmann** [comment]
@buenaflor, strictly speaking, no, we shouldn't do this without a major, but as these frames aren't inApp in most cases they shouldn't impact grouping. @kahest what do you think?

**Comment by kahest** [comment]
I'm wondering why we removed them in the first place. In general I'm ok with doing this in 8.2.0 if we are sufficiently confident that it doesn't affect grouping, especially since v8 is still very new

**Comment by buenaflor** [comment]
Just traced back the change at it has been there since 2020. I'll check how it affects grouping

**Comment by buenaflor** [comment]
> inApp in most cases they shouldn't impact grouping 

This seems to be the case here as well, I tried it out and it still is grouped with the same error without the sentry frame. So I think we're good to go in removing it

Example: https://sentry-sdks.sentry.io/issues/4722238716/events/d70d73150b2a401e9b56755f968cc1de/?project=5428562&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=next-event&statsPeriod=1h&stream_index=0

**Comment by philipphofmann** [comment]
I'm going to use the same rules for system frames that we use for grouping
https://github.com/getsentry/sentry/blob/c4c4c9f4e8de9662c6fcb6ea123b8ab4cd34d133/src/sentry/grouping/enhancer/enhancement-configs/newstyle%402023-01-11.txt#L83-L85

**Comment by philipphofmann** [comment]
We can't make it work for Flutter Browser because the stacktrace paths don't include enough information to reliably detect where frames come from, but I think that's acceptable.

```JSON
{
    "function": "<fn>",
    "filename": "main.dart",
    "abs_path": "http://localhost:53617/main.dart",
},
{
    "function": "setTag",
    "filename": "sentry_tracer.dart",
    "abs_path": "http://localhost:53617/sentry_tracer.dart",
},
{
    "function": "_get]",
    "filename": "js_array.dart",
    "abs_path": "http://localhost:53617/js_array.dart",
},
{
    "function": "throw_",
    "filename": "errors.dart",
    "abs_path": "http://localhost:53617/errors.dart",
}
```

**Comment by philipphofmann** [comment]
We're sampling at 100% now https://github.com/getsentry/sentry-options-automator/pull/1518. We can close this.
