### ISSUE TITLE
Enable first beta cohort

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#66770]
Enabling the first cohort of 5K orgs in the beta.
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/66771
- [ ] https://github.com/getsentry/sentry/issues/66772
- [ ] https://github.com/getsentry/sentry/issues/66773
- [ ] https://github.com/getsentry/sentry/issues/66775
- [ ] https://github.com/getsentry/sentry/issues/66774
- [ ] https://github.com/getsentry/sentry/issues/67122
- [x] https://github.com/getsentry/sentry/issues/67123
- [ ] Heads up Support/Sales with internal FAQ
- [ ] Heads up Ops/Ingest/SnS
- [ ] Discord post in feature feedback
- [ ] https://github.com/getsentry/sentry/issues/67125
- [ ] https://github.com/getsentry/sentry/issues/67126
- [ ] https://github.com/getsentry/sentry/issues/67129
- [ ] https://github.com/getsentry/sentry/issues/67132
```
