### ISSUE TITLE
Cleaning status in monitor environment (removing timeout and missed statuses)

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry#66878]
These status are no longer needed -- We only denormalize `MonitorStatus.ERROR` onto the environment since that indicates it is in an incident state.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/66721
- [ ] https://github.com/getsentry/sentry/pull/66785
- [ ] https://github.com/getsentry/sentry/pull/66832
```
