### ISSUE TITLE
[Epic] Issue Stream Accuracy and Performance Improvements

### ISSUE THREAD

**Issue by snigdhas** [getsentry/sentry#67179]
[Internal PRD](https://www.notion.so/sentry/Issue-stream-performance-and-accuracy-67eead983dea4f11994a5f111437abf4)
[Internal Tech Spec](https://www.notion.so/sentry/Tech-Spec-Issue-Stream-Performance-Accuracy-951d31615f55435b9cac6c70fdc463ad)

In the process of adding new features and improving functionality of the issue stream, the Issues team has become aware of inaccuracies on the stream as well as areas for performance improvements. These improvements would increase the usability of the stream and give our users a better experience.

## Milestone 1: Fix sorting by `first_seen`

```[tasklist]
### Rollout
- [ ] Internal benchmark for milestone 1
- [ ] EA release for milestone 1
- [ ] GA release for milestone 1
```

```[tasklist]
### Group Attributes Query Executor
- [ ] https://github.com/getsentry/sentry/issues/67185
- [ ] https://github.com/getsentry/sentry/issues/67186
- [ ] https://github.com/getsentry/sentry/issues/67187
- [ ] https://github.com/getsentry/sentry/issues/67188
- [ ] https://github.com/getsentry/sentry/issues/67189
- [ ] https://github.com/getsentry/sentry/issues/67190
- [ ] https://github.com/getsentry/sentry/issues/67191
- [ ] https://github.com/getsentry/sentry/issues/67192
```
