### ISSUE TITLE
Update screenshots in Feedback Details to align with designs

### ISSUE THREAD

**Issue by c298lee** [getsentry/sentry#67707]
Designs here: https://www.figma.com/file/hIUACYgu3lenuAPLgg22a3/Specs%3A-Screenshots-v1?type=design&node-id=29-1698&mode=design&t=eXQl14ol7pADOffQ-0

Currently screenshots in feedback details just reuse the screenshot preview from issue details

**Comment by michellewzhang** [comment]
## TODOS

- [ ] Currently, if you delete a screenshot, it will not show up in UI anymore. The design specifies that we should instead show this message instead:
<img width="396" alt="SCR-20240329-kuoq" src="https://github.com/getsentry/sentry/assets/56095982/dddf4e47-6f1b-4ac8-88c5-e7b43b50628d">

- [ ] Pagination code largely copied from the issues component; not tested since we can't currently add multiple screenshots in a FB submission yet
- [ ] Screenshot display in details isn't scaling properly -- if a screenshot comes in that's extra wide or extra long (e.g. more than `360px` in either dimension, it'll get cropped to fit within `360px` x `360px`. However the design specifies that the entire image should instead scale down to fit within this box, rather than getting cropped
- [ ] When clicking into full screen/zoom-in mode, the modal should take up the whole screen rather than staying the same dimensions as the image. (see designs for reference)

**Comment by ryan953** [comment]
The last part of the design missing is treatment for 'deleted attachments'.

I've spun that off into it's own ticket here: https://github.com/getsentry/sentry/issues/68907
We can close this one now.
