### ISSUE TITLE
Cache 

### ISSUE THREAD

**Issue by gioshi3007** [getsentry/sentry#68123]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

> const Prometheus = require('prom-client');

// Definir el histograma para la duración de las operaciones de caché
const cacheOperationDuration = new Prometheus.Histogram({
  name: 'cache_operation_duration_seconds',
  help: 'Duration of cache operations',
  labelNames: ['transaction_name', 'action', 'environment', 'cache_result', 'domain_table'],
  buckets: [0.1, 0.5, 1, 2, 5] // Definir los intervalos de duración
});

// Función para registrar una operación de caché
function recordCacheOperation(transactionName, action, environment, cacheResult, domainTable, duration) {
  cacheOperationDuration.labels(transactionName, action, environment, cacheResult, domainTable).observe(duration);
}

// Ejemplo de registro de una operación de caché
recordCacheOperation('example_transaction', 'get', 'production', 'hit', 'user_data', 0.05);

### Expected Result

const Prometheus = require('prom-client');

// Definir el histograma para la duración de las operaciones de caché
const cacheOperationDuration = new Prometheus.Histogram({
  name: 'cache_operation_duration_seconds',
  help: 'Duration of cache operations',
  labelNames: ['transaction_name', 'action', 'environment', 'cache_result', 'domain_table'],
  buckets: [0.1, 0.5, 1, 2, 5] // Definir los intervalos de duración
});

// Función para registrar una operación de caché
function recordCacheOperation(transactionName, action, environment, cacheResult, domainTable, duration) {
  cacheOperationDuration.labels(transactionName, action, environment, cacheResult, domainTable).observe(duration);
}

// Ejemplo de registro de una operación de caché
recordCacheOperation('example_transaction', 'get', 'production', 'hit', 'user_data', 0.05);

### Actual Result

const Prometheus = require('prom-client');

// Definir el histograma para la duración de las operaciones de caché
const cacheOperationDuration = new Prometheus.Histogram({
  name: 'cache_operation_duration_seconds',
  help: 'Duration of cache operations',
  labelNames: ['transaction_name', 'action', 'environment', 'cache_result', 'domain_table'],
  buckets: [0.1, 0.5, 1, 2, 5] // Definir los intervalos de duración
});

// Función para registrar una operación de caché
function recordCacheOperation(transactionName, action, environment, cacheResult, domainTable, duration) {
  cacheOperationDuration.labels(transactionName, action, environment, cacheResult, domainTable).observe(duration);
}

// Ejemplo de registro de una operación de caché
recordCacheOperation('example_transaction', 'get', 'production', 'hit', 'user_data', 0.05);

### Product Area

User Feedback

```[tasklist]
### Tasks
- [ ] const Prometheus = require('prom-client');  // Definir el histograma para la duración de las operaciones de caché const cacheOperationDuration = new Prometheus.Histogram({   name: 'cache_operation_duration_seconds',   help: 'Duration of cache operations',   labelNames: ['transaction_name', 'action', 'environment', 'cache_result', 'domain_table'],   buckets: [0.1, 0.5, 1, 2, 5] // Definir los intervalos de duración });  // Función para registrar una operación de caché function recordCacheOperation(transactionName, action, environment, cacheResult, domainTable, duration) {   cacheOperationDuration.labels(transactionName, action, environment, cacheResult, domainTable).observe(duration); }  // Ejemplo de registro de una operación de caché recordCacheOperation('example_transaction', 'get', 'production', 'hit', 'user_data', 0.05);
```

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/67248
- [ ] https://github.com/getsentry/sentry/pull/68053
- [ ] https://github.com/getsentry/sentry/pull/67175
- [ ] https://github.com/getsentry/sentry/pull/67563
- [ ] https://github.com/getsentry/sentry/pull/68120
```

**Comment by gioshi3007** [comment]
Tarra

**Comment by nhsiehgit** [comment]
![hmmm](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNGcxdnp5ajVpcXBydjg4aXpoZmIzazd5ZWNoOXl5M3Zzcml6MHhvMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ANbD1CCdA3iI8/giphy.gif)
