### ISSUE TITLE
Crons: Monitor Assignment

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#68202]
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/68623
- [ ] https://github.com/getsentry/sentry/issues/68807
- [ ] https://github.com/getsentry/sentry/issues/69500
- [ ] https://github.com/getsentry/sentry-docs/pull/9784
- [ ] https://github.com/getsentry/develop/pull/1249
- [ ] https://github.com/getsentry/sentry/pull/69522
- [ ] https://github.com/getsentry/sentry/pull/69521
- [ ] Update SDKs to support owner
```

**Comment by evanpurkhiser** [comment]
@gaprl I'm not sure what upsert assignment is going to look like.

Right now the form that we use is `user:<id>` I don't think we should force users to have to lookup their IDs if we're going to allow upserting with ownership, we probably want to use email or teams. In which case, we'll probably need some kind of special processing here.

cc @wedamija for visibility here
