### ISSUE TITLE
Implement twemproxy compatible routing for Python

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#68599]
As discussed in the meeting on April 9th we want to explore if we can do without twemproxy we would like to see if we can match the same routing behavior from twemproxy with Python directly. For that we want to use the `HashClient` of `pymemcache` with a custom hasher that routes the same way as our config of twemproxy.

We use the following configs:
* `crc32a` (matching `zlib.crc32` in python)
* `ketema`

I believe that the input fed into the ketema hash function are not the hostname and port tuples, but instead the custom host names from the `default.yaml`. As the python library does not support custom inputs to ketema via the hasher, that information would have to be relayed manually to the hasher somehow.

Useful links:

* https://github.com/twitter/twemproxy/releases/tag/0.5.0 (twemproxy source dump). configure we use: ketema for dist + crc32a
* https://github.com/getsentry/rb/blob/master/rb/ketama.py (python ketema impl i wrote a while back)
* https://github.com/getsentry/ops/blob/f2b9cf8d9a2dd233c6a05d96cd834cbf62e5315f/k8s/clusters/us/default.yaml#L3103 (inputs that are passed to twemproxy)

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/ophio/pull/52
- [ ] https://github.com/getsentry/ophio/pull/54
- [ ] https://github.com/getsentry/getsentry/pull/13628
- [ ] https://github.com/getsentry/ops/pull/10114
- [ ] https://github.com/getsentry/getsentry/pull/13698
- [ ] https://github.com/getsentry/getsentry/pull/14073
- [ ] https://github.com/getsentry/ophio/pull/55
```

**Comment by Swatinem** [comment]
This plan was later scrapped, as this would blow up the total number of connects way too much, essentially N (number of workers) * M (number of memcached hosts).

So we are reverting / removing all the code that was written for this.
