### ISSUE TITLE
Move assemble status to redis

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#68598]
While investigating caching issues we realized that the assemble status is stored in memcache. This is problematic as memcache neither has persistence, nor can we guarantee that we do not get stale reads which makes moving away to a different memcache clustering system difficult.

- implement dual writing for `set_assemble_status`
- implement dual reading for `get_assemble_status`
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/70344
- [ ] https://github.com/getsentry/sentry-options-automator/pull/1358
- [ ] https://github.com/getsentry/sentry/pull/70490
```
