### ISSUE TITLE
[Epic] Evolved Issues Search 🧬

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#68671]
In order to decrease friction and increase discoverability of Sentry’s powerful issue search, the UI will undergo a refresh that makes search queries easier to create and reason about.

[Internal Figma Designs](https://www.figma.com/file/qLPE7uSdRZMOJloVumv8rA/Q1-Smart-Search)

![Image](https://github.com/getsentry/sentry/assets/10888943/3e2b0b84-bdc0-4db2-a488-2f2b2cb34a00)

![Image](https://github.com/getsentry/sentry/assets/10888943/e35895d0-b348-4ce2-a411-073b2d175953)

```[tasklist]
### Discovery
- [ ] https://github.com/getsentry/sentry/issues/68754
- [ ] https://github.com/getsentry/sentry/issues/68755
- [ ] https://github.com/getsentry/sentry/issues/68757
- [ ] https://github.com/getsentry/sentry/issues/68758
- [ ] https://github.com/getsentry/sentry/issues/68759
- [ ] https://github.com/getsentry/sentry/issues/69788
```

```[tasklist]
### Rollout
- [x] Add feature flag
- [ ] Add documentation
- [ ] EA
- [ ] GA
- [ ] Remove feature flag
```

```[tasklist]
### Component Development
- [ ] https://github.com/getsentry/sentry/issues/69244
- [ ] https://github.com/getsentry/sentry/issues/69262
- [ ] https://github.com/getsentry/sentry/issues/69263
- [ ] https://github.com/getsentry/sentry/issues/69264
- [ ] https://github.com/getsentry/sentry/issues/69266
- [ ] https://github.com/getsentry/sentry/issues/69265
- [ ] https://github.com/getsentry/sentry/issues/69340
- [ ] https://github.com/getsentry/sentry/issues/69723
- [ ] https://github.com/getsentry/sentry/issues/69725
- [ ] https://github.com/getsentry/sentry/issues/69726
- [ ] https://github.com/getsentry/sentry/issues/69727
- [ ] https://github.com/getsentry/sentry/issues/69728
- [ ] https://github.com/getsentry/sentry/issues/69729
- [ ] https://github.com/getsentry/sentry/issues/69730
- [ ] https://github.com/getsentry/sentry/issues/69734
- [ ] https://github.com/getsentry/sentry/issues/69735
- [ ] https://github.com/getsentry/sentry/issues/69736
- [ ] https://github.com/getsentry/sentry/issues/69791
- [ ] https://github.com/getsentry/sentry/issues/70188
- [ ] https://github.com/getsentry/sentry/issues/70953
- [ ] https://github.com/getsentry/sentry/issues/71732
- [ ] https://github.com/getsentry/sentry/issues/71800
```

```[tasklist]
### TagStore changes
- [ ] https://github.com/getsentry/sentry/issues/73699
- [ ] https://github.com/getsentry/sentry/issues/73700
```
