### ISSUE TITLE
Crons: Add frontend components of assignment

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry#68807]
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/68808
- [ ] https://github.com/getsentry/sentry/pull/69047
- [ ] https://github.com/getsentry/sentry/pull/69030
- [ ] https://github.com/getsentry/sentry/pull/69069
- [ ] https://github.com/getsentry/sentry/pull/69355
```
