### ISSUE TITLE
Improve onboarding for new Metrics users

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#68864]
## Problem ##

We currently have an in-product guide for how to send custom metrics, but that's all the onboarding we have. This is not sufficient for customers to understand the full functionality and can be confusing for someone who just lands on the Metrics tab with no prior knowledge.

We have 2 scenarios:
- customer NOT sending performance data at all (have therefore no metrics to visualise yet)
- customers sending perf data (who can already see the ootb perf metrics)

Particular issues:
- the page combines custom metrics and ootb performance metrics, but the user has no way to know this today
- the idea that you are even able to send custom metrics to Sentry is not apparent at all, unless you click on the "set up custom metrics" button
- the UI is very similar to Discover and also has elements of Performance which leaves some customers thinking "how is this different"?

## Proposed Solution ##
**Empty state**
- Have a common empty state for both scenarios that describes both the ability to visualise custom metrics as well as ootb performance metrics. It contains 3 options for the user:
  - (main CTA) Add custom metric
    - opens setup instructions 
    - the snippet is expanded to include examples for all metrics types
    - separate paragraph about the value of adding tags
  - View performance metrics (when present)
    - takes the user to the UI with `transaction.duration` plotted
    - dismissible banner on top to remind them about custom metrics (until first is sent) - CTA "set up custom metrics"
  - Read Docs 
  - FAQ
    - have 2-3 questions answered upfront to clarify most common topics

**First time in UI**
- start tour with pendo guide that points to main UI elements similar to [docs arcade](https://docs.sentry.io/product/metrics/metrics-explorer-page/#querying--visualization)
- default to alphabetical first custom metric when present
  - if not, transaction.duration

## References ##

**Session Replay**
![Image](https://github.com/getsentry/sentry/assets/26696515/cb306fea-213d-43c0-91b6-02920dadabf2)

![Image](https://github.com/getsentry/sentry/assets/26696515/d67da0a9-96bd-4131-b95b-80ba7a197d4c)

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/69945
- [ ] https://github.com/getsentry/sentry/issues/69953
- [ ] https://github.com/getsentry/sentry/issues/70208
- [ ] https://github.com/getsentry/sentry/issues/70209
- [ ] https://github.com/getsentry/sentry/issues/70210
- [ ] https://github.com/getsentry/sentry/issues/70212
- [x] Discuss multi language platforms (Java / Kotlin, Apple-ios)
```

**Comment by ale-cota** [comment]
Copy suggestion for tags:
"You can enrich metrics by adding 'tags'. These are key/value string pairs (for example, platform:ios, region:EU) that are associated with metrics to provide additional context information. When you look at your metrics in the product, you can filter and group by these tags, to narrow down and segment your data."

**Comment by ale-cota** [comment]
Copy suggestion for empty state:

```
Track and solve what matters
Create custom metrics to track and visualize the data points you care about over time, like processing time, checkout conversion rate, or user signups. See correlated trace exemplars and metrics if used together with Performance Monitoring.
```

CTAs: 
- `Add Custom Metric` - opens setup instructions
- `View Performance Metrics` - greyed out if no perf data is present
  - on-hover tooltip: Requires [Performance Monitoring](https://docs.sentry.io/product/performance/getting-started/)
- `Read Docs` -  https://docs.sentry.io/product/metrics

**Comment by ArthurKnaus** [comment]
I think an FAQ entry called `What are custom metrics?` would make sense as people where confused about it (coming from performance custom measurements).
