### ISSUE TITLE
[Epic] Evolved Issues Stream 🧬 

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#69051]
[Internal Tech Spec](https://www.notion.so/sentry/Tech-Spec-Evolved-Issue-Stream-7462e482a2964c57ac142309e6874a5c)

[Internal Figma Designs](https://www.figma.com/file/MM42MEY0OiZRVzQlI8XHej/Q1-Issue-Stream?type=design)

For the search improvements, see https://github.com/getsentry/sentry/issues/68671

```[tasklist]
### Rollout
- [ ] Evolved Issues Stream: Create feature flag for new table view
- [ ] Evolved Issues Stream: EA
- [ ] Evolved Issues Stream: GA
- [ ] Evolved Issues Stream: Cleanup feature flag
```

```[tasklist]
### Targeted component improvements
- [ ] https://github.com/getsentry/sentry/issues/69054
- [ ] https://github.com/getsentry/sentry/issues/69691
- [ ] https://github.com/getsentry/sentry/issues/69699
- [ ] https://github.com/getsentry/sentry/issues/69731
- [ ] https://github.com/getsentry/sentry/issues/69732
- [ ] https://github.com/getsentry/sentry/issues/69826
- [ ] https://github.com/getsentry/sentry/issues/69827
- [ ] https://github.com/getsentry/sentry/issues/69829
- [ ] https://github.com/getsentry/sentry/issues/69835
```
