### ISSUE TITLE
[Replay Details - Breadcrumbs] Support mobile user interaction breadcrumbs

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry#69253]
```[tasklist]
### Tasks
- [ ] Support `ui.click` breadcrumb type (title: "User Click", description: `message`)
- [x] ~Support `ui.scroll` breadcrumbs type (title: "User Scroll", description: `message`)~
- [x] ~Support `ui.swipe` breadcrumbs type (title: "User Swipe", description: `message`)~
- [ ] Use a different icon for mobile `ui.` breadcrumbs
```

Alternatively, for the description, we could also implement the json view from the issue breadcrumbs component and just display the entire `data` field there (this way we can also add more metadata to these crumbs):
![image](https://github.com/getsentry/sentry/assets/4999776/11b3403b-df78-4dae-9a26-10b5a5d04913)

---

Re. using a different icon - the mouse pointer one is not really reflecting user touch/scroll/swipe. In the breadcrumbs component for an issue we use the following icon:
![image](https://github.com/getsentry/sentry/assets/4999776/3fd2d9f3-6bc1-4fb1-b82a-63857d8635eb)

**Comment by romtsn** [comment]
Maybe we'll have a mobile-specific format, @billyvg will look into this

**Comment by romtsn** [comment]
Also, we only want to support `ui.click` for breadcrumbs probably, other touch events should just come as rrweb events to reflect them on the playback itself

**Comment by michellewzhang** [comment]
TODO: go through rrweb library to figure out what mobile events are supported @billyvg

**Comment by michellewzhang** [comment]
`ui.click` is web-specific because it has node info relating to rrweb. for mobile, we would probably want to rename it to `ui.tap` or something, but still need a differentiating property so we know it's a mobile replay-specific breadcrumb

**Comment by billyvg** [comment]
We should think about how we can connect click/tap breadcrumbs w/ view hierarchies in the future too

**Comment by romtsn** [comment]
> ui.click is web-specific because it has node info relating to rrweb

fwiw we also use `ui.click` for mobile breadcrumbs, but of course can change that easily for replays.
