### ISSUE TITLE
Disable 10s granularity for DDM

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#69648]
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/69650
- [ ] https://github.com/getsentry/relay/issues/3483
- [ ] https://github.com/getsentry/sentry-options-automator/pull/1322
```

**Comment by jan-auer** [comment]
This is now completed.
