### ISSUE TITLE
[Epic] User Feedback Annotations

### ISSUE THREAD

**Issue by c298lee** [getsentry/sentry#69786]
The goal of the project is to close a large feature request, sentry users want to allow their customers to create an mark-up screen shots to better illustrate their feedback problems.

Basically, we want to solve for the cases in https://github.com/getsentry/sentry-javascript/issues/9460

[Design File](https://www.figma.com/file/34SnbIZdaYu0TBCfGcpjA3/Specs%3A-Feedback-Widget-v2?type=design&node-id=754-121&mode=design&t=sbkAMTmR28CUQmJq-0)

Hackweek example: https://github.com/getsentry/sentry-javascript/pull/11175

### Annotations
- [ ] https://github.com/getsentry/sentry-javascript/issues/11166
- [ ] https://github.com/getsentry/sentry-javascript/issues/15064
- [ ] https://github.com/getsentry/sentry-javascript/issues/15252
- [ ] Refactor & add tests
- [x] https://github.com/getsentry/sentry-javascript/issues/15117
- [x] https://github.com/getsentry/sentry-javascript/issues/15118
- [ ] https://github.com/getsentry/sentry-javascript/issues/15115
- [ ] https://github.com/getsentry/sentry-javascript/issues/15116
- [ ] https://github.com/getsentry/sentry-javascript/issues/12938
- [ ] https://github.com/getsentry/sentry/issues/84521

### Not doing
- [ ] Discuss/implement a 'select' mode where existing annotations (shapes, text, freeforms) can be re-selected, so that colors and position can be adjusted.
- [ ] Implement an undo/redo stack AND/OR a 'reset' button to remove some/all annotations

**Comment by ryan953** [comment]
closing, duplicate of https://github.com/getsentry/sentry/issues/63749

**Comment by ryan953** [comment]
Re-opened! The other one, https://github.com/getsentry/sentry/issues/63749 is more about the previous round of basic Screenshot features. 

This will be geared towards the renewed effort of annotating/drawing on top of those screenshots.

**Comment by c298lee** [comment]
Proposal:
Implementing undo, redo, selection, eraser etc would require rearchitecting all the current cropping and pen tool annotation work, and would take quite a bit of effort to do. Our user feedback widget is a way to allow people to easily give feedback and highlight their issue. Creating an image editor tool will have diminishing returns. 
Instead, I propose just creating a reset button that resets the image to the original uncropped and unannotated screenshot, in place a full undo/eraser situation. A simple pen tool with the ability to change the pen colour and line width should be sufficient to highlight things on the screenshot as well as block out any PII, and should be sufficient for most cases. For people who want to be more creative with their feedback, we will add functionality to allow people to add their own attachments to their feedback. This way, if a user wants to add some complicated annotations and visuals to explain their feedback, they can use their own image editing tools and add it as an attachment. Additionally, this feature has been requested by several customers too.

**Comment by c298lee** [comment]
We decided to pivot to a new direction: highlight and hide boxes. This will be released on a beta branch and tested out internally before GA

![Image](https://github.com/user-attachments/assets/c3babc12-2313-42a5-b213-b8c78641872f)
