### ISSUE TITLE
Implement wildcard support for metrics

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#69852]
In the context of https://github.com/getsentry/sentry/issues/69387, we discovered that wildcard support needs additional investment on the storage side. When this is possible in storage, we can implement the wildcard support as intended and tried out in https://github.com/getsentry/sentry/pull/69647
```[tasklist]
### Tasks
- [x] Add wildcard support to MQL parser grammar in snuba-sdk for use in Sentry: https://github.com/getsentry/snuba-sdk/blob/main/snuba_sdk/mql/mql.py#L25
- [ ] Add wildcard support to MQL parser visitor in snuba for conversion to Snuba AST: https://github.com/getsentry/snuba/blob/master/snuba/query/mql/parser.py#L91
- [x] Add wildcard support to MQL parser visitor: https://github.com/getsentry/snuba-sdk/blob/main/snuba_sdk/mql/mql.py#L130
- [x] Add wildcard support to MQLPrinter for correct serialization: https://github.com/getsentry/snuba-sdk/blob/2e7d96eea2c6c4cd34bdbeff3257540832685aa3/snuba_sdk/mql_visitor.py#L76
```
