### ISSUE TITLE
[Epic] Replay x Web Vitals

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#69881]
Project Details; https://www.notion.so/sentry/Web-Vitals-x-Session-Replay-Discussion-f6cde2c7d54846749eefa83d4dd9882b
1st KTTR: https://www.notion.so/sentry/Replay-Web-Vitals-Breadcrumbs-0038416a37d8462793ad47a0cbce6ff2
2nd KTTR: https://www.notion.so/sentry/Replay-Web-Vitals-Insights-ff1230303b66485f9fac7441cc34ca46

```[tasklist]
### @sentry/replay SDK - Capture Web Vitals
- [ ] https://github.com/getsentry/sentry-javascript/issues/11639
- [ ] https://github.com/getsentry/sentry-javascript/issues/12470
- [ ] Add TTFB web vitals https://github.com/getsentry/sentry-javascript/pull/12993
```

```[tasklist]
### Replay Details - Render Vitals as Breadcrumbs
- [ ] TODO: How & where will we render the breadcrumb information? https://chromewebstore.google.com/detail/web-vitals/ahfhijdlegdabablpippeagghigmibma has some prior art to reference
```

```[tasklist]
### Replay List Page - show aggregate vitals
- [ ] TODO: Update table render (see figma https://www.figma.com/file/7ejXv6UyWd9ObWYd3i8B4b/Replay-x-Web-Vitals?type=whiteboard&node-id=3-21&t=lHvmKWYMSkWbh6Pj-0)
- [ ] TODO: Do we link to the existing /performance pages?
```

```[tasklist]
### Replay Details - New Vitals Tab/Panel
- [ ] TODO: Iterate on figma https://www.figma.com/file/7ejXv6UyWd9ObWYd3i8B4b/Replay-x-Web-Vitals?type=whiteboard&node-id=3-21&t=lHvmKWYMSkWbh6Pj-0
- [ ] TODO: implement figma
```
