### ISSUE TITLE
[Epic] Mobile Replay: Public Beta Release

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#70065]
We recently kicked off our private alpha and reached out to customers (self-serve only so far) from our [wait list](https://github.com/getsentry/sentry/discussions/63138):
* https://github.com/getsentry/sentry/issues/63255

This Epic tracks progress to our next goal: Open Beta. For folks that filled out the wait list, we'll reach out to **all of your** when Open Beta starts.

```[tasklist]
### Backend
- [x] Undo killswitch: 9c99a10/src/sentry/conf/server.py#L1981-L1983
```

```[tasklist]
### UI: Mobile Replay
- [ ] https://github.com/getsentry/sentry/issues/68496
- [ ] https://github.com/getsentry/sentry/issues/67697
- [ ] https://github.com/getsentry/sentry/issues/69226
- [ ] https://github.com/getsentry/sentry/issues/69253
- [ ] https://github.com/getsentry/sentry/issues/69412
- [ ] https://github.com/getsentry/sentry/issues/69413
- [ ] https://github.com/getsentry/sentry/issues/69817
- [ ] https://github.com/getsentry/sentry/issues/69249
- [ ] https://github.com/getsentry/sentry/issues/70588
- [ ] https://github.com/getsentry/sentry/issues/72232
- [ ] https://github.com/getsentry/sentry/issues/68109
- [ ] https://github.com/getsentry/sentry/issues/72233
- [ ] https://github.com/getsentry/sentry/issues/73290
- [ ] https://github.com/getsentry/sentry/issues/70058
- [ ] https://github.com/getsentry/sentry/issues/67842
- [ ] https://github.com/getsentry/sentry/issues/71665
- [ ] https://github.com/getsentry/sentry/issues/70687
- [ ] Merge rrweb changes upstream
- [ ] https://github.com/getsentry/sentry/issues/74324
```

```[tasklist]
### SDKs
- [ ] https://github.com/getsentry/team-replay/issues/444
- [ ] https://github.com/getsentry/sentry/issues/63248
- [ ] https://github.com/getsentry/sentry/issues/68287
- [x] Remove reliance on tags for replayId in events. Context should be used instead
- [ ] Clock drift fix: use UTC, or single time clock read, or stopwatch
- [ ] Flutter: figure out dynamic frame rate: @vaind
- [ ] https://github.com/getsentry/sentry/issues/70446
```

```[tasklist]
### SDK Android
- [x] Adjust rectangle overlays height to the actual text size (we only cared about width so far, but height would also nice) https://github.com/getsentry/sentry-java/pull/3466
- [x] Add touches/gestures https://github.com/getsentry/sentry-java/pull/3390 https://github.com/getsentry/sentry-java/pull/3473
- [x] Send screen name as navigation to drive the "URL" above the video https://github.com/getsentry/sentry-java/pull/3505
- [x] Resume when app on the foreground
- [ ] https://github.com/getsentry/sentry-java/issues/3558
- [ ] https://github.com/getsentry/sentry-java/issues/3559
- [x] replay for ANR for session mode
- [ ] replay for ANR on buffer mode
- [ ] Capture replay on uncaught exceptions in RN layer
- [ ] Provide a way to redact certain views via `view.setTag("sentry-block|sentry-mask")`
- [ ] Support Jetpack Compose components masking
- [ ] Use different OSS apps to test, e.g. duckduckgo, nowinandroid, pocketcasts + RN apps (expensify)
- [ ] https://github.com/getsentry/sentry/issues/74074
- [ ] https://github.com/getsentry/sentry-java/issues/3560
- [ ] https://github.com/getsentry/sentry-java/issues/3574
```

```[tasklist]
### SDK iOS
- [x] Add breadcrumbs
- [x] Add touches as breadcrumbs
- [x] Send screen name as navigation to drive the "URL" above the video
- [x] Set `replayId` to link replay and errors
- [x] Resume when app on the foreground
- [ ] Capture replay on native crash
- [ ] Handle orientation changes (send rrweb event/breadcrumb and change video size)
- [ ] Handle offline recording (do not capture segments while offline, but keep recording and capture longer ones when back online)
- [ ] Provide a way to redact specific views via UIView extension
- [ ] Use different OSS apps to test, e.g. duckduckgo, nowinandroid, pocketcasts + RN apps (expensify)
- [ ] Redact only text within element (instead of redacting the whole element)
- [ ] Capture replay on uncaught exceptions in RN layer
- [ ] https://github.com/getsentry/sentry-cocoa/issues/4142
- [ ] Resumed replay is missing app foreground bredcrumbs (replay starts after the bredcrumbs)
- [ ] Replay segments have ~2 second gaps
- [ ] https://github.com/getsentry/sentry-cocoa/issues/4155
```

```[tasklist]
### SDK React Native
- [x] Use React Component names in breadcrumbs https://github.com/getsentry/sentry-react-native/pull/3846
- [x] Navigation breadcrumbs from RN https://github.com/getsentry/sentry-react-native/pull/3846
- [x] Network breadcrumbs (network tab) https://github.com/getsentry/sentry-react-native/pull/3912
- [x] Set `replay.url` property from RN (the RN screen name) https://github.com/getsentry/sentry-react-native/pull/3927
- [x] Capture JS console https://github.com/getsentry/sentry-react-native/pull/3928 https://github.com/getsentry/sentry-cocoa/pull/4141
- [ ] Mask all SVG on mobile (react-native-svg) https://github.com/getsentry/sentry-react-native/pull/3930
- [ ] Bump native SDKs to version supporting reading `urls` from scope (not released yet)
- [ ] -- optional tasks below
- [ ] Verify images over network are recorded in the network panel
- [ ] Add quality setting low/medium/high
- [ ] JSX Structure of the touch target
- [ ] Provide a way to redact/exclude certain React Components
- [ ] RN+iOS: Improve dev build experience: Swizzling to tell apart images from bundle
- [ ] Check react-native-webview
```

```[tasklist]
### Documentation
- [ ] Expand Data Privacy for Mobile with Replay specific information: https://docs.sentry.io/product/security/mobile-privacy/
- [ ] Include a guide for `Apple Privacy Questionnaire` to help users navigate app publishing: https://developer.apple.com/app-store/app-privacy-details/
- [ ] Include a guide for `Data safety form in Play Console`: https://support.google.com/googleplay/android-developer/answer/10787469?hl=en
- [ ] Document known limitations: Replay in offline mode, resizing, multi-window
```

This epic is part of:
* https://github.com/getsentry/sentry/issues/64379

**Comment by bruno-garcia** [comment]
Related flags:
* Player: https://github.com/getsentry/sentry-options-automator/pull/1938/
* Ingestion: https://github.com/getsentry/relay/pull/3803
* Denylist (ingestion): https://github.com/getsentry/getsentry/pull/14569
* Denylist Beta list: https://github.com/getsentry/sentry/pull/73981

**Comment by bruno-garcia** [comment]
Open Beta is live:

* https://github.com/getsentry/sentry/discussions/74322
