### ISSUE TITLE
[Epic] Hydration Errors

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#70199]
Project Details: https://www.notion.so/sentry/FY-25-Q2-Hydration-Errors-3d5673e38a2743f8819cee8fdf94b3c4#2e5548009b7c43ebab4c7889910252c6
KTTR Items:
- https://www.notion.so/sentry/Hydration-Errors-in-Issue-Platform-5949fe74682b461c981f448ceaa2b322?pvs=23
- https://www.notion.so/sentry/Hydration-Errors-diff-tooling-936ba93dceff4fdea6c5cf543857ac86
- https://www.notion.so/sentry/Hydration-Errors-GA-219e258cfbdc43e1b7216c1a3b1b14ff

These new Issues are made visible via this flag: https://flagr.getsentry.net/#/flags/621

Relates to https://github.com/getsentry/sentry/issues/45664

```[tasklist]
### Core LA Tasks
- [ ] https://github.com/getsentry/sentry/issues/71392
- [ ] https://github.com/getsentry/sentry/issues/71395
- [ ] https://github.com/getsentry/sentry/issues/71396
- [ ] https://github.com/getsentry/sentry/issues/72067
- [ ] https://github.com/getsentry/sentry/issues/72068
- [x] https://sentry.sentry.io/issues/5451660180/?project=6520785&referrer=github-pr-bot
- [ ] https://github.com/getsentry/sentry/issues/72150
- [ ] https://github.com/getsentry/sentry/issues/72151
- [ ] https://github.com/getsentry/sentry/issues/72152
- [ ] https://github.com/getsentry/sentry/issues/72266
```

```[tasklist]
### Diff Tooling
- [ ] Add icons to diff-tool tabs, to differentiate text-based tools from image-based ones
- [x] Implement an image-diff tool where two images (replay views) are stacked atop each other, and a slider reveals parts of one or the other. AKA the "image slider" tool.
- [ ] https://github.com/getsentry/sentry/issues/74361
- [x] Replace the inline diff-tools tab bar with a single image-based tool on the Issue Details page, users can still click to open the modal which contains all diff tools.
- [ ] https://github.com/getsentry/sentry/issues/74358
- [ ] https://github.com/getsentry/sentry/issues/74360
- [ ] https://github.com/getsentry/sentry/issues/74458
```

```[tasklist]
### Fit & Finish Tasks - GA
- [ ] https://github.com/getsentry/sentry/issues/72493
- [ ] https://github.com/getsentry/sentry/issues/72123
- [ ] https://github.com/getsentry/sentry-docs/issues/10277
- [ ] https://github.com/getsentry/sentry/issues/72180
- [ ] https://github.com/getsentry/sentry/issues/72124
- [ ] https://github.com/getsentry/sentry/issues/72377
- [x] https://github.com/getsentry/sentry/issues/74357
- [ ] https://github.com/getsentry/sentry/issues/77971
- [ ] https://github.com/getsentry/sentry/issues/74456
- [ ] https://github.com/getsentry/sentry/issues/74501
- [ ] https://github.com/getsentry/sentry/issues/74732
- [ ] https://github.com/getsentry/sentry/issues/74734
- [ ] https://github.com/getsentry/sentry/issues/74942
- [ ] https://github.com/getsentry/sentry-docs/issues/10852
- [ ] https://github.com/getsentry/sentry/issues/75073
- [ ] https://github.com/getsentry/sentry/issues/75689
- [ ] https://github.com/getsentry/sentry/issues/76079
- [ ] https://github.com/getsentry/sentry/issues/77210
- [ ] https://github.com/getsentry/sentry/issues/77209
- [ ] https://github.com/getsentry/sentry/issues/77211
- [ ] https://github.com/getsentry/sentry/issues/77212
- [ ] https://github.com/getsentry/sentry/issues/77222
- [ ] https://github.com/getsentry/team-replay/issues/478
```

**Comment by ryan953** [comment]
For React 19 users this might be a good fit: https://www.notion.so/sentry/React-JS-19-23a7a2c5f88d4ef59a4b9647c84333a3

With that they could disable their inbound filter and start consuming error-quota and get hydration-errors. These would include useful stack-traces. If the React19 user also has replays installed, then they'd get replays attached.
