### ISSUE TITLE
[Epic] Remote Configuration - Internal Alpha

### ISSUE THREAD

**Issue by cmanallen** [getsentry/sentry#70942]
```[tasklist]
### Web UI
- [x] [Add API blueprint](https://github.com/getsentry/sentry/pull/70805/files)
- [x] [Add API endpoints](https://github.com/getsentry/sentry/pull/70799)
- [x] Add Web UI
```

```[tasklist]
### SDK
- [x] [Add protocol blueprint](https://github.com/getsentry/sentry/pull/70805/files)
- [x] [Add Javascript SDK support](https://github.com/getsentry/sentry-javascript/pull/12090)
- [x] ~~[Add Python SDK support](https://github.com/getsentry/sentry-python/pull/3041)~~ (Moved to post alpha)
- [x] Add configuration proxy endpoint
```

```[tasklist]
### Documentation
- [x] [Explore Solution Space](https://www.notion.so/sentry/Remote-Config-Tech-braindump-0567916007bd453daa0e35fb95bd6761)
- [x] [Write Delivery Mechanism DACI and Receive Approval](https://www.notion.so/sentry/DACI-Remote-Configuration-Delivery-Mechanism-530e40d7ecc943f4a15c69d427760f9c)
- [x] Add internal infrastructure documentation
```
