### ISSUE TITLE
Instrument Metrics API endpoints to track SLOs per endpoint by moving to individual files

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#71228]
We currently have certain DataDog monitors per-file, but since the Metrics API endpoints are all in the same file, this does not really give us a lot of information about the speed, request size, error ratio, etc. of the metrics API endpoints. Instrumenting these APIs would help us understand the quality level of our APIs, as well as potential problems as they build up over time or suddenly happen.
```[tasklist]
### Tasks
- [x] Factor out OrganizationMetricsSamplesEndpoint
- [ ] Factor out OrganizationMetricDetailsEndpoint
- [ ] Factor out OrganizationMetricsDetailsEndpoint
- [ ] Factor out OrganizationMetricsTagsEndpoint
- [ ] Factor out OrganizationMetricsTagDetailsEndpoint
- [ ] Factor out OrganizationMetricsDataEndpoint
- [ ] Factor out OrganizationMetricsQueryEndpoint
- [ ] Factor out OrganizationMetricsCodeLocationsEndpoint
```
