### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#71222]
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/71223
- [ ] https://github.com/getsentry/sentry/issues/71224
- [ ] https://github.com/getsentry/sentry/issues/71225
- [ ] https://github.com/getsentry/sentry/issues/71226
```
