### ISSUE TITLE
[EPIC] Custom Views Backend Changes

### ISSUE THREAD

**Issue by MichaelSun48** [getsentry/sentry#71575]
[Tech Spec (Internal Only)](https://www.notion.so/sentry/Tech-Spec-Backend-Changes-for-New-Saved-Searches-Custom-Tabs-4b4d24b16be04ff5a7addc5f8f32906a?d=12ca8fcb967f44f7b4036f560e7ef6ee#9cc98fbc95994bf6b93338efc16c2f92)

```[tasklist]
### Task list (in order)
- [ ] https://github.com/getsentry/sentry/issues/71592
- [ ] https://github.com/getsentry/sentry/issues/71589
- [ ] https://github.com/getsentry/sentry/issues/71802
- [ ] https://github.com/getsentry/sentry/issues/71590
- [ ] https://github.com/getsentry/sentry/issues/71593
- [ ] https://github.com/getsentry/sentry/issues/71580
- [ ] https://github.com/getsentry/sentry/issues/71587
- [ ] https://github.com/getsentry/sentry/issues/71594
```
