### ISSUE TITLE
Handle common 500s more gracefully

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#71973]
```[tasklist]
### Tasks
- [x] Fix SENTRY-2M4E: 404 instead of raising Invalid Params in  /api/0/organizations/{organization_id_or_slug}/metrics/tags/
- [x] Fix SENTRY-39RR: 400 instead of raising InvalidParams in /api/0/organizations/{organization_id_or_slug}/metrics/meta/ (fixed in https://github.com/getsentry/sentry/pull/71994)
- [x] Fix SENTRY-39WP: 400 instead of raising InvalidParams in /api/0/organizations/{organization_id_or_slug}/metrics/query/ (fixed in https://github.com/getsentry/sentry/pull/72204)
- [x] Fix SENTRY-38JR: 400 instead of raising UnqualifiedQueryError in /api/0/organizations/{organization_id_or_slug}/metrics/query/ - Not fixing: legitimate 500
- [x] Fix SENTRY-39SN: 400 instead of AssertionError for parse_mql in /api/0/organizations/{organization_id_or_slug}/metrics/query/ (fixed in https://github.com/getsentry/sentry/pull/72204)
```
