### ISSUE TITLE
Public launch flows cleanup

### ISSUE THREAD

**Issue by obostjancic** [getsentry/sentry#71983]
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/72091
- [ ] https://github.com/getsentry/sentry/pull/72089
- [ ] https://github.com/getsentry/sentry/pull/72086
- [ ] https://github.com/getsentry/getsentry/pull/14207
- [ ] https://github.com/getsentry/getsentry/pull/14208
```
