### ISSUE TITLE
Phase out feature flags

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#72392]
`organizations:metrics-blocking`
`organizations:use-metrics-layer-in-alerts`
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/72383
- [ ] https://github.com/getsentry/sentry/pull/72384
- [ ] https://github.com/getsentry/getsentry/pull/14246
- [ ] https://github.com/getsentry/sentry-options-automator/pull/1575
- [ ] https://github.com/getsentry/getsentry/pull/14245
- [ ] https://github.com/getsentry/getsentry/pull/14383
- [ ] https://github.com/getsentry/sentry-options-automator/pull/1660
- [ ] https://github.com/getsentry/sentry/pull/73101
- [ ] https://github.com/getsentry/sentry-options-automator/pull/1674
- [ ] https://github.com/getsentry/getsentry/pull/14402
- [ ] https://github.com/getsentry/sentry/pull/73144
```
