### ISSUE TITLE
[Epic] Update Breadcrumbs for Issues/Replays

### ISSUE THREAD

**Issue by leeandher** [getsentry/sentry#72504]
[Project Page (Internal)](https://www.notion.so/sentry/Update-Breadcrumbs-for-Issues-Replays-16eb005711f94471adefcb244977831b?pvs=4)
[Tech Spec (Internal)](https://www.notion.so/sentry/Tech-Spec-Update-Breadcrumbs-for-Issues-Replays-ddaa2d80089c4dee8f46a2c87897c725?pvs=4)
```[tasklist]
### Tasks
- [x] Create backend feature flag
- [x] Create hook for rendering new UI with flag/query param
- [x] Create base timeline components and expected data structure
- [x] Connect event breadcrumbs to new timeline components
- [x] Connect replay breadcrumbs to new timeline components
- [x] Implement text search for event breadcrumbs
- [x] Implement sorting for event breadcrumbs
- [x] Implement timestamp format toggle for event breadcrumbs
- [x] Incorporate new virtualized list API for issue breadcrumbs
- [x] Expand full JSON on search for breadcrumbs
- [x] Add back custom rendering for known breadcrumbs
- [x] Implement filtering for event breadcrumbs
- [x] Investigate `sentry.x` breadcrumbs
- [x] Audit icons and colors used across replays and issues
- [x] Add analytics for new interactable components
- [x] Create dashboards for summarizing analytics
- [x] Update public documentation/screenshots as needed
- [x] Add changelog
- [ ] Remove feature flags and unused components
```
