### ISSUE TITLE
[Epic] Span Attribute Metrics Extraction

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#72679]
### What is it?
Allow users to configure span-based metrics directly in the Sentry UI. They can be created based on default span attributes such as `span.duration` or custom span attributes that a user can define through custom instrumentation.

These metrics can then be queried in the Metrics explorer page, used in custom dashboard widgets and in metric alerts.

![Image](https://github.com/getsentry/sentry/assets/26696515/1855b627-bc4b-43d8-9db4-f2bb9b638e8b)

### Tech Spec
https://www.notion.so/sentry/Span-Attribute-Extraction-6c2396babe9f4fba958427d3869e3990

### PRD
https://www.notion.so/sentry/Span-Attribute-Extraction-086bb92323914d389a2d88bd82f08dd9

```[tasklist]
### PoC
- [ ] https://github.com/getsentry/sentry/issues/72849
- [ ] https://github.com/getsentry/sentry/issues/72850
- [ ] https://github.com/getsentry/sentry/issues/72851
- [ ] https://github.com/getsentry/relay/issues/3748
```

```[tasklist]
### E2E Working Solution
- [ ] https://github.com/getsentry/sentry/issues/73149
- [ ] https://github.com/getsentry/sentry/issues/73156
- [ ] https://github.com/getsentry/sentry/issues/73158
- [ ] https://github.com/getsentry/sentry/issues/73164
- [ ] https://github.com/getsentry/sentry/issues/73165
- [ ] https://github.com/getsentry/sentry/issues/73171
- [ ] https://github.com/getsentry/sentry/issues/73154
- [ ] https://github.com/getsentry/sentry/issues/73170
- [ ] https://github.com/getsentry/sentry/issues/73151
- [ ] https://github.com/getsentry/sentry/issues/73426
- [ ] https://github.com/getsentry/sentry/issues/73166
- [ ] https://github.com/getsentry/sentry/issues/73163
- [ ] https://github.com/getsentry/sentry/issues/73159
- [ ] https://github.com/getsentry/sentry/issues/73155
- [ ] https://github.com/getsentry/sentry/issues/73418
- [ ] https://github.com/getsentry/sentry/issues/73161
- [ ] https://github.com/getsentry/sentry/issues/73565
- [ ] https://github.com/getsentry/sentry/issues/73152
- [ ] https://github.com/getsentry/sentry/issues/73561
- [ ] https://github.com/getsentry/sentry/issues/73420
- [ ] https://github.com/getsentry/sentry/issues/73174
- [ ] https://github.com/getsentry/sentry/issues/73162
- [ ] https://github.com/getsentry/sentry/issues/73179
- [ ] https://github.com/getsentry/sentry/issues/73562
```

```[tasklist]
### Internal Testing
- [x] Dogfood with gibpotato
- [ ] https://github.com/getsentry/sentry/issues/74123
- [ ] https://github.com/getsentry/sentry/issues/73160
- [ ] https://github.com/getsentry/sentry/issues/74125
- [ ] https://github.com/getsentry/sentry/issues/74124
- [ ] https://github.com/getsentry/sentry/issues/74126
- [ ] https://github.com/getsentry/sentry/issues/74127
- [ ] https://github.com/getsentry/sentry/issues/74128
- [ ] https://github.com/getsentry/sentry/issues/73925
```
