### ISSUE TITLE
Remove 1min custom metric alerts

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#72843]
```[tasklist]
### Tasks
- [x] Remove the option from UI
- [x] Reach out to orgs that use this today
- [ ] Change interval of existing 1minute alerts to 5 minutes
```
