### ISSUE TITLE
[EPIC] Streamlining Issue Details

### ISSUE THREAD

**Issue by scttcper** [getsentry/sentry#73747]
Tech spec - https://www.notion.so/sentry/Tech-Spec-Streamlining-Issue-Details-6c29b340b6a948858c1fc863d0234212?pvs=4
Figma - https://www.figma.com/design/p2DOzd1RwAHQbq0v6KaYmF/Q2-Issue-Details?node-id=430-6233&t=agIKtZo34vqdVzUM-4
PRD - https://www.notion.so/sentry/Streamlining-Issue-Details-UI-UX-35d5111e0b2947979655682add5225ea

Slack channel - [#proj-issue-details-improvements](https://sentry.slack.com/archives/C0646LUCC1Z)

```[tasklist]
### Redesigned Issue Details Layout
- [ ] https://github.com/getsentry/sentry/issues/73753
- [ ] https://github.com/getsentry/sentry/issues/73758
- [ ] https://github.com/getsentry/sentry/issues/73768
- [ ] https://github.com/getsentry/sentry/issues/73772
- [ ] https://github.com/getsentry/sentry/issues/75501
- [ ] https://github.com/getsentry/sentry/issues/76010
- [ ] https://github.com/getsentry/sentry/issues/76014
```

```[tasklist]
### Issue Details Search
- [ ] https://github.com/getsentry/sentry/issues/73776
- [ ] https://github.com/getsentry/sentry/issues/73777
- [ ] https://github.com/getsentry/sentry/issues/73779
- [ ] https://github.com/getsentry/sentry/issues/73773
- [ ] https://github.com/getsentry/sentry/issues/73759
- [ ] https://github.com/getsentry/sentry/issues/73781
```

```[tasklist]
### Redesigned Components
- [ ] https://github.com/getsentry/sentry/issues/73782
- [ ] https://github.com/getsentry/sentry/issues/73784
- [ ] https://github.com/getsentry/sentry/issues/73794
- [ ] https://github.com/getsentry/sentry/issues/73796
```

```[tasklist]
### Cleanup
- [ ] https://github.com/getsentry/sentry/issues/73800
- [ ] https://github.com/getsentry/sentry/issues/73799
```
