### ISSUE TITLE
[EPIC] Upgrading search in non-issues surfaces

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#74240]
See https://github.com/getsentry/sentry/issues/68671 for the initial introduction of the new search component to issues.

The next step is to replace all other search bars with the new component:

- Releases
- Traces
- Metrics
- Profiles
- Replays
- Discover
- User Feedback
- Dashboards
- Project Details
- Alerts
- Performance

```[tasklist]
### Releases
- [ ] https://github.com/getsentry/sentry/issues/74242
- [ ] https://github.com/getsentry/sentry/issues/74309
- [ ] https://github.com/getsentry/sentry/issues/74991
```

```[tasklist]
### Traces
- [ ] https://github.com/getsentry/sentry/issues/74242
- [ ] https://github.com/getsentry/sentry/issues/74300
- [ ] https://github.com/getsentry/sentry/issues/74302
- [ ] https://github.com/getsentry/sentry/issues/74276
- [ ] https://github.com/getsentry/sentry/issues/74304
- [ ] https://github.com/getsentry/sentry/issues/74309
- [ ] https://github.com/getsentry/sentry/issues/75003
```

```[tasklist]
### Metrics
- [ ] https://github.com/getsentry/sentry/issues/74242
- [ ] https://github.com/getsentry/sentry/issues/74305
- [ ] https://github.com/getsentry/sentry/issues/74302
- [ ] https://github.com/getsentry/sentry/issues/74350
- [ ] https://github.com/getsentry/sentry/issues/75004
```

```[tasklist]
### Profiles
- [ ] https://github.com/getsentry/sentry/issues/74302
- [ ] https://github.com/getsentry/sentry/issues/74242
- [ ] https://github.com/getsentry/sentry/issues/74305
- [ ] https://github.com/getsentry/sentry/issues/74309
- [ ] https://github.com/getsentry/sentry/issues/75005
```

```[tasklist]
### Replays
- [ ] https://github.com/getsentry/sentry/issues/74309
- [ ] https://github.com/getsentry/sentry/issues/74304
- [ ] https://github.com/getsentry/sentry/issues/75006
```

```[tasklist]
### Discover
- [ ] https://github.com/getsentry/sentry/issues/74309
- [ ] https://github.com/getsentry/sentry/issues/74302
- [ ] https://github.com/getsentry/sentry/issues/74305
- [ ] https://github.com/getsentry/sentry/issues/74312
- [ ] https://github.com/getsentry/sentry/issues/74242
- [ ] https://github.com/getsentry/sentry/issues/75007
```

```[tasklist]
### Feedback
- [ ] https://github.com/getsentry/sentry/issues/74242
- [ ] https://github.com/getsentry/sentry/issues/74309
- [ ] https://github.com/getsentry/sentry/issues/75008
```

```[tasklist]
### Dashboards
- [ ] https://github.com/getsentry/sentry/issues/74302
- [ ] https://github.com/getsentry/sentry/issues/74305
- [ ] https://github.com/getsentry/sentry/issues/74312
- [ ] https://github.com/getsentry/sentry/issues/74242
- [ ] https://github.com/getsentry/sentry/issues/74350
- [ ] https://github.com/getsentry/sentry/issues/75009
```

```[tasklist]
### Project Details
- [ ] https://github.com/getsentry/sentry/issues/74242
- [ ] https://github.com/getsentry/sentry/issues/75010
```

```[tasklist]
### Alerts
- [ ] https://github.com/getsentry/sentry/issues/74701
- [ ] https://github.com/getsentry/sentry/issues/74753
- [ ] https://github.com/getsentry/sentry/issues/74754
- [ ] https://github.com/getsentry/sentry/issues/75011
```

```[tasklist]
### Performance
- [ ] https://github.com/getsentry/sentry/issues/74754
- [ ] https://github.com/getsentry/sentry/issues/75019
```
