### ISSUE TITLE
Insights Toolbars Design Audit

### ISSUE THREAD

**Issue by gggritso** [getsentry/sentry#74424]
Some QA feedback from Vasudha! A few minor tweaks to our metric ribbons, dropdowns, etc.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/74726
- [ ] https://github.com/getsentry/sentry/pull/74342
- [ ] https://github.com/getsentry/sentry/pull/74164
- [ ] https://github.com/getsentry/sentry/pull/74161
- [ ] https://github.com/getsentry/sentry/pull/74159
- [ ] https://github.com/getsentry/sentry/pull/74158
- [ ] https://github.com/getsentry/sentry/pull/74157
- [ ] https://github.com/getsentry/sentry/pull/74497
```
