### ISSUE TITLE
Insights - Mobile Vitals

### ISSUE THREAD

**Issue by markushi** [getsentry/sentry#75120]
A mobile module providing an entry point, top level metrics and the ability to drill deeper into app starts, screen loads and UI jank.

Internal [notion doc for feedback](https://www.notion.so/sentry/Mobile-Vitals-Feedback-0e136e5cd0784c3192beeae3dd4db085) here.

![Image](https://github.com/user-attachments/assets/71922621-a4bc-495a-a215-10c1133846db)

```[tasklist]
### Tasks
- [ ] Add tooltips for table columns to clearly explain what they represent.
- [ ] Switch to slow and frozen frame rates
- [ ] Add platform switcher for RN projects
- [ ] Remove screens label
- [ ] Sub-Modules: Fix padding
- [ ] Sub-Modules: Have proper routing
- [ ] Fix missing unit for frame delay
- [ ] Add release selectors
- [ ] Update docs / sales
```

**Comment by kahest** [comment]
possible GA/post GA item: https://github.com/getsentry/sentry/issues/77560

**Comment by kahest** [comment]
we aligned internally that we will expand the scope and adapt the timeline a little:
- include screen rendering in EA/GA (currently LA)
- rename to Mobile Vitals
- public comms push (blog post, email outreach)
- SE training

updated timeline:
 - EA: Early Feb
 - GA: Mid-late Feb

**Comment by markushi** [comment]
There's now a new project for post GA topics and tasks: https://github.com/getsentry/projects/issues/703

**Comment by kahest** [comment]
GA rollout currently at 50%

**Comment by markushi** [comment]
Rollout is now at 100%, Docs have been merged as well.
