### ISSUE TITLE
[EPIC] Phase out low priority symbolication

### ISSUE THREAD

**Issue by loewenheim** [getsentry/sentry#76786]
Since Symbolicator autoscales now, we hopefully shouldn't need the LPQ machinery anymore.

### Things that remain to be done:
- [x] https://github.com/getsentry/getsentry/pull/15531
- [x] https://github.com/getsentry/sentry/pull/79965
- [x] https://github.com/getsentry/sentry/pull/79976
- [x] https://github.com/getsentry/sentry/pull/80050
- [x] https://github.com/getsentry/sentry/pull/80046
- [x] https://github.com/getsentry/sentry-options-automator/pull/2575
- [x] https://github.com/getsentry/getsentry/pull/15569
- [x] https://github.com/getsentry/getsentry/pull/15601
- [x] https://github.com/getsentry/getsentry/pull/15604
- [x] https://github.com/getsentry/ops/pull/12668
- [x] OPS Infra removal https://getsentry.atlassian.net/browse/INF-319
- [x] https://github.com/getsentry/ops/pull/12748
- [x] https://github.com/getsentry/sentry/pull/80310

**Comment by loewenheim** [comment]
The first step is https://github.com/getsentry/sentry/pull/76788.

**Comment by loewenheim** [comment]
Increase JS Symbolicator max replicas to absorb LPQ traffic https://github.com/getsentry/ops/pull/11989

**Comment by loewenheim** [comment]
We're currently running on 80% of LPQ traffic going to normal Symbolicators. Before we switch it off entirely, we should increase Symbolicator autoscaling https://github.com/getsentry/ops/pull/12039.

**Comment by loewenheim** [comment]
No traffic has gone to the LPQ since https://github.com/getsentry/sentry-options-automator/pull/2324 and autoscaling is in a decent state.

**Comment by Dav1dde** [comment]
Created a INF request to remove the LPQ Infrastructure: [INF-319](https://getsentry.atlassian.net/browse/INF-319)

**Comment by olksdr** [comment]
done!
