### ISSUE TITLE
Divide up insights into Mobile / Web / Platform / AI

### ISSUE THREAD

**Issue by DominikB2014** [getsentry/sentry#77572]
_This project is being fleshed out, broadly:_

- We want landing pages for each domain which would include a list of the specific root spans for that domain, e.g., screens for mobile, pages for web, routes for backend.
- We want to keep the existing insights modules, but they may be tabs on these pages.

See: https://www.notion.so/sentry/Proposal-Interim-Insights-Cleanup-a48686b74353458c86eae018aafdb88b?pvs=4

**Notes:**

* As part of this work we should remove the alternate Web Vitals UI from the Transaction Summary page.

```[tasklist]
### Tasks
- [x] Scope down domain views by transaction op
- [x] ensure performance pages contain correct headers/breadcrumbs
- [x] Bring back performance in sidebar and add domain views under insights
- [x] Name http module "Network Requests" in the frontend tab and "Outbound API Requests" in the backend
- [x] Add app starts, pageload and screen recording modules
- [x] Fix breadcrumbs not appending in module subpages
- [x] Fix header title not updating within module subpages
- [x] Module Tabs show "you do not have access to this feature" on AM1, we should make this nicer or hide the tabs
- [x] Fix give feedback button incorrectly place in header
- [x] Link web vitals widget in frontend overview page to new web vitals
- [x] make table exactly as they are now, just reorder columns operation next to transaction
- [x] Make bottom 3 charts the same for all views
- [x] add missing subpages for mobile screens
- [x] missing view trends button
- [ ] Create banner on transaction web vitals tab to notify that this view is going away (related to #78060)
- [ ] (nice to have) Sorting domain view table
- [ ] (nice to have) figure out transaction vs route vs pages vs something else for column header
- [ ] (nice to have): remove project column with one project
```

**Comment by bcoe** [comment]
Ben's QAing:

## Frontend:

- [ ] breadcrumbs not updated when traversing into Pages, Queries, Domains, from Insights view:

![Image](https://github.com/user-attachments/assets/bc44accf-8282-4a9a-9af0-b85deae4aadd)

☝ Note the breadcrumb missing the "page".
