### ISSUE TITLE
Milestone 1: Add options for querying EAP dataset into the widget builder

### ISSUE THREAD

**Issue by narsaynorath** [getsentry/sentry#78264]
After the correct EAP aggregates and fields are identified, allow users to select them in the widget builder by adding a new dataset that encapsulates the new options.

## Tasks
- [x] Introduce the EAP dataset - #79412 
- [x] Ensure all of insights fields and aggregations are exposed
- [x] Add a custom filter bar that scopes tags to specific EAP tags and values
- [x] Add support for timeseries charts
