### ISSUE TITLE
[Uptime] Record environment for uptime alerts and set issue created to it

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry#78342]
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/78332
- [ ] https://github.com/getsentry/sentry/pull/78351
- [ ] Pass environment on the frontend
```
