### ISSUE TITLE
[Epic] Metric Issues

### ISSUE THREAD

**Issue by snigdhas** [getsentry/sentry#78400]
[PRD](https://www.notion.so/sentry/Custom-Metric-Issues-e035bde25dae4b8fbd19f0e461b94d76?pvs=25)
[Tech Spec](https://www.notion.so/sentry/Tech-Spec-Metric-Issues-20985131b1a147a080ae01a78b47cd59)

```[tasklist]
### Milestone 1: Define a metric issue in issue platform
- [ ] https://github.com/getsentry/sentry/issues/78883
- [ ] Translate `Incident` data to `IssueOccurrenceData`
- [ ] Generate unique fingerprints for each metric issue
```

```[tasklist]
### Milestone 2: Add metric alert action to create a new issue
```
```[tasklist]
### Milestone 3: Display issue and alert data in metric issue details
```
```[tasklist]
### Milestone 4: Notify users on metric issue changes via workflow alerts
```

```[tasklist]
### Migrations, Testing, and Release
```
