### ISSUE TITLE
[Epic] Migrate UserReport-related services to Feedback Issues

### ISSUE THREAD

**Issue by aliu39** [getsentry/sentry#79859]
## Background info:
Since SDK v8 and the release of the UF widget, there are 2 data formats for feedback. “User reports” in Postgres, and “Feedback issues” in Clickhouse. Feedback issues are a superset of user reports and newer, so **all user-facing services should work with feedback issues.**

Currently:
![Image](https://github.com/user-attachments/assets/c0887669-4bbb-45cd-9b06-6fc8fe80407e)
[source](https://develop.sentry.dev/application-architecture/feedback-architecture/#sentry-ui)
____________________________________________________

### Desired result:
Issue details “User Feedback” tab shows feedback issues associated with the current event, making use of the associatedEventId field in the feedback context.

### Motivation:
Currently this tab only shows user reports, which come from the crash report modal and older, deprecated SDKs and endpoints. **If a user tries to associate events to their widget feedback, it won't show up in the UF tab**

### Tasks:

- [ ] Investigate what field to filter by and how to write the API query
    1. event.contexts.feedback.associatedEventId
    2. event.tags[“associated event id”]
        - Are there any drawbacks to this? e.g. Performance, data duplication
- [ ] share a spec/RFC with issues team and get their approval
- [ ] Query `/issues` from the UF tab in the frontend, using the query from above task.
    - [ ] Make a FF and start with enabling for replay team only
    - Code refs:
      - [useGroupUserFeedback.tsx](https://github.com/getsentry/sentry/blob/8b4d7250086d4df4c0980222b8ca12741dccfe3f/static/app/views/issueDetails/useGroupUserFeedback.tsx#L15-L20)
      - [groupUserFeedback.tsx](https://github.com/getsentry/sentry/blob/8b4d7250086d4df4c0980222b8ca12741dccfe3f/static/app/views/issueDetails/groupUserFeedback.tsx#L20-L99)
- [ ] Determine a rollout plan and make load/performance measurements.
- [ ] Reach out to users who’ve reported issues (can incl them in EA)

### Follow-ups:
- Support filters by event ID / "has_linked_error" in feedback list page
- Link to feedback details from issue details

____________________________________________________

### Desired results:
Return widget feedbacks and extra fields isSpam, hasSeen, traceId, replayId, groupId (of feedback) etc
- Query clickhouse for all data, since these fields aren't available in Postgres.
- Response must be backward compatible (include the same fields as current schema)
- Support search filters where appropriate?

### Motivation:
1. Users are requesting these fields after GA of new feedback. We point them to `/issues` in docs but many are still confused.
2. Like issue details, it may be confusing why we’re not returning widget feedbacks here.

### Cons:
- We're already directing users to `/issues` in [the api doc](https://docs.sentry.io/api/projects/list-a-projects-user-feedback/)
- After updating issue details, we, internally, have no use for this endpoint. **Alternative is to unpublish it.**

Decision should be consistent between the Organization, Project (most used) and Group endpoints. 

Tasks:
- [ ] Determine the search query util to use (see GroupIndexEndpoint’s)
- [ ] Figure out how to get the current response fields from search response
- [ ] Decide on the list of new fields, and how to get from search response
- [ ] Decide on list of search filters and how to parse them
- [ ] Update each endpoint's code, gated w/a FF, using knowledge from tasks 1-4
    - [ ] Project
    - [ ] Organization
    - [ ] Group
- [ ] Roll out
- [ ] Update docs

### Follow-ups
- If we stop querying Postgres, we could garbage collect user reports after shimming, or make a task to delete periodically. **Saves postgres storage cost** -> how many rows is `sentry_userreport` right now?
    - note the table is also queried by redash dashboards for debugging. https://github.com/getsentry/team-replay/issues/477 helps replace them.

____________________________________________________

## Milestone 3: Ongoing work to support a `captureFeedback` API in all SDK platforms.
Branched off to
- https://github.com/getsentry/sentry/issues/82252

### Motivation:

1. Benefits of new format:
- has all the context of a regular event, incl environment, trace, replay, breadcrumbs, user..
- associated event is optional: allows users to collect generic feedback
- don't need to wait for assoc event to be ingested, handle invalid/expired event ids, etc. Either the feedback is ingested, or it's not.
- less models to store/shim

2. The shim pipeline is inefficient and complicated to maintain

Today [Datadog](https://app.datadoghq.com/dashboard/z3p-ajn-5ma/user-feedback) shows **128k old v 7k new (18:1) envelopes in the last week.** The majority may be from gaming platforms.

**Comment by aliu39** [comment]
Potential problems:
- efficiency + increased load when querying Snuba from issue details
- same, but from the public endpoint
- losing the redash queries we use for UserReport usage analytics

**Comment by aliu39** [comment]
Related: https://github.com/getsentry/sentry/issues/77374#issuecomment-2359225953

**Comment by aliu39** [comment]
Related
- https://github.com/getsentry/sentry-docs/issues/10822

**Comment by aliu39** [comment]
Closing this as not planned because it is very difficult to query clickhouse by issue id. SDK work is still being tracked in https://github.com/getsentry/sentry/issues/82252 and a workaround to link new feedbacks in issue details was merged in https://github.com/getsentry/sentry/pull/89685
