### ISSUE TITLE
[epic] Automatic code mappings & in-app frames for Java projects

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#79888]
The Java SDK cannot determine in-app frames for customer issues. In some cases, it does create it based on [the app package identifier](https://github.com/getsentry/sentry-java/blob/b11dc55cfc01379e481be60de78b512191128a25/sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java#L335-L339).

**NOTE**: Some Java SDKs do mark in-app frames: Spring Boot and Android.

**NOTE**: At the moment, this system will only work for customers using the GitHub integration. Other SCMs will need to invest in implementing the [get trees repo functionality](https://github.com/getsentry/sentry/blob/409351a9021b779031695974e3286dea1ac9f5e3/src/sentry/integrations/source_code_management/repo_trees.py#L39).

**DISCLAIMER**: For the privacy-conscious developer, source code contents are not used; only the file paths.

Relying on customers setting up their in-app frames with Stack Trace Rules is not successful.

Without in-app frames, the following Sentry features cannot work:

- Stack trace linking
- Code coverage linking (if applicable)
- GitHub pull request comments
- Suspect Commits
- Auto-assignments based on CODEOWNERS

Only a few projects have Java stack traces with in-app frames, thus, the Sentry experience is handicapped.

The idea is that we create a code mapping and a stack trace rule to map from the `module` or `package` in the error (e.g. `com.foo.bar`) to the file (`com/foo/bar.java`) representing the file in their repositories.

Automatically generating code mappings is based on [the documented manual step of creating code mappings by developers](https://docs.sentry.io/platforms/java/source-context/#setting-up-code-mappings).

We already derive code mappings for other languages ([1](https://blog.sentry.io/code-mappings-and-why-they-matter/)). The novelty of this project is that we will also **create the stack trace rules.**

Once we derive the code mapping, we can add this stack trace rule for the project:
```
/* Sentry added this stack trace rule to have in-app frames */
stack.module:com.example.foo.** +app
```

Task list:
- [x] #84226
- [x] #84692
- [x] Dry-run in-app rules & collect metrics
- [x] Fix any errors from the dry-run stage
- [x] Metrics to measure change
- [x] Prepare docs for auto in-app stack trace rules
- [x] Enable for EA & handle feedback
- [x] Enable for GA & handle feedback
- [x] Write [changelog](https://changelog.sentry.dev/changelog/)
- [x] Remove options and feature flags

**Comment by armenzg** [comment]
I have enabled this for GA orgs this morning.
