### ISSUE TITLE
[Crons] Add crons overview as a backend insights module

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry#82428]
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/82329
- [ ] https://github.com/getsentry/sentry/pull/82376
- [ ] https://github.com/getsentry/sentry/pull/83029
```
