### ISSUE TITLE
[Uptime] Implement simple overview page under Backend Insights

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry#82422]
For now this is just a simple list (without timeline) that displays a paginated list of uptime monitors (uptime alerts) as a module under backend insights.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/82376
- [ ] https://github.com/getsentry/sentry/pull/82420
- [ ] Add empty list page
- [ ] Connect listing page to uptime API
```
