### ISSUE TITLE
[Mobile Replay] Add banner re: grace period for beta organizations after GA

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#82651]
### TODO for Jan 6 2025

Add banner on Replay Index re: grace period for Mobile Replay beta organizations after GA (targeting Jan 6)

- [ ] Mention there is a two month grace period of unlimited usage until March 6, and after that, you need to pay for additional replays not included in your plan
- [ ] Link to Replay pricing page (https://docs.sentry.io/pricing/#replays-pricing)
- [ ] Need hard-coded list of beta organizations
